# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from __future__ import annotations
import queue
import subprocess
import threading
from pathlib import Path

# ── cross-module imports ─────────────────────────────────────────────────
from ..utils.misc import make_id, now_ts
from ..utils.text import trim

class BackgroundManager:
    def __init__(self, workdir: Path):
        self.workdir = workdir
        self.tasks: dict[str, dict] = {}
        self.notifications: queue.Queue = queue.Queue()
        self.lock = threading.Lock()

    def run(self, command: str, timeout: int = 120) -> str:
        task_id = make_id("bg")
        with self.lock:
            self.tasks[task_id] = {
                "status": "running",
                "command": command,
                "result": None,
                "started_at": now_ts(),
            }
        th = threading.Thread(
            target=self._exec, args=(task_id, command, timeout), daemon=True
        )
        th.start()
        return f"Background task {task_id} started: {command[:80]}"

    def _exec(self, task_id: str, command: str, timeout: int):
        try:
            r = subprocess.run(
                command,
                shell=True,
                cwd=self.workdir,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            output = trim((r.stdout + r.stderr).strip())
            status = "completed"
        except Exception as exc:
            output = f"Error: {exc}"
            status = "error"
        with self.lock:
            task = self.tasks.get(task_id, {})
            task.update(
                {
                    "status": status,
                    "result": output or "(no output)",
                    "finished_at": now_ts(),
                }
            )
            self.tasks[task_id] = task
        self.notifications.put(
            {
                "task_id": task_id,
                "status": status,
                "result": (output or "(no output)")[:500],
            }
        )

    def check(self, task_id: str | None = None) -> str:
        with self.lock:
            if task_id:
                task = self.tasks.get(task_id)
                if not task:
                    return f"Unknown task: {task_id}"
                return f"[{task['status']}] {task.get('result') or '(running)'}"
            if not self.tasks:
                return "No bg tasks."
            lines = []
            for key, task in self.tasks.items():
                lines.append(f"{key}: [{task['status']}] {task['command'][:60]}")
            return "\n".join(lines)

    def drain(self) -> list[dict]:
        out = []
        while True:
            try:
                out.append(self.notifications.get_nowait())
            except queue.Empty:
                break
        return out

    def list_objects(self) -> list[dict]:
        with self.lock:
            return [{**v, "id": k} for k, v in self.tasks.items()]

