# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=816 original-lines=16485-16550 hash=e3208bbabbb43929

class MessageBus:
    def __init__(self, inbox_dir: Path, crypto: CryptoBox):
        self.inbox_dir = inbox_dir
        self.inbox_dir.mkdir(parents=True, exist_ok=True)
        self.crypto = crypto
        self.lock = threading.Lock()

    def _path(self, name: str) -> Path:
        return self.inbox_dir / f"{name}.json"

    def send(
        self,
        sender: str,
        to: str,
        content: str,
        msg_type: str = "message",
        extra: dict | None = None,
    ) -> str:
        if msg_type not in VALID_MSG_TYPES:
            return f"Error: invalid msg_type '{msg_type}'"
        msg = {"type": msg_type, "from": sender, "content": content, "timestamp": now_ts()}
        if extra:
            msg.update(extra)
        path = self._path(to)
        with self.lock:
            payload = self.crypto.read_json(path, [])
            if not isinstance(payload, list):
                payload = []
            payload.append(msg)
            self.crypto.write_json(path, payload)
        return f"Sent {msg_type} to {to}"

    def read_inbox(self, name: str) -> list[dict]:
        path = self._path(name)
        if not path.exists():
            return []
        with self.lock:
            payload = self.crypto.read_json(path, [])
            if not isinstance(payload, list):
                payload = []
            self.crypto.write_json(path, [])
        out = []
        for row in payload:
            if isinstance(row, dict):
                out.append(row)
        return out

    def peek_inbox(self, name: str) -> list[dict]:
        path = self._path(name)
        if not path.exists():
            return []
        with self.lock:
            payload = self.crypto.read_json(path, [])
            if not isinstance(payload, list):
                payload = []
        return [row for row in payload if isinstance(row, dict)]

    def broadcast(self, sender: str, content: str, names: list[str]) -> str:
        count = 0
        for name in names:
            if name == sender:
                continue
            self.send(sender, name, content, "broadcast")
            count += 1
        return f"Broadcast to {count} teammates"
