# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from __future__ import annotations
import argparse
import ast
import base64
from collections import Counter, defaultdict, deque
import concurrent.futures
import csv
import difflib
import errno
import html
import hashlib
import hmac
import io
import importlib.util
import json
import math
import multiprocessing
import mimetypes
import os
import queue
import re
import selectors
import signal
import shutil
import shlex
import socket
import subprocess
import sys
import threading
import time
import traceback
import uuid
import zipfile
import zlib
import xml.etree.ElementTree as ET
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path, PurePosixPath
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qs, unquote, urlparse
from urllib.request import Request, urlopen
try:
    import yaml as _yaml
except Exception:
    _yaml = None

class EventHub:
    _MAXSIZE = 512

    def __init__(self):
        self._subs: list[queue.Queue] = []
        self._lock = threading.Lock()
        self._seq = 0

    def subscribe(self) -> queue.Queue:
        q: queue.Queue = queue.Queue(maxsize=self._MAXSIZE)
        with self._lock:
            self._subs.append(q)
        return q

    def unsubscribe(self, q: queue.Queue):
        with self._lock:
            self._subs = [x for x in self._subs if x is not q]

    def publish(self, event: dict):
        with self._lock:
            self._seq += 1
            seq = self._seq
            subs = list(self._subs)
        if isinstance(event, dict):
            event["seq"] = seq
        for q in subs:
            try:
                q.put_nowait(event)
            except queue.Full:
                # Evict oldest half then insert gap marker + new event
                evicted = 0
                half = max(1, self._MAXSIZE // 2)
                while not q.empty() and evicted < half:
                    try:
                        q.get_nowait()
                        evicted += 1
                    except queue.Empty:
                        break
                try:
                    q.put_nowait({"type": "gap", "dropped": evicted, "seq": seq})
                except queue.Full:
                    pass
                try:
                    q.put_nowait(event)
                except queue.Full:
                    pass

