# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=671 original-lines=7551-7572 hash=95e5ae12873a4310

def subprocess_text_encodings() -> list[str]:
    candidates: list[str] = ["utf-8", *_windows_subprocess_encodings()]
    try:
        candidates.append(str(locale.getpreferredencoding(False) or ""))
    except Exception:
        pass
    candidates.append("gb18030")
    out: list[str] = []
    seen: set[str] = set()
    for value in candidates:
        encoding = str(value or "").strip()
        key = encoding.casefold().replace("_", "-")
        if not encoding or key in seen:
            continue
        try:
            "".encode(encoding)
        except LookupError:
            continue
        seen.add(key)
        out.append(encoding)
    return out or ["utf-8"]

# split-source: order=672 original-lines=7573-7599 hash=6bce8faef6bf011c

def decode_subprocess_bytes(data: bytes | bytearray | str | None) -> tuple[str, dict]:
    if data is None:
        return "", {"encoding": "", "fallback": False, "replacement": False}
    if isinstance(data, str):
        return escape_invalid_utf8_text(data), {
            "encoding": "text",
            "fallback": False,
            "replacement": False,
        }
    raw = bytes(data)
    encodings = subprocess_text_encodings()
    for index, encoding in enumerate(encodings):
        try:
            return raw.decode(encoding, errors="strict"), {
                "encoding": encoding,
                "fallback": index > 0,
                "replacement": False,
            }
        except UnicodeDecodeError:
            continue
    encoding = encodings[0]
    return raw.decode(encoding, errors="replace"), {
        "encoding": encoding,
        "fallback": True,
        "replacement": True,
    }

# split-source: order=673 original-lines=7600-7622 hash=b24b8ba5b5793915

def run_subprocess_text(*popenargs, **kwargs) -> subprocess.CompletedProcess:
    """Run a captured subprocess without allowing platform decoding to fail."""
    options = dict(kwargs)
    options.pop("encoding", None)
    options.pop("errors", None)
    options.pop("universal_newlines", None)
    options["text"] = False
    try:
        completed = subprocess.run(*popenargs, **options)
    except subprocess.TimeoutExpired as exc:
        stdout, stdout_diag = decode_subprocess_bytes(getattr(exc, "stdout", None))
        stderr, stderr_diag = decode_subprocess_bytes(getattr(exc, "stderr", None))
        exc.stdout = exc.output = stdout
        exc.stderr = stderr
        exc.decoding_diagnostics = {"stdout": stdout_diag, "stderr": stderr_diag}
        raise
    stdout, stdout_diag = decode_subprocess_bytes(completed.stdout)
    stderr, stderr_diag = decode_subprocess_bytes(completed.stderr)
    completed.stdout = stdout
    completed.stderr = stderr
    completed.decoding_diagnostics = {"stdout": stdout_diag, "stderr": stderr_diag}
    return completed

# split-source: order=674 original-lines=7623-7629 hash=322031603b8faa1f


def windows_utf8_shell_command(command: object) -> str:
    text = str(command or "")
    if re.match(r"(?is)^\s*chcp\s+65001\s*>\s*nul\s*&", text):
        return text
    return f"chcp 65001>nul & {text}"

# split-source: order=675 original-lines=7630-7640 hash=48571f90d386fb9d


def shell_process_invocation(command: str, prefix: list[str] | tuple[str, ...] | None = None) -> tuple[object, bool, bool]:
    """Build one platform-correct shell invocation for foreground and background runners."""
    shell_prefix = [str(item) for item in (prefix or [])]
    windows_job = _is_windows_job_sandbox_prefix(shell_prefix)
    if shell_prefix and not windows_job:
        return [*shell_prefix, "/bin/sh", "-c", str(command or "")], False, False
    if os.name == "nt":
        return windows_utf8_shell_command(command), True, windows_job
    return str(command or ""), True, windows_job

# split-source: order=676 original-lines=7641-7652 hash=1f92ebf8c91d329f


def join_shell_task_command(command: object, args: object) -> str:
    parts = [str(command or "").strip()]
    if isinstance(args, list):
        parts.extend(str(item) for item in args)
    parts = [item for item in parts if item]
    if not parts:
        return ""
    if os.name == "nt":
        return subprocess.list2cmdline(parts)
    return shlex.join(parts)

# split-source: order=895 original-lines=21483-21842 hash=a9a553f635f6c8c1


class UserProcessManager:
    """Application-wide registry for user-owned background child processes."""

    ACTIVE_STATUSES = {"starting", "running", "stopping"}
    MAX_RECORDS = 5000
    MAX_BULK_TARGETS = 200
    _SECRET_NAME = r"(?:api[_-]?key|token|secret|password|passwd|access[_-]?key|private[_-]?key)"

    def __init__(self):
        self.lock = threading.RLock()
        self.records: dict[str, dict] = {}
        self.terminators: dict[str, object] = {}

    @staticmethod
    def _user_hash(user_id: str) -> str:
        return hashlib.sha256(str(user_id or "").encode("utf-8", errors="ignore")).hexdigest()[:16]

    @classmethod
    def _redact_text(cls, value: object, *, limit: int) -> str:
        text = str(value or "")
        text = re.sub(
            rf"(?i)(\b{cls._SECRET_NAME}\b\s*[=:]\s*)(?:\"[^\"]*\"|'[^']*'|[^\s;&|]+)",
            r"\1[REDACTED]",
            text,
        )
        text = re.sub(
            rf"(?i)(--{cls._SECRET_NAME}(?:=|\s+))(?:\"[^\"]*\"|'[^']*'|[^\s;&|]+)",
            r"\1[REDACTED]",
            text,
        )
        text = re.sub(r"(?i)(https?://[^\s/:@]+:)[^\s/@]+(@)", r"\1[REDACTED]\2", text)
        try:
            home = str(Path.home())
            if home and home != "/":
                text = text.replace(home, "~")
        except Exception:
            pass
        return trim(text, max(1, int(limit)))

    @staticmethod
    def _workspace_label(cwd: object) -> str:
        raw = str(cwd or "").strip()
        if not raw:
            return "workspace"
        try:
            return Path(raw).name or "workspace"
        except Exception:
            return "workspace"

    def _prune_locked(self) -> None:
        if len(self.records) <= self.MAX_RECORDS:
            return
        finished = sorted(
            (
                row for row in self.records.values()
                if str(row.get("status", "")) not in self.ACTIVE_STATUSES
            ),
            key=lambda row: float(row.get("finished_at", row.get("started_at", 0.0)) or 0.0),
        )
        for row in finished[: max(0, len(self.records) - self.MAX_RECORDS)]:
            process_id = str(row.get("id", "") or "")
            self.records.pop(process_id, None)
            self.terminators.pop(process_id, None)

    def register(
        self,
        *,
        process_id: str,
        task_id: str,
        owner_user_id: str,
        session_id: str,
        session_title: str,
        command: str,
        cwd: Path,
        source: str,
        started_at: float,
        timeout_seconds: int = 0,
        pid: int = 0,
        status: str = "starting",
        terminator=None,
    ) -> None:
        key = str(process_id or task_id or "").strip()
        if not key:
            raise ValueError("process_id is required")
        now = now_ts()
        with self.lock:
            existing = dict(self.records.get(key, {}))
            self.records[key] = {
                **existing,
                "id": key,
                "task_id": str(task_id or key),
                "owner_user_id": str(owner_user_id or ""),
                "user_hash": self._user_hash(owner_user_id),
                "session_id": str(session_id or ""),
                "session_title": trim(str(session_title or session_id or ""), 160),
                "command": str(command or ""),
                "cwd": str(cwd or ""),
                "workspace_label": self._workspace_label(cwd),
                "source": str(source or "background_run"),
                "status": str(status or "starting"),
                "pid": max(0, int(pid or 0)),
                "started_at": float(started_at or now),
                "updated_at": now,
                "last_activity_at": float(existing.get("last_activity_at", started_at or now) or now),
                "timeout_seconds": max(0, int(timeout_seconds or 0)),
                "output_bytes": int(existing.get("output_bytes", 0) or 0),
            }
            if callable(terminator):
                self.terminators[key] = terminator
            self._prune_locked()

    def update(self, process_id: str, **fields) -> None:
        key = str(process_id or "").strip()
        if not key:
            return
        allowed = {
            "status", "pid", "last_activity_at", "output_bytes", "output_tail",
            "exit_code", "error", "finished_at", "duration_seconds",
            "termination_actor", "termination_reason", "termination_requested_at",
        }
        clean = {name: value for name, value in fields.items() if name in allowed}
        if not clean:
            return
        with self.lock:
            row = self.records.get(key)
            if row is None:
                return
            row.update(clean)
            row["updated_at"] = now_ts()
            if str(row.get("status", "")) not in self.ACTIVE_STATUSES:
                self.terminators.pop(key, None)

    def _reconcile_locked(self) -> None:
        now = now_ts()
        for process_id, row in list(self.records.items()):
            if str(row.get("status", "")) not in self.ACTIVE_STATUSES:
                continue
            process = row.get("_process")
            if process is None:
                continue
            try:
                returncode = process.poll()
            except Exception:
                returncode = None
            if returncode is None:
                continue
            terminated = bool(row.get("termination_requested_at"))
            row.update({
                "status": "terminated" if terminated else ("completed" if int(returncode) == 0 else "error"),
                "exit_code": int(returncode),
                "finished_at": float(row.get("finished_at", now) or now),
                "updated_at": now,
            })
            self.terminators.pop(process_id, None)

    def attach_process(self, process_id: str, process: subprocess.Popen, *, terminator=None) -> None:
        key = str(process_id or "").strip()
        with self.lock:
            row = self.records.get(key)
            if row is None:
                return
            row["_process"] = process
            row["pid"] = max(0, int(getattr(process, "pid", 0) or 0))
            row["status"] = "running"
            row["updated_at"] = now_ts()
            if callable(terminator):
                self.terminators[key] = terminator

    def was_termination_requested(self, process_id: str) -> bool:
        with self.lock:
            return bool((self.records.get(str(process_id or ""), {}) or {}).get("termination_requested_at"))

    def _public(self, row: dict, *, detail: bool = False) -> dict:
        out = {
            "id": str(row.get("id", "") or ""),
            "task_id": str(row.get("task_id", "") or ""),
            "user_hash": str(row.get("user_hash", "") or ""),
            "session_id": str(row.get("session_id", "") or ""),
            "session_title": str(row.get("session_title", "") or ""),
            "pid": max(0, int(row.get("pid", 0) or 0)),
            "command": self._redact_text(row.get("command", ""), limit=260),
            "workspace": str(row.get("workspace_label", "workspace") or "workspace"),
            "source": str(row.get("source", "") or ""),
            "status": str(row.get("status", "") or "unknown"),
            "started_at": float(row.get("started_at", 0.0) or 0.0),
            "updated_at": float(row.get("updated_at", 0.0) or 0.0),
            "last_activity_at": float(row.get("last_activity_at", 0.0) or 0.0),
            "finished_at": float(row.get("finished_at", 0.0) or 0.0),
            "duration_seconds": round(float(row.get("duration_seconds", 0.0) or 0.0), 3),
            "timeout_seconds": max(0, int(row.get("timeout_seconds", 0) or 0)),
            "output_bytes": max(0, int(row.get("output_bytes", 0) or 0)),
            "exit_code": row.get("exit_code"),
            "error": self._redact_text(row.get("error", ""), limit=500),
            "termination_actor": str(row.get("termination_actor", "") or ""),
            "termination_reason": trim(str(row.get("termination_reason", "") or ""), 200),
            "termination_requested_at": float(row.get("termination_requested_at", 0.0) or 0.0),
            "can_stop": str(row.get("status", "")) in {"starting", "running"},
        }
        if detail:
            out["output_tail"] = self._redact_text(row.get("output_tail", ""), limit=4000)
        return out

    def list_processes(
        self,
        *,
        owner_user_id: str | None = None,
        user_hash: str = "",
        session_id: str = "",
        status: str = "",
        query: str = "",
        limit: int = 100,
        offset: int = 0,
    ) -> dict:
        limit = max(1, min(500, int(limit or 100)))
        offset = max(0, int(offset or 0))
        wanted_status = str(status or "").strip().lower()
        wanted_hash = str(user_hash or "").strip().lower()
        wanted_session = str(session_id or "").strip()
        needle = str(query or "").strip().lower()
        with self.lock:
            self._reconcile_locked()
            rows = []
            for row in self.records.values():
                if owner_user_id is not None and str(row.get("owner_user_id", "")) != str(owner_user_id):
                    continue
                if wanted_hash and str(row.get("user_hash", "")).lower() != wanted_hash:
                    continue
                if wanted_session and str(row.get("session_id", "")) != wanted_session:
                    continue
                if wanted_status and str(row.get("status", "")).lower() != wanted_status:
                    continue
                if needle:
                    haystack = " ".join((
                        str(row.get("id", "")), str(row.get("session_id", "")),
                        str(row.get("session_title", "")), str(row.get("command", "")),
                        str(row.get("source", "")), str(row.get("status", "")),
                    )).lower()
                    if needle not in haystack:
                        continue
                rows.append(dict(row))
            rows.sort(key=lambda row: float(row.get("started_at", 0.0) or 0.0), reverse=True)
            total = len(rows)
            page = rows[offset: offset + limit]
            counts: dict[str, int] = {}
            for row in rows:
                state = str(row.get("status", "unknown") or "unknown")
                counts[state] = counts.get(state, 0) + 1
        return {
            "processes": [self._public(row) for row in page],
            "total": total,
            "offset": offset,
            "limit": limit,
            "has_more": offset + len(page) < total,
            "counts": counts,
        }

    def get_process(self, process_id: str, *, owner_user_id: str | None = None) -> dict:
        key = str(process_id or "").strip()
        with self.lock:
            self._reconcile_locked()
            row = self.records.get(key)
            if row is None or (owner_user_id is not None and str(row.get("owner_user_id", "")) != str(owner_user_id)):
                raise ProcessManagerError("process not found", status=404, code="process_not_found")
            public = self._public(dict(row), detail=True)
        return public

    def stop_process(
        self,
        process_id: str,
        *,
        owner_user_id: str | None = None,
        actor: str,
        reason: str = "requested",
    ) -> dict:
        key = str(process_id or "").strip()
        with self.lock:
            self._reconcile_locked()
            row = self.records.get(key)
            if row is None or (owner_user_id is not None and str(row.get("owner_user_id", "")) != str(owner_user_id)):
                raise ProcessManagerError("process not found", status=404, code="process_not_found")
            if str(row.get("status", "")) not in {"starting", "running"}:
                raise ProcessManagerError("process is not running", status=409, code="process_not_running")
            terminator = self.terminators.get(key)
            if not callable(terminator):
                raise ProcessManagerError("process cannot be stopped", status=409, code="process_not_stoppable")
            now = now_ts()
            row.update({
                "status": "stopping",
                "termination_actor": trim(str(actor or "system"), 120),
                "termination_reason": trim(str(reason or "requested"), 200),
                "termination_requested_at": now,
                "updated_at": now,
            })
        try:
            terminator()
        except Exception as exc:
            with self.lock:
                current = self.records.get(key)
                if current is not None:
                    current.update({"status": "error", "error": trim(str(exc), 500), "updated_at": now_ts()})
            raise ProcessManagerError("failed to stop process", status=500, code="process_stop_failed") from exc
        return {"ok": True, "process": self.get_process(key, owner_user_id=owner_user_id)}

    def bulk_stop(
        self,
        *,
        actor: str,
        ids: list[str] | None = None,
        user_hash: str = "",
        session_id: str = "",
        reason: str = "admin bulk stop",
    ) -> dict:
        requested = list(dict.fromkeys(str(value or "").strip() for value in (ids or []) if str(value or "").strip()))
        wanted_hash = str(user_hash or "").strip().lower()
        wanted_session = str(session_id or "").strip()
        if not requested and not wanted_hash and not wanted_session:
            raise ProcessManagerError("bulk stop requires process ids, a user hash, or a session id", status=400, code="bulk_filter_required")
        with self.lock:
            self._reconcile_locked()
            if requested:
                targets = [key for key in requested if key in self.records]
            else:
                targets = [
                    key for key, row in self.records.items()
                    if (not wanted_hash or str(row.get("user_hash", "")).lower() == wanted_hash)
                    and (not wanted_session or str(row.get("session_id", "")) == wanted_session)
                ]
            targets = [key for key in targets if str(self.records[key].get("status", "")) in {"starting", "running"}]
        if len(targets) > self.MAX_BULK_TARGETS:
            raise ProcessManagerError(
                f"bulk stop matches {len(targets)} processes; maximum is {self.MAX_BULK_TARGETS}",
                status=413,
                code="bulk_target_limit",
            )
        stopped: list[str] = []
        failed: list[dict] = []
        for key in targets:
            try:
                self.stop_process(key, actor=actor, reason=reason)
                stopped.append(key)
            except ProcessManagerError as exc:
                failed.append({"id": key, "code": exc.code, "error": str(exc)})
        return {"ok": not failed, "matched": len(targets), "stopped": stopped, "failed": failed}

    def stop_all(self, *, actor: str = "system", reason: str = "service shutdown") -> int:
        with self.lock:
            targets = [
                key for key, row in self.records.items()
                if str(row.get("status", "")) in {"starting", "running"} and callable(self.terminators.get(key))
            ]
        stopped = 0
        for key in targets[: self.MAX_BULK_TARGETS]:
            try:
                self.stop_process(key, actor=actor, reason=reason)
                stopped += 1
            except ProcessManagerError:
                pass
        return stopped
