# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=768 original-lines=10494-10527 hash=494ce756bc5b35d8


def _ask_user_option_rows(raw_options: object, *, limit: int = 8) -> list[object]:
    """Keep ask_user choices structured without breaking legacy string options."""
    source = raw_options
    if isinstance(source, str):
        candidate = source.strip()
        if candidate.startswith(("[", "{")):
            try:
                source = json.loads(candidate)
            except Exception:
                source = [source]
        else:
            source = [source] if candidate else []
    if isinstance(source, dict):
        source = [source]
    if not isinstance(source, (list, tuple)):
        return []
    rows: list[object] = []
    for item in source:
        if isinstance(item, dict):
            label = trim(str(item.get("label", item.get("text", item.get("name", ""))) or "").strip(), 400)
            value = trim(str(item.get("value", item.get("id", label)) or label).strip(), 400)
            description = trim(str(item.get("description", item.get("detail", "")) or "").strip(), 800)
            if not label and not value:
                continue
            rows.append({"label": label or value, "value": value or label, **({"description": description} if description else {})})
        else:
            value = trim(str(item or "").strip(), 400)
            if value:
                rows.append(value)
        if len(rows) >= max(1, int(limit or 8)):
            break
    return rows

# split-source: order=769 original-lines=10528-10533 hash=4bfe2fe5ea6ce1a8


def _ask_user_option_value(option: object) -> str:
    if isinstance(option, dict):
        return trim(str(option.get("value", option.get("id", option.get("label", ""))) or "").strip(), 400)
    return trim(str(option or "").strip(), 400)

# split-source: order=840 original-lines=20488-20501 hash=f19c222e839c27ec

def tool_def(name: str, description: str, properties: dict, required: list[str] | None = None) -> dict:
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {
                "type": "object",
                "properties": properties,
                "required": required or [],
            },
        },
    }

# split-source: order=841 original-lines=20502-20986 hash=7e04884c2080e744

TOOLS = [
    tool_def("bash", "Run a shell command.", {"command": {"type": "string"}}, ["command"]),
    tool_def(
        "read_file",
        (
            "Read files or directories with structure-aware modes. "
            "Examples: large.py + func_42 -> mode='symbol' target='func_42'; "
            "app.py line 240 -> mode='window' line=240 context=5; "
            "run.txt E123 -> mode='search' query='E123'. "
            "Use mode='auto' by default; use mode='symbol', 'search', or 'window' for focused reads, "
            "and mode='full' when complete content is explicitly needed. Successful reads are remembered in "
            "the tool-memory registry; use that evidence instead of repeating identical broad reads."
        ),
        {
            "path": {"type": "string"},
            "mode": {
                "type": "string",
                "enum": ["auto", "full", "overview", "window", "symbol", "search", "directory"],
                "description": "Reading strategy. Use symbol with target for a function/class; search with query for known text/errors; window with line/context for a line range. Avoid full for large logs when a query is known.",
            },
            "target": {"type": "string", "description": "Symbol name for mode='symbol', for example 'ClassName.method' or 'func_42'."},
            "query": {"type": "string", "description": "Search text or regex for mode='search'; can also be used when target is unknown."},
            "line": {"type": "integer", "description": "1-based center line for mode='window'."},
            "context": {"type": "integer", "description": "Number of surrounding lines for mode='window' or mode='search'."},
            "regex": {"type": "boolean", "description": "Treat query as a regular expression in mode='search'."},
            "max_chars": {"type": "integer", "description": "Maximum characters to return for broad reads; use only when wider context is needed."},
            "limit": {"type": "integer", "description": "Legacy line count for compatibility; prefer mode/context for new calls."},
            "offset": {"type": "integer", "description": "0-based character offset for mode='full'; legacy 0-based line/entry offset for mode='window' or mode='directory'. Prefer mode='window' with line/context for line-oriented reads."},
        },
        ["path"],
    ),
    tool_def("write_file", "Write file content.", {"path": {"type": "string"}, "content": {"type": "string"}}, ["path", "content"]),
    tool_def("edit_file", "Edit a file by replacing first match.", {"path": {"type": "string"}, "old_text": {"type": "string"}, "new_text": {"type": "string"}}, ["path", "old_text", "new_text"]),
    tool_def(
        "TodoWrite",
        (
            "Update current todos. update_mode='status_update' is merge-only: omitted unfinished rows are preserved, "
            "so a partial progress payload can never shorten the task tree. In approved plan mode, use it for status-only progress. "
            "When new current-step tool evidence or reviewer findings prove the open subplan is no longer suitable, "
            "use update_mode='revise_open' with a concrete revision_reason and revision_evidence references; the runtime performs an atomic LLM audit "
            "against the authoritative goal, original Todo baseline, completed evidence, and remaining requirement coverage before replacing open rows. "
            "Use 'rework_completed' only when failure/reviewer evidence requires reopening completed work. "
            "Preferred items are objects with content/status/owner/parent_step_id/subtask_id."
        ),
        {
            "items": {"type": "array", "items": {}},
            # Provider-compatible aliases. Runtime validation intentionally
            # treats these as equivalent to `items` so a compact/resume model
            # does not get trapped by the historical required-key spelling.
            "todos": {"type": "array", "items": {}},
            "todo_items": {"type": "array", "items": {}},
            "subtasks": {"type": "array", "items": {}},
            "rows": {"type": "array", "items": {}},
            "updates": {"type": "array", "items": {}},
            "tasks": {"type": "array", "items": {}},
            "data": {},
            "content": {"type": "string"},
            "text": {"type": "string"},
            "title": {"type": "string"},
            "task": {"type": "string"},
            "description": {"type": "string"},
            "label": {"type": "string"},
            "resume": {"type": "boolean"},
            "continue": {"type": "boolean"},
            "resume_existing": {"type": "boolean"},
            "in_progress_index": {"type": "integer"},
            "update_mode": {
                "type": "string",
                "enum": ["status_update", "revise_open", "rework_completed"],
                "description": "status_update merges statuses and preserves omitted rows; revise_open proposes a complete open snapshot and requires an LLM coverage/risk audit; rework_completed additionally proposes reopening completed work.",
            },
            "revision_reason": {"type": "string", "description": "Concrete new finding that justifies a structural rolling-plan revision."},
            "revision_evidence": {},
            "evidence": {},
        },
        [],
    ),
    tool_def(
        "TodoWriteRescue",
        "Fallback todo writer using the same protected merge/replan transaction as TodoWrite. Omitted rows are preserved unless an explicit revise_open passes LLM review. Preferred format: objects with content/status/owner/parent_step_id. String fallback should use only '[ ] task', '[>] task', or '[x] task'.",
        {
            "items": {"type": "array", "items": {}},
            "todos": {"type": "array", "items": {}},
            "todo_items": {"type": "array", "items": {}},
            "subtasks": {"type": "array", "items": {}},
            "rows": {"type": "array", "items": {}},
            "updates": {"type": "array", "items": {}},
            "tasks": {"type": "array", "items": {}},
            "data": {},
            "content": {"type": "string"},
            "text": {"type": "string"},
            "title": {"type": "string"},
            "task": {"type": "string"},
            "description": {"type": "string"},
            "label": {"type": "string"},
            "resume": {"type": "boolean"},
            "continue": {"type": "boolean"},
            "resume_existing": {"type": "boolean"},
            "in_progress_index": {"type": "integer"},
            "update_mode": {"type": "string", "enum": ["status_update", "revise_open", "rework_completed"]},
            "revision_reason": {"type": "string"},
            "revision_evidence": {},
            "evidence": {},
        },
        [],
    ),
    tool_def(
        "TodoWriteResume",
        (
            "Resume and reconcile the existing todo graph after compaction, a handoff, or a partial tool call. "
            "This is an alias of TodoWrite with elastic item/status recognition; it preserves completed rows and "
            "updates only the active owner/current plan step. Items may be supplied as items, todos, todo_items, "
            "subtasks, rows, or a structured text payload."
        ),
        {
            "items": {"type": "array", "items": {}},
            "todos": {"type": "array", "items": {}},
            "todo_items": {"type": "array", "items": {}},
            "subtasks": {"type": "array", "items": {}},
            "rows": {"type": "array", "items": {}},
            "updates": {"type": "array", "items": {}},
            "tasks": {"type": "array", "items": {}},
            "data": {},
            "content": {"type": "string"},
            "text": {"type": "string"},
            "title": {"type": "string"},
            "task": {"type": "string"},
            "description": {"type": "string"},
            "label": {"type": "string"},
            "resume": {"type": "boolean"},
            "continue": {"type": "boolean"},
            "resume_existing": {"type": "boolean"},
            "in_progress_index": {"type": "integer"},
            "update_mode": {"type": "string"},
            "mode": {"type": "string"},
            "operation": {"type": "string"},
            "reason": {"type": "string"},
            # Keep this unconstrained: providers differ in whether they accept
            # `oneOf`, while the runtime already normalizes strings and arrays.
            "evidence": {},
            "revision_reason": {"type": "string"},
            "revision_evidence": {"type": "array", "items": {"type": "string"}},
        },
        [],
    ),
    tool_def(
        "finish_task",
        "Request overall user task completion. Not for subtasks or individual plan steps; completion gates decide whether the run can stop.",
        {"summary": {"type": "string"}},
    ),
    tool_def(
        "finish_current_task",
        "Minimal overall-run finish request. Do not use for subtasks or plan steps; use TodoWrite for those.",
        {"summary": {"type": "string"}},
    ),
    tool_def(
        "mark_done",
        "Alias of finish_current_task; requests overall-run completion only.",
        {"summary": {"type": "string"}},
    ),
    tool_def(
        "ask_user",
        "Pause the run and ask the user a question when you need a decision or clarification you cannot make yourself (e.g. choosing among options, confirming a direction, missing info). The run STOPS after this call and resumes only when the user replies. Do NOT use this to report progress or to finish — use finish_task for completion. Provide a clear question; optionally provide `options` (a short list of choices to present as buttons) and set `allow_free_text` false to require picking an option.",
        {
            "question": {"type": "string"},
            "options": {"type": "array", "items": {"type": "string"}},
            "allow_free_text": {"type": "boolean"},
        },
        ["question"],
    ),
    tool_def("task", "Spawn a subagent for isolated work.", {"prompt": {"type": "string"}, "agent_type": {"type": "string"}}, ["prompt"]),
    tool_def("list_skills", "List skill names.", {}),
    tool_def("load_skill", "Load a skill by name.", {"name": {"type": "string"}}, ["name"]),
    tool_def("list_skill_providers", "List discovered skill providers.", {}),
    tool_def("list_skill_protocols", "List supported skill backend protocols.", {}),
    tool_def(
        "write_skill",
        "Write a SKILL.md into global ./skills (cross-session) and reload skill index.",
        {"path": {"type": "string"}, "content": {"type": "string"}, "overwrite": {"type": "boolean"}},
        ["path", "content"],
    ),
    tool_def("scan_skills", "Force reload skills from ./skills and return summary.", {}),
    tool_def(
        "compress",
        "Compress conversation context and optionally pin/drop remembered tool evidence.",
        {
            "keep_tool_memory": {
                "type": "array",
                "items": {},
                "description": "Tool-memory ids, paths, commands, signatures, or objects to keep/pin across compact.",
            },
            "drop_tool_memory": {
                "type": "array",
                "items": {},
                "description": "Tool-memory ids, paths, commands, signatures, or objects to remove from future prompt summaries.",
            },
            "keep_read_context": {
                "type": "array",
                "items": {},
                "description": "Backward-compatible alias for read_file tool-memory entries to keep/pin across compact.",
            },
            "drop_read_context": {
                "type": "array",
                "items": {},
                "description": "Backward-compatible alias for read_file tool-memory entries to remove from future prompt summaries.",
            },
        },
    ),
    tool_def(
        "tool_memory",
        (
            "Inspect remembered tool evidence from the current session before repeating read_file/bash/query/edit calls. "
            "Use mode='summary' for the active map, mode='search' with query/path/command terms, "
            "or mode='detail' with id to load an entry and optional cached preview."
        ),
        {
            "mode": {"type": "string", "enum": ["summary", "search", "recent", "detail"]},
            "query": {"type": "string"},
            "id": {"type": "string"},
            "tool": {"type": "string"},
            "role": {"type": "string"},
            "status": {"type": "string"},
            "limit": {"type": "integer"},
            "max_chars": {"type": "integer"},
            "include_cached": {"type": "boolean"},
        },
    ),
        tool_def(
            "context_recall",
            (
                "Recall archived compacted context with focused modes. "
                "Use this tool, not read_from_blackboard, when the user says archived context, compacted context, previous segment, or context segment. "
                "Use mode='summary' for a map, 'search' with query/tool_name/role for evidence, "
                "or 'window' with around_index/context for nearby messages."
            ),
        {
            "mode": {"type": "string", "enum": ["summary", "search", "recent", "window", "detail"]},
            "segment_id": {"type": "string"},
            "query": {"type": "string"},
            "role": {"type": "string"},
            "tool_name": {"type": "string"},
            "around_index": {"type": "integer"},
            "context": {"type": "integer"},
            "max_chars": {"type": "integer"},
            "recent_segments": {"type": "integer"},
            "max_messages": {"type": "integer"},
            "offset": {"type": "integer", "description": "Legacy offset for compatibility; prefer query or around_index/context."},
            "include_tools": {"type": "boolean"},
        },
    ),
    tool_def(
        "query_code_library",
        "Query the independent code library for repo/file/symbol references before implementing or reviewing code.",
        {
            "query": {"type": "string"},
            "top_k": {"type": "integer"},
            "route": {"type": "string", "enum": ["auto", "workflow", "wiki", "raw", "fast", "global", "hybrid"]},
            "budget": {"type": "string", "enum": ["tight", "standard", "deep"]},
            "language": {"type": "string"},
            "embed_model": {"type": "string"},
            "embedding_mode": {"type": "string", "enum": ["sparse", "hybrid", "dense", "off"]},
        },
        ["query"],
    ),
    tool_def(
        "query_knowledge_library",
        (
            "Query the RAG knowledge library for grounded document references and background knowledge. "
            "Call this BEFORE answering questions that require domain expertise, factual grounding, "
            "or synthesis from imported documents. "
            "Pass an empty query to check library status only."
        ),
        {
            "query": {"type": "string"},
            "top_k": {"type": "integer"},
            "route": {"type": "string", "enum": ["auto", "wiki", "raw", "fast", "global", "hybrid"]},
            "budget": {"type": "string", "enum": ["tight", "standard", "deep"]},
            "category": {"type": "string"},
            "kind": {"type": "string"},
            "embed_model": {"type": "string"},
            "embedding_mode": {"type": "string", "enum": ["sparse", "hybrid", "dense", "off"]},
        },
    ),
    tool_def(
        "rag_remember",
        (
            "Save a useful reference, finding, or snippet into the RAG knowledge library so it "
            "is retrievable in this and future sessions. Use this when you discover a durable, "
            "reusable piece of knowledge — an authoritative explanation, a resolved gotcha, a "
            "well-structured summary, a canonical code/config example, or a vetted external "
            "reference. Do NOT use it for transient chatter or unverified guesses. The text is "
            "parsed, chunked, and indexed exactly like an imported document; duplicates (same "
            "content) are de-duplicated automatically."
        ),
        {
            "text": {"type": "string"},
            "title": {"type": "string"},
            "tags": {"type": "array", "items": {"type": "string"}},
            "category": {"type": "string"},
            "source": {"type": "string"},
        },
        ["text"],
    ),
    tool_def(
        "agent_web_search",
        (
            "Autonomous bounded web research without third-party search APIs. "
            "Use explicit seed_urls/domains when possible; otherwise it derives official/source domains from the query, "
            "probes roots, robots, sitemaps, RSS/Atom, and bounded same-domain HTML links, then stores fetched pages in a local SQLite/FTS index. "
            "Use this for current open-web facts or source discovery; cite only returned fetched URLs. "
            "For relative dates or time-sensitive queries, ground query terms and freshness_days against the injected runtime temporal/local context; do not use stale years from model memory. "
            "Safety: http/https only, private/local networks blocked by default, robots obeyed, strict page/depth budgets."
        ),
        {
            "mode": {"type": "string", "enum": ["search", "discover", "deepen", "follow", "fetch", "index_status", "site_probe"]},
            "query": {"type": "string"},
            "url": {"type": "string"},
            "seed_urls": {"type": "array", "items": {"type": "string"}},
            "domains": {"type": "array", "items": {"type": "string"}},
            "max_results": {"type": "integer"},
            "max_pages": {"type": "integer"},
            "depth": {"type": "integer"},
            "freshness_days": {"type": "integer"},
            "allow_html_discovery": {"type": "boolean"},
            "max_chars": {"type": "integer"},
            "obey_robots": {"type": "boolean"},
        },
    ),
    tool_def(
        "generate_media",
        "Generate image/audio/video using active model media endpoints.",
        {
            "media_type": {"type": "string", "enum": ["image", "audio", "video"]},
            "prompt": {"type": "string"},
            "size": {"type": "string"},
            "duration": {"type": "integer"},
            "format": {"type": "string"},
            "filename": {"type": "string"},
            "extra": {"type": "object"},
        },
        ["media_type", "prompt"],
    ),
    tool_def("background_run", "Run command in background.", {"command": {"type": "string"}, "timeout": {"type": "integer"}}, ["command"]),
        tool_def(
            "check_background",
            (
                "Inspect background tasks with summary/search/detail/tail modes. "
                "If the user names an error token, command text, or output text such as E123 or pytest, use mode='search' with query. "
                "Use tail only for recent jobs when no query is known."
            ),
        {
            "task_id": {"type": "string"},
            "mode": {"type": "string", "enum": ["summary", "search", "detail", "tail"]},
            "query": {"type": "string"},
            "status": {"type": "string"},
            "limit": {"type": "integer"},
            "max_chars": {"type": "integer"},
        },
    ),
    tool_def("task_create", "Create task.", {"subject": {"type": "string"}, "description": {"type": "string"}}, ["subject"]),
    tool_def("task_get", "Get task.", {"task_id": {"type": "integer"}}, ["task_id"]),
    tool_def("task_update", "Update task.", {"task_id": {"type": "integer"}, "status": {"type": "string"}, "add_blocked_by": {"type": "array", "items": {"type": "integer"}}, "add_blocks": {"type": "array", "items": {"type": "integer"}}}, ["task_id"]),
    tool_def(
        "task_list",
        "List tasks with optional status/owner/query filters and summary/detail modes.",
        {
            "mode": {"type": "string", "enum": ["summary", "search", "detail", "recent"]},
            "query": {"type": "string"},
            "status": {"type": "string"},
            "owner": {"type": "string"},
            "limit": {"type": "integer"},
            "max_chars": {"type": "integer"},
        },
    ),
    tool_def("claim_task", "Claim task.", {"task_id": {"type": "integer"}}, ["task_id"]),
    tool_def("spawn_teammate", "Spawn teammate thread.", {"name": {"type": "string"}, "role": {"type": "string"}, "prompt": {"type": "string"}}, ["name", "role", "prompt"]),
    tool_def("list_teammates", "List teammates.", {}),
    tool_def(
        "ask_colleague",
        "Hand off to explorer/developer/reviewer via the internal agent bus. The recipient automatically receives a mainline anchor (goal+focus) and an evidence manifest of blackboard POINTERS to the work you produced this step — so keep `content` SHORT (your intent/ask, not a copy of your code or logs). To point at specific blackboard evidence, list `refs` (file paths you changed, or short search phrases); the bus resolves them into pointers the recipient pulls on demand via read_from_blackboard. Do not paste large file/log content into `content`.",
        {
            "to": {"type": "string", "enum": ["explorer", "developer", "reviewer"]},
            "intent": {"type": "string"},
            "content": {"type": "string"},
            "refs": {"type": "array", "items": {"type": "string"}},
        },
        ["to", "intent", "content"],
    ),
        tool_def(
            "read_from_blackboard",
            (
                "Read shared multi-agent blackboard state with summary/search/recent/window/detail modes. "
                "Use this for memory, research_notes, execution_logs, review_feedback, code_artifacts, and status; "
                "use context_recall instead for archived or compacted conversation context."
            ),
        {
            "section": {
                "type": "string",
                "enum": [
                    "all",
                    "original_goal",
                    "research_notes",
                    "code_artifacts",
                    "execution_logs",
                    "review_feedback",
                    "conversation_history",
                    "memory",
                    "status",
                ],
            },
            "mode": {"type": "string", "enum": ["summary", "search", "recent", "window", "detail"]},
            "query": {"type": "string"},
            "actor": {"type": "string"},
            "status": {"type": "string"},
            "around_index": {"type": "integer"},
            "context": {"type": "integer"},
            "max_chars": {"type": "integer"},
            "limit": {"type": "integer"},
        },
    ),
    tool_def(
        "write_to_blackboard",
        "Write a concise update into shared blackboard.",
        {
            "section": {
                "type": "string",
                "enum": [
                    "research_notes",
                    "execution_logs",
                    "review_feedback",
                    "conversation_history",
                    "status",
                    "plan_findings",
                    "plan_proposal",
                    "plan_steps",
                    "plan_risks",
                    "skill_analysis",
                ],
            },
            "content": {"type": "string"},
            "status": {"type": "string"},
        },
        ["section", "content"],
    ),
    tool_def("send_message", "Send message.", {"to": {"type": "string"}, "content": {"type": "string"}, "msg_type": {"type": "string"}}, ["to", "content"]),
    tool_def(
        "read_inbox",
        "Read lead inbox. Use mode='peek' to inspect without draining, mode='search' to find messages, or mode='drain' to consume them.",
        {
            "mode": {"type": "string", "enum": ["peek", "drain", "search", "summary"]},
            "query": {"type": "string"},
            "from": {"type": "string"},
            "type": {"type": "string"},
            "limit": {"type": "integer"},
            "max_chars": {"type": "integer"},
        },
    ),
    tool_def("broadcast", "Broadcast to teammates.", {"content": {"type": "string"}}, ["content"]),
    tool_def("shutdown_request", "Request teammate shutdown.", {"teammate": {"type": "string"}}, ["teammate"]),
    tool_def("plan_approval", "Respond to plan approval request.", {"request_id": {"type": "string"}, "approve": {"type": "boolean"}, "feedback": {"type": "string"}}, ["request_id", "approve"]),
    tool_def("worktree_create", "Create git worktree.", {"name": {"type": "string"}, "task_id": {"type": "integer"}, "base_ref": {"type": "string"}}, ["name"]),
    tool_def("worktree_list", "List worktrees.", {}),
    tool_def("worktree_status", "Get worktree status.", {"name": {"type": "string"}}, ["name"]),
    tool_def("worktree_run", "Run command in worktree.", {"name": {"type": "string"}, "command": {"type": "string"}}, ["name", "command"]),
    tool_def("worktree_keep", "Mark worktree kept.", {"name": {"type": "string"}}, ["name"]),
    tool_def("worktree_remove", "Remove worktree.", {"name": {"type": "string"}, "force": {"type": "boolean"}, "complete_task": {"type": "boolean"}}, ["name"]),
        tool_def(
            "worktree_events",
            (
                "Read worktree lifecycle events with summary/search/detail modes. "
                "For a worktree name like alpha, set worktree='alpha'; do not put worktree names in event. "
                "For known failure text use mode='search' and query='failed' or the exact error; event is for lifecycle names like worktree.remove.failed."
            ),
        {
            "mode": {"type": "string", "enum": ["summary", "search", "recent", "detail"]},
            "query": {"type": "string"},
            "event": {"type": "string"},
            "worktree": {"type": "string"},
            "task_id": {"type": "integer"},
            "limit": {"type": "integer"},
            "max_chars": {"type": "integer"},
        },
    ),
]

# split-source: order=842 original-lines=20987-20988 hash=3ee29b226eaf3576

TOOL_REQUIRED_ARGS: dict[str, list[str]] = {}

# split-source: order=843 original-lines=20989-20989 hash=08ea091c248842a3
TOOL_SPEC_BY_NAME: dict[str, dict] = {}

# split-source: order=844 original-lines=20990-20999 hash=5b49546953f9369c
for _tool in TOOLS:
    try:
        _fn = _tool.get("function", {})
        _name = str(_fn.get("name", "") or "")
        _required = _fn.get("parameters", {}).get("required", [])
        if _name:
            TOOL_SPEC_BY_NAME[_name] = _tool
            TOOL_REQUIRED_ARGS[_name] = [str(x) for x in (_required if isinstance(_required, list) else [])]
    except Exception:
        continue

# split-source: order=845 original-lines=21000-21001 hash=bfed07d2aedc6126

TOOL_NAME_FUZZY_MAP: dict[str, str] = {}

# split-source: order=846 original-lines=21002-21005 hash=61dd6436d3455b98
for _name in TOOL_SPEC_BY_NAME.keys():
    _key = re.sub(r"[^a-z0-9]+", "", str(_name or "").lower())
    if _key and _key not in TOOL_NAME_FUZZY_MAP:
        TOOL_NAME_FUZZY_MAP[_key] = str(_name)

# split-source: order=847 original-lines=21006-21023 hash=8c7992dc17a67107

for _alias, _target in {
    "writefile": "write_file",
    "readfile": "read_file",
    "editfile": "edit_file",
    "finishcurrenttask": "finish_current_task",
    "finishtask": "finish_task",
    "markdone": "mark_done",
    # Todo protocol aliases seen in older providers and compact-resume traces.
    # They intentionally collapse to the same canonical dispatcher so a resume
    # call cannot create a second, disconnected todo graph.
    "todowrite": "TodoWrite",
    "todowriteresume": "TodoWrite",
    "todowriteresumeexisting": "TodoWrite",
    "todoresume": "TodoWrite",
    "resumetodos": "TodoWrite",
}.items():
    TOOL_NAME_FUZZY_MAP[_alias] = _target

# split-source: order=848 original-lines=21024-21040 hash=a168e414b363725e


def is_todo_resume_tool_name(raw: object) -> bool:
    """Return whether a provider tool name carries resume semantics.

    Resume aliases intentionally share TodoWrite's canonical state machine, but
    the alias itself still conveys an operation when no payload is present.
    Keeping this tiny bit of provenance avoids losing that meaning during
    canonicalization.
    """
    key = re.sub(r"[^a-z0-9]+", "", str(raw or "").strip().lower())
    return key in {
        "todowriteresume",
        "todowriteresumeexisting",
        "todoresume",
        "resumetodos",
    }

# split-source: order=849 original-lines=21041-21059 hash=b3e6ffc2768f20fa


def canonicalize_tool_name(raw: object) -> str:
    name = str(raw or "").strip()
    if not name:
        return ""
    lowered = name.lower()
    key = re.sub(r"[^a-z0-9]+", "", lowered)
    # Check aliases before the exact-name path.  ``TodoWriteResume`` is exposed
    # as a compatibility schema, but must execute through TodoWrite's canonical
    # reconciliation logic rather than a separate state writer.
    mapped = TOOL_NAME_FUZZY_MAP.get(key, "") if key else ""
    if mapped:
        return mapped
    if name in TOOL_SPEC_BY_NAME:
        return name
    if lowered in TOOL_SPEC_BY_NAME:
        return lowered
    return mapped or name

# split-source: order=850 original-lines=21060-21075 hash=b445806005f59898


def filter_tool_specs_for_runtime(tools: list[dict] | None, *, web_search_enabled: bool = DEFAULT_WEB_SEARCH_ENABLED) -> list[dict]:
    src = tools if isinstance(tools, list) else []
    out: list[dict] = []
    for tool in src:
        fn = tool.get("function", {}) if isinstance(tool, dict) else {}
        name = canonicalize_tool_name(fn.get("name", ""))
        # Global skills are executable policy. Ordinary sessions may inspect them,
        # but mutation is restricted to the authenticated admin/Skills Studio path.
        if name == "write_skill":
            continue
        if name == "agent_web_search" and not bool(web_search_enabled):
            continue
        out.append(tool)
    return out

# split-source: order=851 original-lines=21076-21086 hash=9ed4253b5af25719


# Fix F: orchestration / worktree / teammate-management tools a sync-mode developer
# never calls — dropped from the developer tool bundle to cut ~1k tokens of unused
# JSON schema per developer turn. Edit this set to tune what the developer can see.
DEVELOPER_TOOL_DROP: set[str] = {
    "worktree_create", "worktree_events", "worktree_keep", "worktree_list",
    "worktree_remove", "worktree_run", "worktree_status",
    "spawn_teammate", "broadcast", "send_message", "list_teammates",
    "shutdown_request", "plan_approval", "scan_skills", "write_skill",
}

# split-source: order=852 original-lines=21087-21147 hash=6d3b7a2b319abd41

AGENT_TOOL_ALLOWLIST: dict[str, set[str]] = {
    "explorer": {
        "bash",
        "read_file",
        "TodoWrite",
        "TodoWriteRescue",
        "ask_user",
        "list_skills",
        "load_skill",
        "list_skill_providers",
        "list_skill_protocols",
        "scan_skills",
        "tool_memory",
        "context_recall",
        "task_get",
        "task_list",
        "check_background",
        "read_inbox",
        "ask_colleague",
        "read_from_blackboard",
        "write_to_blackboard",
        "compress",
        "query_code_library",
        "query_knowledge_library",
        "rag_remember",
        "agent_web_search",
    },
    "developer": {
        str(name)
        for name in TOOL_SPEC_BY_NAME.keys()
        # Fix F: a sync-mode developer never drives these orchestration / worktree /
        # teammate-management tools; sending their full schemas (~1k tokens) every
        # call was pure waste. Dropped from the developer bundle (still available to
        # whatever role/path legitimately needs them). Tune via DEVELOPER_TOOL_DROP.
        if str(name) not in DEVELOPER_TOOL_DROP
    },
    "reviewer": {
        "bash",
        "read_file",
        "TodoWrite",
        "TodoWriteRescue",
        "ask_user",
        "finish_task",
        "finish_current_task",
        "mark_done",
        "tool_memory",
        "context_recall",
        "task_get",
        "task_list",
        "check_background",
        "ask_colleague",
        "read_from_blackboard",
        "write_to_blackboard",
        "compress",
        "query_code_library",
        "query_knowledge_library",
        "rag_remember",
        "agent_web_search",
    },
}
