# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=122 original-lines=3822-3822 hash=1193ac432052a5ff
DEFAULT_OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")

# split-source: order=123 original-lines=3823-3823 hash=e498053827490a72
DEFAULT_OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:7b")

# split-source: order=875 original-lines=12536-12545 hash=9a445aba4f015d9d

OPENAI_COMPAT_PROVIDER_NAMES = {
    "openai_compat",
    "siliconflow",
    "vllm",
    "lmstudio",
    "glm",
    "kimi",
    "openrouter",
}

# split-source: order=876 original-lines=12546-12547 hash=17e3a31f65cff18b

OPENAI_LIKE_PROVIDER_NAMES = OPENAI_COMPAT_PROVIDER_NAMES | {"custom_http"}

# split-source: order=879 original-lines=12554-12565 hash=d6ecf69b7361bfa0

# ── Effort / reasoning-budget model ────────────────────────────────────
# A single provider-neutral "effort" axis that maps onto each provider's
# native reasoning controls:
#   - Anthropic (Claude)  -> extended thinking: {"type":"enabled","budget_tokens":N}
#   - OpenAI / DeepSeek    -> {"reasoning_effort": "low|medium|high"}
#   - GLM (智谱/coding)     -> {"thinking": {"type":"enabled|disabled"}}
#   - Ollama (local)       -> native options {"think": true}
# Effort is provider-neutral; the resolver below converts it to whatever the
# active provider+model actually understands, and unknown fields are stripped
# on a 400 fallback so non-reasoning models never break.
EFFORT_OFF = "off"

# split-source: order=880 original-lines=12566-12566 hash=0c5d5bfdf97a19e9
EFFORT_LOW = "low"

# split-source: order=881 original-lines=12567-12567 hash=b5439b37fab58e00
EFFORT_MEDIUM = "medium"

# split-source: order=882 original-lines=12568-12568 hash=82e662cb132aaefa
EFFORT_HIGH = "high"

# split-source: order=883 original-lines=12569-12569 hash=01bd36c88de4589d
EFFORT_MAX = "max"

# split-source: order=884 original-lines=12570-12570 hash=6460246751e15557
EFFORT_LEVELS = (EFFORT_OFF, EFFORT_LOW, EFFORT_MEDIUM, EFFORT_HIGH, EFFORT_MAX)

# split-source: order=885 original-lines=12571-12571 hash=0938bc0fa1221788
EFFORT_ORDER = {name: idx for idx, name in enumerate(EFFORT_LEVELS)}

# split-source: order=886 original-lines=12572-12572 hash=1559f599104bb115
EFFORT_DEFAULT = EFFORT_MEDIUM

# split-source: order=887 original-lines=12573-12580 hash=6f464f1a4b2eee46

# Anthropic extended-thinking token budgets per effort level.
EFFORT_ANTHROPIC_BUDGET = {
    EFFORT_LOW: 4_096,
    EFFORT_MEDIUM: 10_000,
    EFFORT_HIGH: 21_000,
    EFFORT_MAX: 32_000,
}

# split-source: order=888 original-lines=12581-12587 hash=9639aada761e4a0e
# OpenAI/DeepSeek reasoning_effort enum mapping (their API only has 3 tiers).
EFFORT_OPENAI_REASONING = {
    EFFORT_LOW: "low",
    EFFORT_MEDIUM: "medium",
    EFFORT_HIGH: "high",
    EFFORT_MAX: "high",
}

# split-source: order=889 original-lines=12588-12597 hash=af4090d39855aa3c

# Task level (L1-L5) -> default effort. L3-L5 are forced to MAX per spec:
# moderate/complex/expert tiers always run reasoning at full strength.
TASK_LEVEL_EFFORT = {
    1: EFFORT_LOW,
    2: EFFORT_LOW,
    3: EFFORT_MAX,
    4: EFFORT_MAX,
    5: EFFORT_MAX,
}

# split-source: order=890 original-lines=12598-12603 hash=28ad6e40a67252b2
# Per-role effort floor: managers and reviewers reason at least at HIGH even on
# lighter tiers, because routing/critique quality dominates outcome quality.
ROLE_EFFORT_FLOOR = {
    "manager": EFFORT_HIGH,
    "reviewer": EFFORT_HIGH,
}

# split-source: order=891 original-lines=12604-12607 hash=bd8afbd1d4cf64d1
# Per-round routing is a semantic decision over the active objective, evidence,
# permissions, and collaboration history. Keep enough reasoning budget for the
# Manager to make that decision itself; the runtime only validates the result.
COORDINATION_EFFORT = EFFORT_HIGH
