# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F821

from __future__ import annotations

# split-source: order=56 original-lines=66-66 hash=1193ac432052a5ff
DEFAULT_OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")

# split-source: order=57 original-lines=67-67 hash=e498053827490a72
DEFAULT_OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:7b")

# split-source: order=646 original-lines=6634-6643 hash=9a445aba4f015d9d

OPENAI_COMPAT_PROVIDER_NAMES = {
    "openai_compat",
    "siliconflow",
    "vllm",
    "lmstudio",
    "glm",
    "kimi",
    "openrouter",
}

# split-source: order=647 original-lines=6644-6645 hash=17e3a31f65cff18b

OPENAI_LIKE_PROVIDER_NAMES = OPENAI_COMPAT_PROVIDER_NAMES | {"custom_http"}

# split-source: order=650 original-lines=6652-6663 hash=d6ecf69b7361bfa0

# ── Effort / reasoning-budget model ────────────────────────────────────
# A single provider-neutral "effort" axis that maps onto each provider's
# native reasoning controls:
#   - Anthropic (Claude)  -> extended thinking: {"type":"enabled","budget_tokens":N}
#   - OpenAI / DeepSeek    -> {"reasoning_effort": "low|medium|high"}
#   - GLM (智谱/coding)     -> {"thinking": {"type":"enabled|disabled"}}
#   - Ollama (local)       -> native options {"think": true}
# Effort is provider-neutral; the resolver below converts it to whatever the
# active provider+model actually understands, and unknown fields are stripped
# on a 400 fallback so non-reasoning models never break.
EFFORT_OFF = "off"

# split-source: order=651 original-lines=6664-6664 hash=0c5d5bfdf97a19e9
EFFORT_LOW = "low"

# split-source: order=652 original-lines=6665-6665 hash=b5439b37fab58e00
EFFORT_MEDIUM = "medium"

# split-source: order=653 original-lines=6666-6666 hash=82e662cb132aaefa
EFFORT_HIGH = "high"

# split-source: order=654 original-lines=6667-6667 hash=01bd36c88de4589d
EFFORT_MAX = "max"

# split-source: order=655 original-lines=6668-6668 hash=6460246751e15557
EFFORT_LEVELS = (EFFORT_OFF, EFFORT_LOW, EFFORT_MEDIUM, EFFORT_HIGH, EFFORT_MAX)

# split-source: order=656 original-lines=6669-6669 hash=0938bc0fa1221788
EFFORT_ORDER = {name: idx for idx, name in enumerate(EFFORT_LEVELS)}

# split-source: order=657 original-lines=6670-6670 hash=1559f599104bb115
EFFORT_DEFAULT = EFFORT_MEDIUM

# split-source: order=658 original-lines=6671-6678 hash=6f464f1a4b2eee46

# Anthropic extended-thinking token budgets per effort level.
EFFORT_ANTHROPIC_BUDGET = {
    EFFORT_LOW: 4_096,
    EFFORT_MEDIUM: 10_000,
    EFFORT_HIGH: 21_000,
    EFFORT_MAX: 32_000,
}

# split-source: order=659 original-lines=6679-6685 hash=9639aada761e4a0e
# OpenAI/DeepSeek reasoning_effort enum mapping (their API only has 3 tiers).
EFFORT_OPENAI_REASONING = {
    EFFORT_LOW: "low",
    EFFORT_MEDIUM: "medium",
    EFFORT_HIGH: "high",
    EFFORT_MAX: "high",
}

# split-source: order=660 original-lines=6686-6695 hash=af4090d39855aa3c

# Task level (L1-L5) -> default effort. L3-L5 are forced to MAX per spec:
# moderate/complex/expert tiers always run reasoning at full strength.
TASK_LEVEL_EFFORT = {
    1: EFFORT_LOW,
    2: EFFORT_LOW,
    3: EFFORT_MAX,
    4: EFFORT_MAX,
    5: EFFORT_MAX,
}

# split-source: order=661 original-lines=6696-6701 hash=28ad6e40a67252b2
# Per-role effort floor: managers and reviewers reason at least at HIGH even on
# lighter tiers, because routing/critique quality dominates outcome quality.
ROLE_EFFORT_FLOOR = {
    "manager": EFFORT_HIGH,
    "reviewer": EFFORT_HIGH,
}

# split-source: order=662 original-lines=6702-6710 hash=e45835b7df73ce60
# Coordination effort: the manager's per-round *routing* decision is a mechanical
# tool-pick (missing facts->explorer, impl->developer, verify->reviewer, done->finish)
# constrained to a single route_to_next_agent call. It does NOT need HIGH/MAX
# reasoning every round — that was the single biggest token sink in multi-agent
# mode. Routing calls use this low effort and bypass ROLE_EFFORT_FLOOR; manager
# judgement/classification/planning calls keep the HIGH floor. On Anthropic/OpenAI
# this is a real 5-8x thinking-token cut per round; on GLM (binary thinking) it is
# neutral and the savings come from the loop/cache/tool-scope fixes.
COORDINATION_EFFORT = EFFORT_LOW
