# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from .._source_bridge import _split_source_symbol

# Symbols are bound from the original monolith to keep the split package importable.
# Use FRAMEWORK.md for the architecture map and Clouds_Coder.py for executable source.
probe_ollama_environment = _split_source_symbol('probe_ollama_environment')
list_ollama_models = _split_source_symbol('list_ollama_models')
_OLLAMA_TAG_CACHE_LOCK = _split_source_symbol('_OLLAMA_TAG_CACHE_LOCK')
_OLLAMA_TAG_CACHE = _split_source_symbol('_OLLAMA_TAG_CACHE')
list_ollama_models_cached = _split_source_symbol('list_ollama_models_cached')
resolve_ollama_model = _split_source_symbol('resolve_ollama_model')
infer_thinking_model = _split_source_symbol('infer_thinking_model')
split_thinking_content = _split_source_symbol('split_thinking_content')
strip_thinking_content = _split_source_symbol('strip_thinking_content')
check_ollama_model_ready = _split_source_symbol('check_ollama_model_ready')
list_loaded_ollama_models = _split_source_symbol('list_loaded_ollama_models')
wake_ollama_model = _split_source_symbol('wake_ollama_model')
try_pull_ollama_model = _split_source_symbol('try_pull_ollama_model')
ordered_model_candidates = _split_source_symbol('ordered_model_candidates')
pick_working_ollama_model = _split_source_symbol('pick_working_ollama_model')
extract_base_url = _split_source_symbol('extract_base_url')
complete_chat_endpoint = _split_source_symbol('complete_chat_endpoint')
normalize_openai_compat_provider_name = _split_source_symbol('normalize_openai_compat_provider_name')
is_openai_compat_provider = _split_source_symbol('is_openai_compat_provider')
is_openai_like_provider = _split_source_symbol('is_openai_like_provider')
openai_compat_probe_headers = _split_source_symbol('openai_compat_probe_headers')
openai_compat_model_list_urls = _split_source_symbol('openai_compat_model_list_urls')
extract_openai_compat_model_ids = _split_source_symbol('extract_openai_compat_model_ids')
_is_http_url = _split_source_symbol('_is_http_url')
_resolve_local_path = _split_source_symbol('_resolve_local_path')
