# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from __future__ import annotations
import base64
import multiprocessing
import os
import queue
import re
import shutil
import threading
from pathlib import Path

# ── cross-module imports ─────────────────────────────────────────────────
from ..config.constants import CODE_IMPORT_WORKER_COUNT, CODE_LIBRARY_IGNORED_DIRS, CODE_PARSE_TIMEOUT_SECONDS, RAG_IMPORT_WORKER_COUNT, RAG_MAX_IMPORT_BATCH_ITEMS, RAG_MAX_IMPORT_FILES, RAG_MODEL_MEDIA_MAX_BYTES, RAG_PARSE_TIMEOUT_SECONDS, RAG_PDF_IMAGE_LIMIT
from ..config.settings import default_multimodal_capabilities
from .parsers import CodeContentParser, RAGContentParser, _rag_extract_entities, _rag_safe_name
from .store import CodeLibraryStore, RAGLibraryStore
from ..session.state import SessionState
from ..utils.files import try_read_text
from ..utils.json_utils import _read_json_file, _write_json_file, parse_json_object
from ..utils.media import guess_mime_from_name
from ..utils.misc import make_id, now_ts
from ..utils.text import trim

def _rag_parse_file_worker(send_conn, source_path: str, mime: str, text_override: str, include_filename_entities: bool):
    try:
        parser = RAGContentParser(include_filename_entities=include_filename_entities)
        result = parser.parse_file(Path(source_path), mime=mime, text_override=text_override)
        send_conn.send({"ok": True, "result": result})
    except Exception as exc:
        try:
            send_conn.send({"ok": False, "error": trim(str(exc), 320)})
        except Exception:
            pass
    finally:
        try:
            send_conn.close()
        except Exception:
            pass

class RAGIngestionService:
    def __init__(self, store: RAGLibraryStore, parser: RAGContentParser, session_resolver=None):
        self.store = store
        self.parser = parser
        self.session_resolver = session_resolver if callable(session_resolver) else None
        self.queue: queue.Queue[dict] = queue.Queue()
        self.stop_event = threading.Event()
        self.worker_count = int(RAG_IMPORT_WORKER_COUNT)
        self.parse_timeout_seconds = int(RAG_PARSE_TIMEOUT_SECONDS)
        self.resume_report = {"resumed": 0, "failed": 0, "cleaned": 0}
        self._flush_lock = threading.Lock()
        self.threads = [
            threading.Thread(target=self._worker_loop, name=f"rag-ingestion-{idx+1}", daemon=True)
            for idx in range(self.worker_count)
        ]
        for thread in self.threads:
            thread.start()
        self._cleanup_finished_job_artifacts()
        self._resume_incomplete_tasks()

    def __getattr__(self, name: str):
        # Belt-and-suspenders: if _flush_lock was never set (e.g. partial init,
        # subclass skipped super().__init__), create it on first access so we
        # never crash with AttributeError inside _flush_ingest_state.
        if name == "_flush_lock":
            lock = threading.Lock()
            object.__setattr__(self, "_flush_lock", lock)
            return lock
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

    def _task_spool_path(self, task_id: str) -> Path:
        safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(task_id or "").strip()) or "task"
        return self.store.queue_root / f"{safe}.json"

    def _serialize_job_value(self, value):
        if isinstance(value, SessionState):
            return None
        if isinstance(value, Path):
            return str(value)
        if isinstance(value, (bytes, bytearray)):
            return {"__bytes_b64__": base64.b64encode(bytes(value)).decode("ascii")}
        if isinstance(value, dict):
            out: dict[str, object] = {}
            for key, item in value.items():
                if str(key) == "session":
                    continue
                out[str(key)] = self._serialize_job_value(item)
            return out
        if isinstance(value, (list, tuple)):
            return [self._serialize_job_value(item) for item in value]
        return value

    def _deserialize_job_value(self, value):
        if isinstance(value, dict):
            if set(value.keys()) == {"__bytes_b64__"}:
                try:
                    return base64.b64decode(str(value.get("__bytes_b64__", "") or ""))
                except Exception:
                    return b""
            return {str(key): self._deserialize_job_value(item) for key, item in value.items()}
        if isinstance(value, list):
            return [self._deserialize_job_value(item) for item in value]
        return value

    def _persist_job_payload(self, job: dict):
        task_id = str(job.get("task_id", "") or "").strip()
        if not task_id:
            return
        payload = {
            "version": 1,
            "task_id": task_id,
            "saved_at": now_ts(),
            "job": self._serialize_job_value(dict(job)),
        }
        spool_path = self._task_spool_path(task_id)
        _write_json_file(spool_path, payload)
        self.store.update_task(task_id, job_spool_path=self.store._rel(spool_path))

    def _load_job_payload(self, task_id: str) -> dict | None:
        spool_path = self._task_spool_path(task_id)
        raw = _read_json_file(spool_path, {})
        if not isinstance(raw, dict):
            return None
        payload = raw.get("job", {})
        if not isinstance(payload, dict):
            return None
        job = self._deserialize_job_value(payload)
        return dict(job) if isinstance(job, dict) else None

    def _drop_job_payload(self, task_id: str):
        try:
            self._task_spool_path(task_id).unlink(missing_ok=True)
        except Exception:
            pass

    def _cleanup_task_inbox(self, task_id: str):
        prefix = str(task_id or "").strip()
        if not prefix:
            return
        try:
            targets = list(self.store.inbox_root.glob(f"{prefix}*"))
        except Exception:
            targets = []
        for path in targets:
            try:
                if path.is_dir():
                    shutil.rmtree(path, ignore_errors=True)
                else:
                    path.unlink(missing_ok=True)
            except Exception:
                continue

    def _cleanup_finished_job_artifacts(self):
        cleaned = 0
        with self.store.lock:
            rows = [dict(x) for x in self.store.tasks]
        live_ids = {
            str(row.get("id", "") or "").strip()
            for row in rows
            if str(row.get("status", "") or "").strip().lower() in {"queued", "running"}
        }
        for row in rows:
            task_id = str(row.get("id", "") or "").strip()
            if not task_id or task_id in live_ids:
                continue
            self._cleanup_task_inbox(task_id)
            self._drop_job_payload(task_id)
            cleaned += 1
        try:
            for spool_path in self.store.queue_root.glob("*.json"):
                if spool_path.stem not in live_ids:
                    try:
                        spool_path.unlink(missing_ok=True)
                    except Exception:
                        continue
        except Exception:
            pass
        self.resume_report["cleaned"] = int(cleaned)

    def _resolve_job_session(self, session_id: str, user_id: str, current=None):
        if isinstance(current, SessionState):
            return current
        if not callable(self.session_resolver):
            return None
        uid = str(user_id or "").strip()
        if not uid:
            return None
        try:
            return self.session_resolver(uid, str(session_id or "").strip())
        except Exception:
            return None

    def _fallback_job_from_task(self, task: dict) -> dict | None:
        row = dict(task or {})
        task_id = str(row.get("id", "") or "").strip()
        task_type = str(row.get("type", "") or "").strip()
        session_id = str(row.get("session_id", "") or "").strip()
        user_id = str(row.get("user_id", "") or "").strip()
        source_path = str(row.get("source_path", "") or "").strip()
        if task_type == "session_upload" and source_path:
            return {
                "type": "session_upload",
                "task_id": task_id,
                "source_path": source_path,
                "parsed_path": str(row.get("parsed_path", "") or ""),
                "filename": str(row.get("filename", row.get("label", Path(source_path).name)) or Path(source_path).name),
                "mime": str(row.get("mime", "") or ""),
                "session_id": session_id,
                "user_id": user_id,
                "source_mode": str(row.get("source_mode", "session_upload") or "session_upload"),
            }
        if task_type == "manual_import" and source_path:
            return {
                "type": "manual_import",
                "task_id": task_id,
                "path": source_path,
                "recursive": bool(row.get("recursive", True)),
                "title": str(row.get("label", "") or ""),
                "filename": str(row.get("filename", "") or ""),
                "mime": str(row.get("mime", "") or ""),
                "session_id": session_id,
                "user_id": user_id,
                "source_mode": str(row.get("source_mode", "manual") or "manual"),
                "tags": [str(x).strip() for x in (row.get("tags", []) or []) if str(x).strip()],
                "strict_local_only": bool(row.get("strict_local_only", False)),
            }
        return None

    def _resume_task_job(self, task: dict) -> bool:
        row = dict(task or {})
        task_id = str(row.get("id", "") or "").strip()
        if not task_id:
            return False
        job = self._load_job_payload(task_id)
        if not isinstance(job, dict):
            job = self._fallback_job_from_task(row)
        if not isinstance(job, dict):
            self.store.update_task(
                task_id,
                status="failed",
                finished_at=now_ts(),
                error="pending import payload missing after restart; please submit the import again",
            )
            self._cleanup_task_inbox(task_id)
            self._drop_job_payload(task_id)
            self.resume_report["failed"] = int(self.resume_report.get("failed", 0) or 0) + 1
            return False
        session_id = str(job.get("session_id", row.get("session_id", "")) or "").strip()
        user_id = str(job.get("user_id", row.get("user_id", "")) or "").strip()
        session = self._resolve_job_session(session_id, user_id, job.get("session"))
        if isinstance(session, SessionState):
            job["session"] = session
        else:
            job.pop("session", None)
        job["task_id"] = task_id
        if not self._task_spool_path(task_id).exists():
            self._persist_job_payload(job)
        resume_count = int(row.get("resume_count", 0) or 0) + 1
        self.store.update_task(
            task_id,
            status="queued",
            started_at=0,
            finished_at=0,
            heartbeat_at=0,
            error="",
            resumed_at=now_ts(),
            resume_count=resume_count,
        )
        self.queue.put(job)
        self.resume_report["resumed"] = int(self.resume_report.get("resumed", 0) or 0) + 1
        return True

    def _resume_incomplete_tasks(self):
        for row in self.store.incomplete_tasks():
            try:
                self._resume_task_job(row)
            except Exception:
                task_id = str(row.get("id", "") or "").strip()
                if task_id:
                    self.store.update_task(
                        task_id,
                        status="failed",
                        finished_at=now_ts(),
                        error="resume failed after restart",
                    )
                    self._cleanup_task_inbox(task_id)
                    self._drop_job_payload(task_id)
                    self.resume_report["failed"] = int(self.resume_report.get("failed", 0) or 0) + 1

    def _queue_job(self, job: dict, *, persist: bool = True):
        if persist:
            self._persist_job_payload(job)
        self.queue.put(job)

    def shutdown(self, timeout: float = 2.0):
        self.stop_event.set()
        for _ in range(max(1, self.worker_count)):
            try:
                self.queue.put_nowait({"type": "__stop__"})
            except Exception:
                pass
        per_thread_timeout = max(0.1, float(timeout or 0.1)) / max(1, len(self.threads))
        for thread in self.threads:
            try:
                thread.join(timeout=per_thread_timeout)
            except Exception:
                pass

    def enqueue_upload(self, session: SessionState, upload_meta: dict, workspace_target: Path, parsed_target: Path | None) -> dict:
        task = self.store.register_task(
            {
                "type": "session_upload",
                "label": str(upload_meta.get("filename", workspace_target.name)),
                "source_path": str(workspace_target),
                "filename": str(upload_meta.get("filename", workspace_target.name)),
                "mime": str(upload_meta.get("mime", "") or ""),
                "parsed_path": str(parsed_target) if parsed_target else "",
                "session_id": str(getattr(session, "id", "") or ""),
                "user_id": str(getattr(session, "owner_user_id", "") or ""),
                "source_mode": "session_upload",
            }
        )
        self._queue_job(
            {
                "type": "session_upload",
                "task_id": str(task.get("id", "")),
                "source_path": str(workspace_target),
                "parsed_path": str(parsed_target) if parsed_target else "",
                "filename": str(upload_meta.get("filename", workspace_target.name)),
                "mime": str(upload_meta.get("mime", "") or ""),
                "session_id": str(getattr(session, "id", "") or ""),
                "user_id": str(getattr(session, "owner_user_id", "") or ""),
                "source_mode": "session_upload",
            }
        )
        return {
            "ok": True,
            "queued": True,
            "task_id": str(task.get("id", "")),
            "library_root": str(self.store.root),
        }

    def enqueue_import(
        self,
        *,
        path: str = "",
        session: SessionState | None = None,
        session_id: str = "",
        user_id: str = "",
        recursive: bool = True,
        title: str = "",
        text: str = "",
        filename: str = "",
        mime: str = "",
        content_bytes: bytes | None = None,
        source_mode: str = "manual",
        tags: list[str] | None = None,
        items: list[dict] | None = None,
        strict_local_only: bool = False,
    ) -> dict:
        normalized_items: list[dict] = []
        for row in (items or []):
            if not isinstance(row, dict):
                continue
            raw_bytes = row.get("content_bytes")
            item_text = str(row.get("text", "") or "")
            if not item_text.strip() and not isinstance(raw_bytes, (bytes, bytearray)):
                continue
            if len(normalized_items) >= RAG_MAX_IMPORT_BATCH_ITEMS:
                raise ValueError(f"too many import items in one batch (max {RAG_MAX_IMPORT_BATCH_ITEMS})")
            normalized_items.append(
                {
                    "filename": str(row.get("filename", "") or "").strip(),
                    "mime": str(row.get("mime", "") or "").strip(),
                    "text": item_text,
                    "relative_path": str(row.get("relative_path", "") or "").strip().replace("\\", "/").lstrip("/"),
                    "content_bytes": bytes(raw_bytes) if isinstance(raw_bytes, (bytes, bytearray)) else None,
                }
            )
        item_count = len(normalized_items)
        label = (
            title
            or filename
            or path
            or (
                normalized_items[0].get("relative_path")
                or normalized_items[0].get("filename")
                or "manual-import"
                if item_count == 1
                else ""
            )
            or (f"batch-import ({item_count} items)" if item_count > 1 else "manual-import")
        )
        task = self.store.register_task(
            {
                "type": "manual_import",
                "label": trim(label, 120),
                "source_path": str(path or ""),
                "filename": str(filename or ""),
                "mime": str(mime or ""),
                "session_id": str(session_id or getattr(session, "id", "") or ""),
                "user_id": str(user_id or getattr(session, "owner_user_id", "") or ""),
                "item_count": item_count or 1,
                "strict_local_only": bool(strict_local_only),
                "recursive": bool(recursive),
                "source_mode": str(source_mode or "manual"),
                "tags": [str(x).strip() for x in (tags or []) if str(x).strip()],
            }
        )
        self._queue_job(
            {
                "type": "manual_import",
                "task_id": str(task.get("id", "")),
                "session": session,
                "session_id": str(session_id or getattr(session, "id", "") or ""),
                "user_id": str(user_id or getattr(session, "owner_user_id", "") or ""),
                "path": str(path or ""),
                "recursive": bool(recursive),
                "title": str(title or ""),
                "text": str(text or ""),
                "filename": str(filename or ""),
                "mime": str(mime or ""),
                "content_bytes": content_bytes,
                "source_mode": str(source_mode or "manual"),
                "tags": [str(x).strip() for x in (tags or []) if str(x).strip()],
                "items": normalized_items,
                "strict_local_only": bool(strict_local_only),
            }
        )
        return {
            "ok": True,
            "queued": True,
            "task_id": str(task.get("id", "")),
            "library_root": str(self.store.root),
            "item_count": item_count or 1,
            "strict_local_only": bool(strict_local_only),
        }

    def _parse_file_safe(self, source_path: Path, *, mime: str = "", text_override: str = "") -> dict:
        kind = self.parser.detect_kind(source_path, mime=mime)
        if kind in {"text", "csv", "image", "audio", "video"}:
            return self.parser.parse_file(source_path, mime=mime, text_override=text_override)
        ctx = multiprocessing.get_context("spawn")
        parent_conn, child_conn = ctx.Pipe(duplex=False)
        proc = ctx.Process(
            target=_rag_parse_file_worker,
            args=(
                child_conn,
                str(source_path),
                str(mime or ""),
                str(text_override or ""),
                bool(getattr(self.parser, "include_filename_entities", False)),
            ),
        )
        try:
            proc.start()
            try:
                child_conn.close()
            except Exception:
                pass
            if not parent_conn.poll(self.parse_timeout_seconds):
                raise TimeoutError(f"parse timeout after {self.parse_timeout_seconds}s ({kind or 'document'})")
            payload = parent_conn.recv()
            if not isinstance(payload, dict):
                raise RuntimeError("parser worker returned invalid payload")
            if not bool(payload.get("ok", False)):
                raise RuntimeError(str(payload.get("error", "parse failed") or "parse failed"))
            result = payload.get("result")
            if not isinstance(result, dict):
                raise RuntimeError("parser worker returned invalid result")
            return dict(result)
        finally:
            try:
                parent_conn.close()
            except Exception:
                pass
            try:
                if proc.is_alive():
                    proc.terminate()
                    proc.join(timeout=1.5)
            except Exception:
                pass
            try:
                if proc.is_alive():
                    proc.kill()
                    proc.join(timeout=0.5)
            except Exception:
                pass

    def _session_capabilities(self, session: SessionState | None) -> dict[str, bool]:
        if not isinstance(session, SessionState):
            return default_multimodal_capabilities()
        try:
            return session._capabilities_from_profile()
        except Exception:
            return default_multimodal_capabilities()

    def _multimodal_enrich(self, session: SessionState | None, title: str, parse_result: dict, media_rows: list[dict]) -> dict:
        if not isinstance(session, SessionState):
            return {"status": "skipped", "reason": "no_session"}
        caps = self._session_capabilities(session)
        selected: list[dict] = []
        skipped: list[str] = []
        kind = str(parse_result.get("kind", "") or "")
        for row in media_rows:
            media_type = str(row.get("type", "") or "").strip().lower()
            cap_key = {
                "image": "input_image",
                "audio": "input_audio",
                "video": "input_video",
            }.get(media_type, "")
            if not cap_key or not bool(caps.get(cap_key, False)):
                skipped.append(f"{media_type}:capability_disabled")
                continue
            fp = Path(str(row.get("path", "") or ""))
            if not fp.exists() or not fp.is_file():
                skipped.append(f"{media_type}:missing")
                continue
            if fp.stat().st_size > RAG_MODEL_MEDIA_MAX_BYTES:
                skipped.append(f"{media_type}:too_large")
                continue
            try:
                selected.append(
                    {
                        "type": media_type,
                        "name": str(row.get("name", fp.name) or fp.name),
                        "mime": str(row.get("mime", guess_mime_from_name(fp.name, "application/octet-stream")) or ""),
                        "data_b64": base64.b64encode(fp.read_bytes()).decode("ascii"),
                    }
                )
            except Exception:
                skipped.append(f"{media_type}:read_failed")
                continue
            if media_type in {"audio", "video"}:
                break
            if sum(1 for item in selected if str(item.get("type", "")) == "image") >= 3:
                break
        if not selected:
            return {"status": "skipped", "reason": "no_compatible_media", "skipped": skipped}
        context_text = trim(str(parse_result.get("text", "") or parse_result.get("summary", "") or ""), 1800)
        title_line = f"Title: {title}\n" if bool(getattr(self.parser, "include_filename_entities", False)) else ""
        prompt = (
            "Analyze these uploaded knowledge-base assets and return strict JSON with keys "
            "summary, tags, entities, category, confidence, findings. "
            f"{title_line}Kind: {kind}\nExisting text context:\n{context_text}"
        )
        try:
            rsp = session.ollama.chat(
                [{"role": "user", "content": prompt}],
                max_tokens=700,
                temperature=0.1,
                think=False,
                stream_thinking=False,
                media_inputs=selected,
            )
            payload = parse_json_object(str(rsp.get("content", "") or ""), {})
            summary = trim(str(payload.get("summary", "") or rsp.get("content", "") or ""), 2400)
            tags = [str(x).strip() for x in (payload.get("tags", []) or []) if str(x).strip()]
            entities = [str(x).strip() for x in (payload.get("entities", []) or []) if str(x).strip()]
            if not entities:
                entities = _rag_extract_entities(summary)
            return {
                "status": "completed",
                "summary": summary,
                "tags": tags[:16],
                "entities": entities[:24],
                "category": str(payload.get("category", parse_result.get("category", "")) or ""),
                "confidence": str(payload.get("confidence", "medium") or "medium"),
                "findings": payload.get("findings", []) if isinstance(payload.get("findings"), list) else [],
                "used_media": [str(x.get("name", "")) for x in selected],
                "skipped": skipped,
            }
        except Exception as exc:
            return {"status": "failed", "error": trim(str(exc), 240), "skipped": skipped}

    def _collect_supported_files(self, root: Path, recursive: bool) -> list[Path]:
        files: list[Path] = []
        iterator = root.rglob("*") if recursive else root.glob("*")
        for path in iterator:
            if len(files) >= RAG_MAX_IMPORT_FILES:
                break
            try:
                if not path.is_file():
                    continue
            except Exception:
                continue
            if self.parser.supported_file(path):
                files.append(path)
        return files

    def _ingest_one_file(
        self,
        *,
        task_id: str,
        source_path: Path,
        session: SessionState | None,
        session_id: str,
        user_id: str,
        filename: str,
        mime: str,
        source_mode: str,
        tags: list[str],
        source_rel_path: str = "",
        strict_local_only: bool = False,
        content_bytes: bytes | None = None,
        text_override: str = "",
        persist_now: bool = True,
        rebuild_index_now: bool = True,
    ) -> dict:
        parse_result = self._parse_file_safe(source_path, mime=mime, text_override=text_override)
        doc_id = make_id("ragdoc")
        media_rows: list[dict] = []
        asset_sources: list[dict] = []
        kind = str(parse_result.get("kind", "") or "")
        if kind in {"image", "audio", "video"}:
            media_rows.append(
                {
                    "type": kind,
                    "path": str(source_path),
                    "name": filename or source_path.name,
                    "mime": parse_result.get("mime", mime),
                }
            )
        elif kind == "pdf":
            pdf_asset_dir = self.store.inbox_root / f"{task_id}_{source_path.stem}_pdf_assets"
            pdf_assets = self.parser.extract_pdf_images(source_path, pdf_asset_dir, limit=RAG_PDF_IMAGE_LIMIT)
            media_rows.extend(pdf_assets)
            asset_sources.extend(pdf_assets)
        multimodal = (
            {"status": "skipped", "reason": "strict_local_only"}
            if bool(strict_local_only)
            else self._multimodal_enrich(session, filename or source_path.name, parse_result, media_rows)
        )
        return self.store.ingest_document(
            doc_id=doc_id,
            source_path=source_path,
            original_name=filename or source_path.name,
            parse_result=parse_result,
            raw_bytes=content_bytes,
            source_mode=source_mode,
            session_id=session_id,
            user_id=user_id,
            source_rel_path=source_rel_path,
            tags=tags,
            multimodal=multimodal,
            asset_sources=asset_sources,
            persist_now=persist_now,
            rebuild_index_now=rebuild_index_now,
        )

    def _worker_loop(self):
        while not self.stop_event.is_set():
            try:
                job = self.queue.get(timeout=0.4)
            except queue.Empty:
                continue
            if not isinstance(job, dict):
                self.queue.task_done()
                continue
            if str(job.get("type", "")) == "__stop__":
                self.queue.task_done()
                break
            task_id = str(job.get("task_id", "") or "")
            self._cleanup_task_inbox(task_id)
            self.store.update_task(task_id, status="running", started_at=now_ts())
            try:
                result_rows: list[dict] = []
                item_errors: list[str] = []
                pending_flushes = 0
                pending_rebuild = False
                last_progress_at = 0.0
                session = job.get("session") if isinstance(job.get("session"), SessionState) else None
                session_id = str(job.get("session_id", "") or getattr(session, "id", "") or "")
                user_id = str(job.get("user_id", "") or getattr(session, "owner_user_id", "") or "")
                session = self._resolve_job_session(session_id, user_id, session)
                if isinstance(session, SessionState):
                    session_id = str(session_id or getattr(session, "id", "") or "")
                    user_id = str(user_id or getattr(session, "owner_user_id", "") or "")
                source_mode = str(job.get("source_mode", "manual") or "manual")
                tags = [str(x).strip() for x in (job.get("tags", []) or []) if str(x).strip()]
                strict_local_only = bool(job.get("strict_local_only", False))
                batch_items = [dict(x) for x in (job.get("items", []) or []) if isinstance(x, dict)][:RAG_MAX_IMPORT_BATCH_ITEMS]

                def _update_progress(current: int, total: int, label: str):
                    nonlocal last_progress_at
                    now = now_ts()
                    current_item = int(current or 0)
                    total_items = int(total or 0)
                    force = total_items <= 1 or current_item <= 1 or current_item >= total_items
                    if not force and current_item % 8 != 0 and (now - last_progress_at) < 0.75:
                        return
                    last_progress_at = now
                    self.store.update_task(
                        task_id,
                        heartbeat_at=now,
                        current_item=current_item,
                        total_items=total_items,
                        progress_label=trim(str(label or ""), 220),
                    )

                def _flush_ingest_state():
                    nonlocal pending_flushes, pending_rebuild
                    if pending_flushes <= 0:
                        return
                    with self._flush_lock:
                        self.store.flush_content_state()
                        if pending_rebuild:
                            self.store.rebuild_index()
                    pending_flushes = 0
                    pending_rebuild = False
                    result_rows.clear()

                def _capture_ingest(**kwargs):
                    nonlocal pending_flushes, pending_rebuild
                    try:
                        row = self._ingest_one_file(
                            persist_now=False,
                            rebuild_index_now=False,
                            **kwargs,
                        )
                        result_rows.append(row)
                        pending_flushes += 1
                        if bool(row.get("ok", False)) and not bool(row.get("duplicate", False)):
                            pending_rebuild = True
                        if pending_flushes >= 12:
                            _flush_ingest_state()
                    except Exception as exc:
                        label = str(
                            kwargs.get("source_rel_path", "")
                            or kwargs.get("filename", "")
                            or Path(str(kwargs.get("source_path", "") or "")).name
                            or "item"
                        )
                        item_errors.append(f"{label}: {trim(str(exc), 220)}")

                if str(job.get("type", "")) == "session_upload":
                    src = Path(str(job.get("source_path", "") or "")).resolve()
                    parsed_path = Path(str(job.get("parsed_path", "") or "")).resolve() if str(job.get("parsed_path", "") or "").strip() else None
                    text_override = ""
                    if parsed_path and parsed_path.exists():
                        text_override = try_read_text(parsed_path, max_bytes=300_000) or ""
                    _update_progress(1, 1, str(job.get("filename", src.name) or src.name))
                    _capture_ingest(
                        task_id=task_id,
                        source_path=src,
                        session=session,
                        session_id=session_id,
                        user_id=user_id,
                        filename=str(job.get("filename", src.name) or src.name),
                        mime=str(job.get("mime", "") or ""),
                        source_mode=source_mode,
                        tags=tags,
                        strict_local_only=strict_local_only,
                        text_override=text_override,
                    )
                elif batch_items:
                    total_batch_items = len(batch_items)
                    for idx, item in enumerate(batch_items, 1):
                        rel_path = str(item.get("relative_path", "") or "").strip().replace("\\", "/").lstrip("/")
                        base_name = rel_path.rsplit("/", 1)[-1] if rel_path else str(item.get("filename", "") or "").strip()
                        filename = _rag_safe_name(base_name or f"uploaded_{idx}.bin", f"uploaded_{idx}.bin")
                        item_text = str(item.get("text", "") or "")
                        item_bytes = item.get("content_bytes") if isinstance(item.get("content_bytes"), (bytes, bytearray)) else None
                        temp_path = self.store.inbox_root / f"{task_id}_{make_id('ragitem')}_{filename}"
                        _update_progress(idx, total_batch_items, rel_path or filename)
                        if item_text.strip():
                            temp_path.write_text(item_text, encoding="utf-8")
                            _capture_ingest(
                                task_id=task_id,
                                source_path=temp_path,
                                session=session,
                                session_id=session_id,
                                user_id=user_id,
                                filename=filename,
                                mime=str(item.get("mime", "text/plain") or "text/plain"),
                                source_mode=source_mode,
                                tags=tags,
                                source_rel_path=rel_path or filename,
                                strict_local_only=strict_local_only,
                                text_override=item_text,
                            )
                        elif item_bytes is not None:
                            temp_path.write_bytes(bytes(item_bytes))
                            _capture_ingest(
                                task_id=task_id,
                                source_path=temp_path,
                                session=session,
                                session_id=session_id,
                                user_id=user_id,
                                filename=filename,
                                mime=str(item.get("mime", "") or ""),
                                source_mode=source_mode,
                                tags=tags,
                                source_rel_path=rel_path or filename,
                                strict_local_only=strict_local_only,
                                content_bytes=bytes(item_bytes),
                            )
                else:
                    text = str(job.get("text", "") or "")
                    content_bytes = job.get("content_bytes") if isinstance(job.get("content_bytes"), (bytes, bytearray)) else None
                    if text:
                        filename = _rag_safe_name(str(job.get("filename", "") or job.get("title", "") or "manual_note.txt"), "manual_note.txt")
                        temp_path = self.store.inbox_root / f"{task_id}_{filename}"
                        temp_path.write_text(text, encoding="utf-8")
                        _capture_ingest(
                            task_id=task_id,
                            source_path=temp_path,
                            session=session,
                            session_id=session_id,
                            user_id=user_id,
                            filename=filename,
                            mime=str(job.get("mime", "text/plain") or "text/plain"),
                            source_mode=source_mode,
                            tags=tags,
                            source_rel_path=filename,
                            strict_local_only=strict_local_only,
                            text_override=text,
                        )
                    elif content_bytes is not None:
                        filename = _rag_safe_name(str(job.get("filename", "") or "uploaded.bin"), "uploaded.bin")
                        temp_path = self.store.inbox_root / f"{task_id}_{filename}"
                        temp_path.write_bytes(bytes(content_bytes))
                        _capture_ingest(
                            task_id=task_id,
                            source_path=temp_path,
                            session=session,
                            session_id=session_id,
                            user_id=user_id,
                            filename=filename,
                            mime=str(job.get("mime", "") or ""),
                            source_mode=source_mode,
                            tags=tags,
                            source_rel_path=filename,
                            strict_local_only=strict_local_only,
                            content_bytes=bytes(content_bytes),
                        )
                    else:
                        raw_path = str(job.get("path", "") or "").strip()
                        if not raw_path:
                            raise ValueError("import path required")
                        source_path = Path(raw_path).expanduser().resolve()
                        if source_path.is_dir():
                            files = self._collect_supported_files(source_path, recursive=bool(job.get("recursive", True)))
                            total_files = len(files)
                            for idx, fp in enumerate(files, 1):
                                try:
                                    rel_path = fp.relative_to(source_path).as_posix()
                                except Exception:
                                    rel_path = fp.name
                                _update_progress(idx, total_files, rel_path)
                                _capture_ingest(
                                    task_id=task_id,
                                    source_path=fp,
                                    session=session,
                                    session_id=session_id,
                                    user_id=user_id,
                                    filename=fp.name,
                                    mime="",
                                    source_mode=source_mode,
                                    tags=tags,
                                    source_rel_path=rel_path,
                                    strict_local_only=strict_local_only,
                                )
                        else:
                            _update_progress(1, 1, source_path.name)
                            _capture_ingest(
                                task_id=task_id,
                                source_path=source_path,
                                session=session,
                                session_id=session_id,
                                user_id=user_id,
                                filename=source_path.name,
                                mime=str(job.get("mime", "") or ""),
                                source_mode=source_mode,
                                tags=tags,
                                source_rel_path=source_path.name,
                                strict_local_only=strict_local_only,
                            )
                _flush_ingest_state()
                ok_count = sum(1 for row in result_rows if bool(row.get("ok", False)))
                duplicate_count = sum(1 for row in result_rows if bool(row.get("duplicate", False)))
                failed_count = len(item_errors)
                if failed_count and ok_count <= 0:
                    raise ValueError("\n".join(item_errors[:12]))
                self.store.update_task(
                    task_id,
                    status="completed_with_errors" if failed_count else "completed",
                    finished_at=now_ts(),
                    imported_count=ok_count,
                    duplicate_count=duplicate_count,
                    failed_count=failed_count,
                    error="\n".join(item_errors[:12]),
                    doc_ids=[str(x.get("doc_id", "")) for x in result_rows if str(x.get("doc_id", "")).strip()],
                )
            except Exception as exc:
                self.store.update_task(
                    task_id,
                    status="failed",
                    finished_at=now_ts(),
                    error=trim(str(exc), 320),
                )
            finally:
                self._cleanup_task_inbox(task_id)
                current = self.store.get_task(task_id)
                status = str((current or {}).get("status", "") or "").strip().lower()
                if status and status not in {"queued", "running"}:
                    self._drop_job_payload(task_id)
                self.queue.task_done()

class CodeIngestionService(RAGIngestionService):
    def __init__(self, store: CodeLibraryStore, parser: CodeContentParser, session_resolver=None):
        self.store = store
        self.parser = parser
        self.session_resolver = session_resolver if callable(session_resolver) else None
        self.queue: queue.Queue[dict] = queue.Queue()
        self.stop_event = threading.Event()
        self.worker_count = int(CODE_IMPORT_WORKER_COUNT)
        self.parse_timeout_seconds = int(CODE_PARSE_TIMEOUT_SECONDS)
        self.resume_report = {"resumed": 0, "failed": 0, "cleaned": 0}
        self._flush_lock = threading.Lock()
        self.threads = [
            threading.Thread(target=self._worker_loop, name=f"code-ingestion-{idx+1}", daemon=True)
            for idx in range(self.worker_count)
        ]
        for thread in self.threads:
            thread.start()
        self._cleanup_finished_job_artifacts()
        self._resume_incomplete_tasks()

    def _collect_supported_files(self, root: Path, recursive: bool) -> list[Path]:
        files: list[Path] = []
        if not root.exists():
            return files
        if not recursive:
            for path in sorted(root.glob("*")):
                try:
                    if path.is_file() and self.parser.supported_file(path):
                        files.append(path)
                except Exception:
                    continue
                if len(files) >= RAG_MAX_IMPORT_FILES:
                    break
            return files
        for current_root, dirnames, filenames in os.walk(root):
            dirnames[:] = [name for name in dirnames if name.lower() not in CODE_LIBRARY_IGNORED_DIRS and not name.startswith(".")]
            current_path = Path(current_root)
            for name in sorted(filenames):
                fp = current_path / name
                try:
                    if fp.is_file() and self.parser.supported_file(fp):
                        files.append(fp)
                except Exception:
                    continue
                if len(files) >= RAG_MAX_IMPORT_FILES:
                    return files
        return files

    def _ingest_one_file(
        self,
        *,
        task_id: str,
        source_path: Path,
        session: SessionState | None,
        session_id: str,
        user_id: str,
        filename: str,
        mime: str,
        source_mode: str,
        tags: list[str],
        source_rel_path: str = "",
        strict_local_only: bool = False,
        content_bytes: bytes | None = None,
        text_override: str = "",
        persist_now: bool = True,
        rebuild_index_now: bool = True,
    ) -> dict:
        if not self.parser.supported_file(source_path):
            raise ValueError(f"unsupported code file: {source_path.name}")
        parse_result = self.parser.parse_file(source_path, mime=mime, text_override=text_override)
        doc_id = make_id("codedoc")
        return self.store.ingest_document(
            doc_id=doc_id,
            source_path=source_path,
            original_name=filename or source_path.name,
            parse_result=parse_result,
            raw_bytes=content_bytes,
            source_mode=source_mode,
            session_id=session_id,
            user_id=user_id,
            source_rel_path=source_rel_path,
            tags=tags,
            persist_now=persist_now,
            rebuild_index_now=rebuild_index_now,
        )

