# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=653 original-lines=6165-6171 hash=d4aaf23433416734

def compress_text_blob(text: str) -> str:
    src = str(text or "")
    if not src:
        return ""
    raw = src.encode("utf-8")
    return base64.b64encode(zlib.compress(raw, 6)).decode("ascii")

# split-source: order=654 original-lines=6172-6181 hash=c2d373626d05f242

def decompress_text_blob(blob_b64: str) -> str:
    token = str(blob_b64 or "").strip()
    if not token:
        return ""
    try:
        raw = base64.b64decode(token.encode("ascii"))
        return zlib.decompress(raw).decode("utf-8", errors="replace")
    except Exception:
        return ""
