# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from __future__ import annotations
import base64
import zlib

def compress_text_blob(text: str) -> str:
    src = str(text or "")
    if not src:
        return ""
    raw = src.encode("utf-8")
    return base64.b64encode(zlib.compress(raw, 6)).decode("ascii")

def decompress_text_blob(blob_b64: str) -> str:
    token = str(blob_b64 or "").strip()
    if not token:
        return ""
    try:
        raw = base64.b64decode(token.encode("ascii"))
        return zlib.decompress(raw).decode("utf-8", errors="replace")
    except Exception:
        return ""

