# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=107 original-lines=230-230 hash=48865d9a7490efb5
JSON_FSYNC_ENABLED = str(os.getenv("AGENT_JSON_FSYNC", "true") or "true").strip().lower() not in {"0", "false", "no", "off"}

# split-source: order=598 original-lines=3805-3808 hash=e1513981a13c723f

def json_dumps(obj: object, *, indent: int | None = None, ensure_ascii: bool = False) -> str:
    raw = json.dumps(obj, ensure_ascii=ensure_ascii, indent=indent)
    return escape_invalid_utf8_text(raw)

# split-source: order=663 original-lines=6475-6485 hash=5307c5450c8ad587

def parse_tool_arguments(raw: object) -> dict:
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            parsed = json.loads(raw)
            return parsed if isinstance(parsed, dict) else {}
        except Exception:
            return {}
    return {}

# split-source: order=664 original-lines=6486-6540 hash=ba4ea688566de9b0

def repair_truncated_json_object(raw: object) -> str:
    src = str(raw or "").strip()
    if not src:
        return ""
    fenced = re.search(r"```(?:json)?\s*([\s\S]*?)```", src, re.IGNORECASE)
    if fenced:
        src = str(fenced.group(1) or "").strip()
    first_obj = src.find("{")
    if first_obj > 0:
        src = src[first_obj:]
    src = src.strip()
    if not src:
        return ""
    if src.endswith(":"):
        src += " null"
    src = re.sub(r",\s*$", "", src)
    if "\n" in src and re.search(r"[,:\[{(\"'`]$", src.rstrip()):
        src = src[: src.rfind("\n")].rstrip()
    if not src:
        return ""
    stack: list[str] = []
    in_string = False
    escaped = False
    for ch in src:
        if in_string:
            if escaped:
                escaped = False
                continue
            if ch == "\\":
                escaped = True
                continue
            if ch == "\"":
                in_string = False
            continue
        if ch == "\"":
            in_string = True
            continue
        if ch in "{[":
            stack.append(ch)
            continue
        if ch == "}" and stack and stack[-1] == "{":
            stack.pop()
            continue
        if ch == "]" and stack and stack[-1] == "[":
            stack.pop()
            continue
    if in_string:
        src += "\""
    src = re.sub(r",\s*$", "", src)
    while stack:
        opener = stack.pop()
        src += "}" if opener == "{" else "]"
    src = re.sub(r",(\s*[}\]])", r"\1", src)
    return src.strip()

# split-source: order=665 original-lines=6541-6572 hash=7d2fb800ce2aba73

def parse_tool_arguments_with_error(raw: object) -> tuple[dict, str]:
    if isinstance(raw, dict):
        return raw, ""
    if isinstance(raw, str):
        text = raw.strip()
        if not text:
            return {}, "arguments is empty string"
        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                return parsed, ""
            return {}, f"arguments JSON is {type(parsed).__name__}, expected object"
        except Exception as exc:
            repaired = repair_truncated_json_object(text)
            if repaired and repaired != text:
                try:
                    parsed_repaired = json.loads(repaired)
                    if isinstance(parsed_repaired, dict):
                        # Check repair confidence: count fields that look truncated
                        truncated_fields = sum(
                            1 for v in parsed_repaired.values()
                            if isinstance(v, str) and (v.endswith("...") or v.endswith("\\"))
                        )
                        if truncated_fields == 0:
                            return parsed_repaired, "arguments JSON auto-repaired from invalid/truncated input"
                        return parsed_repaired, f"arguments JSON auto-repaired (low confidence: {truncated_fields} possibly truncated fields)"
                except Exception:
                    pass
            brief = trim(text.replace("\n", "\\n"), 240)
            return {}, f"arguments JSON parse failed: {exc}; raw={brief}"
    return {}, f"unsupported arguments type: {type(raw).__name__}"

# split-source: order=666 original-lines=6573-6578 hash=0edae7a6e375829d

def _is_valid_json_object(text: object) -> bool:
    try:
        return isinstance(json.loads(str(text)), dict)
    except Exception:
        return False

# split-source: order=667 original-lines=6579-6602 hash=fd22a71d21becf3d

def _scan_top_level_json_objects(text: str) -> list[str]:
    """Return every top-level {...} substring in text that decodes to an object.
    Used to salvage tool arguments when a streaming endpoint sends multiple
    cumulative JSON snapshots that got naively concatenated into one string."""
    out: list[str] = []
    src = str(text or "")
    decoder = json.JSONDecoder()
    i, n = 0, len(src)
    while i < n:
        if src[i] != "{":
            i += 1
            continue
        try:
            obj, end = decoder.raw_decode(src, i)
        except Exception:
            i += 1
            continue
        if isinstance(obj, dict) and end > i:
            out.append(src[i:end])
            i = end
        else:
            i = end if end > i else i + 1
    return out

# split-source: order=668 original-lines=6603-6647 hash=a020af34209979c8

def reconstruct_streamed_tool_args(fragments: object) -> str:
    """Rebuild a tool call's argument JSON from the per-delta fragments captured
    during a streamed response, tolerant of differing provider dialects.

    Strict OpenAI streams *incremental* fragments that must be concatenated.
    Several non-strict endpoints (some Chinese clouds, certain GLM/ark gateways)
    instead stream *cumulative* snapshots — each chunk re-sends the whole (growing)
    arguments object. Naive concatenation of cumulative chunks yields
    `{...}{...}` which fails to parse and forces a malformed-arguments fallback
    (felt hardest on write_files, where large content = many chunks).

    Strategy, in order:
      1. single fragment              -> return as-is
      2. concatenation parses to dict -> incremental dialect, return concat
      3. every chunk starts with "{"  -> cumulative dialect, return the longest
                                         fragment (prefer one that parses); the
                                         longest snapshot is the most complete
      4. multiple complete objects    -> salvage the last complete top-level {...}
      5. otherwise                    -> return concat for downstream repair
    """
    if isinstance(fragments, str):
        return fragments
    frags = [str(f) for f in (fragments or []) if f is not None and str(f) != ""]
    if not frags:
        return ""
    if len(frags) == 1:
        return frags[0]
    joined = "".join(frags)
    # (2) incremental dialect: the concatenation is itself a valid object.
    if _is_valid_json_object(joined):
        return joined
    # (3) cumulative dialect: each chunk independently begins with "{".
    stripped = [f.lstrip() for f in frags if f.strip()]
    if stripped and all(s.startswith("{") for s in stripped):
        valid = [f for f in frags if _is_valid_json_object(f)]
        if valid:
            return max(valid, key=len)
        return max(frags, key=len)
    # (4) several complete objects concatenated: keep the last complete snapshot.
    objs = _scan_top_level_json_objects(joined)
    if objs:
        return objs[-1]
    # (5) genuinely truncated/garbled: hand the concatenation to repair downstream.
    return joined

# split-source: order=686 original-lines=6912-6918 hash=107b133e877d9d78

def parse_json_object(text: str, default: dict | None = None) -> dict:
    try:
        obj = json.loads(text)
        return obj if isinstance(obj, dict) else (default or {})
    except Exception:
        return default or {}

# split-source: order=687 original-lines=6919-6942 hash=0a499c26dfa8ee1a

def extract_json_object_from_text(text: str, default: dict | None = None) -> dict:
    src = str(text or "").strip()
    if not src:
        return default or {}
    direct = parse_json_object(src, {})
    if direct:
        return direct
    fence = re.search(r"```json\s*(\{.*?\})\s*```", src, re.S | re.I)
    if fence:
        boxed = parse_json_object(fence.group(1), {})
        if boxed:
            return boxed
    decoder = json.JSONDecoder()
    for i, ch in enumerate(src):
        if ch != "{":
            continue
        try:
            obj, _ = decoder.raw_decode(src[i:])
        except Exception:
            continue
        if isinstance(obj, dict):
            return obj
    return default or {}

# split-source: order=730 original-lines=8450-8456 hash=447a2de5bc82a133

def _json_default_copy(default: object) -> object:
    if isinstance(default, dict):
        return dict(default)
    if isinstance(default, list):
        return list(default)
    return default

# split-source: order=731 original-lines=8457-8478 hash=3bf3649f6416e766

def _read_json_file(path: Path, default: object) -> object:
    bak = path.with_name(f"{path.name}.bak")
    expected_dict = isinstance(default, dict)
    expected_list = isinstance(default, list)
    for fp in (path, bak):
        if not fp.exists() or (not fp.is_file()):
            continue
        try:
            raw = fp.read_text(encoding="utf-8")
        except Exception:
            continue
        try:
            obj = json.loads(raw)
        except Exception:
            continue
        if expected_dict and not isinstance(obj, dict):
            continue
        if expected_list and not isinstance(obj, list):
            continue
        return obj
    return _json_default_copy(default)

# split-source: order=732 original-lines=8479-8507 hash=a8537823069e1ffa

def _write_json_file(path: Path, obj: object):
    path.parent.mkdir(parents=True, exist_ok=True)
    bak = path.with_name(f"{path.name}.bak")
    tmp = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        with tmp.open("w", encoding="utf-8") as f:
            f.write(json_dumps(obj, indent=2))
            f.flush()
            if JSON_FSYNC_ENABLED:
                try:
                    os.fsync(f.fileno())
                except Exception:
                    pass
        if path.exists():
            try:
                os.replace(path, bak)
            except Exception:
                try:
                    shutil.copy2(path, bak)
                except Exception:
                    pass
        os.replace(tmp, path)
    finally:
        try:
            if tmp.exists():
                tmp.unlink()
        except Exception:
            pass
