# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from .._source_bridge import _split_source_symbol

# Symbols are bound from the original monolith to keep the split package importable.
# Use FRAMEWORK.md for the architecture map and Clouds_Coder.py for executable source.
JSON_FSYNC_ENABLED = _split_source_symbol('JSON_FSYNC_ENABLED')
json_dumps = _split_source_symbol('json_dumps')
parse_tool_arguments = _split_source_symbol('parse_tool_arguments')
repair_truncated_json_object = _split_source_symbol('repair_truncated_json_object')
parse_tool_arguments_with_error = _split_source_symbol('parse_tool_arguments_with_error')
parse_json_object = _split_source_symbol('parse_json_object')
extract_json_object_from_text = _split_source_symbol('extract_json_object_from_text')
_json_default_copy = _split_source_symbol('_json_default_copy')
_read_json_file = _split_source_symbol('_read_json_file')
_write_json_file = _split_source_symbol('_write_json_file')
tool_def = _split_source_symbol('tool_def')
TOOLS = _split_source_symbol('TOOLS')
TOOL_REQUIRED_ARGS = _split_source_symbol('TOOL_REQUIRED_ARGS')
TOOL_SPEC_BY_NAME = _split_source_symbol('TOOL_SPEC_BY_NAME')
TOOL_NAME_FUZZY_MAP = _split_source_symbol('TOOL_NAME_FUZZY_MAP')
canonicalize_tool_name = _split_source_symbol('canonicalize_tool_name')
