# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from .._source_bridge import _split_source_symbol

# Symbols are bound from the original monolith to keep the split package importable.
# Use FRAMEWORK.md for the architecture map and Clouds_Coder.py for executable source.
MIN_TIMEOUT_SECONDS = _split_source_symbol('MIN_TIMEOUT_SECONDS')
MAX_TIMEOUT_SECONDS = _split_source_symbol('MAX_TIMEOUT_SECONDS')
DEFAULT_TIMEOUT_SECONDS = _split_source_symbol('DEFAULT_TIMEOUT_SECONDS')
BENIGN_SOCKET_DEBUG_LOG_ENABLED = _split_source_symbol('BENIGN_SOCKET_DEBUG_LOG_ENABLED')
BENIGN_SOCKET_LOG_INTERVAL_SECONDS = _split_source_symbol('BENIGN_SOCKET_LOG_INTERVAL_SECONDS')
now_ts = _split_source_symbol('now_ts')
_benign_socket_log_lock = _split_source_symbol('_benign_socket_log_lock')
_benign_socket_log_state = _split_source_symbol('_benign_socket_log_state')
is_benign_socket_error = _split_source_symbol('is_benign_socket_error')
_socket_error_code = _split_source_symbol('_socket_error_code')
_log_benign_socket_error_limited = _split_source_symbol('_log_benign_socket_error_limited')
swallow_benign_socket_error = _split_source_symbol('swallow_benign_socket_error')
normalize_timeout_seconds = _split_source_symbol('normalize_timeout_seconds')
detect_local_lan_ip = _split_source_symbol('detect_local_lan_ip')
_LOCAL_LAN_IP_CACHE = _split_source_symbol('_LOCAL_LAN_IP_CACHE')
detect_local_lan_ip_cached = _split_source_symbol('detect_local_lan_ip_cached')
make_id = _split_source_symbol('make_id')
sanitize_profile_id = _split_source_symbol('sanitize_profile_id')
user_id_from_ip = _split_source_symbol('user_id_from_ip')
_meta_string_list = _split_source_symbol('_meta_string_list')
_module_exists = _split_source_symbol('_module_exists')
