# Auto-generated by split_coder.py — do not edit manually.
# Re-run split_coder.py to regenerate.

from __future__ import annotations
import argparse
import ast
import base64
from collections import Counter, defaultdict, deque
import concurrent.futures
import csv
import difflib
import errno
import html
import hashlib
import hmac
import io
import importlib.util
import json
import math
import multiprocessing
import mimetypes
import os
import queue
import re
import selectors
import signal
import shutil
import shlex
import socket
import subprocess
import sys
import threading
import time
import traceback
import uuid
import zipfile
import zlib
import xml.etree.ElementTree as ET
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path, PurePosixPath
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qs, unquote, urlparse
from urllib.request import Request, urlopen
try:
    import yaml as _yaml
except Exception:
    _yaml = None

MAX_TOOL_OUTPUT = 50_000

SOCKET_NOISE_LINE_PATTERNS = (
    re.compile(r"\bwinerror\s*10038\b", re.IGNORECASE),
    re.compile(r"\bwsaenotsock\b", re.IGNORECASE),
    re.compile(r"\bsocket\s+closed\s+benignly\b", re.IGNORECASE),
    re.compile(r"\bbenign\s+socket\s+error\b", re.IGNORECASE),
)

def filter_runtime_noise_lines(text: str) -> tuple[str, int]:
    raw = str(text or "")
    if not raw:
        return "", 0
    kept: list[str] = []
    dropped = 0
    for line in raw.splitlines():
        row = str(line or "")
        if any(p.search(row) for p in SOCKET_NOISE_LINE_PATTERNS):
            dropped += 1
            continue
        kept.append(row)
    return "\n".join(kept).strip(), int(dropped)

def trim(text: object, limit: int = MAX_TOOL_OUTPUT) -> str:
    s = str(text)
    return s if len(s) <= limit else s[:limit] + "\n...(truncated)"

def _fmt_export_ts(ts: float | int) -> str:
    v = float(ts or 0)
    if v <= 0:
        return ""
    try:
        from datetime import datetime
        return datetime.fromtimestamp(v).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return ""

def _html_esc(text: str) -> str:
    return html.escape(str(text or ""))

def _text_to_minimal_pdf(text: str) -> bytes:
    """纯 Python 最小 PDF 生成器，支持 CJK（中日韩）字符。"""
    raw = str(text or "")
    lines = raw.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    font_size = 9
    leading = font_size * 1.5
    margin_top, margin_bottom, margin_left, margin_right = 50, 50, 50, 50
    page_w, page_h = 595, 842  # A4

    def _has_cjk(s: str) -> bool:
        for ch in s:
            cp = ord(ch)
            if (0x2E80 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF
                    or 0xFE30 <= cp <= 0xFE4F or 0x20000 <= cp <= 0x2FA1F
                    or 0x3000 <= cp <= 0x30FF or 0x31F0 <= cp <= 0x31FF
                    or 0xFF00 <= cp <= 0xFFEF):
                return True
        return False

    has_cjk = _has_cjk(raw)

    # CJK chars are wider; adjust chars-per-line accordingly
    usable_w = page_w - margin_left - margin_right
    if has_cjk:
        max_chars_per_line = max(20, int(usable_w / (font_size * 0.55)))
    else:
        max_chars_per_line = max(20, int(usable_w / (font_size * 0.52)))
    usable_h = page_h - margin_top - margin_bottom
    lines_per_page = max(1, int(usable_h / leading))

    # 折行
    wrapped: list[str] = []
    for line in lines:
        if not line:
            wrapped.append("")
            continue
        while len(line) > max_chars_per_line:
            wrapped.append(line[:max_chars_per_line])
            line = line[max_chars_per_line:]
        wrapped.append(line)

    # 分页
    pages_list: list[list[str]] = []
    for i in range(0, len(wrapped), lines_per_page):
        pages_list.append(wrapped[i:i + lines_per_page])
    if not pages_list:
        pages_list = [[""]]

    def _pdf_escape_bytes(s: str) -> bytes:
        """Encode string to UTF-16BE hex for CJK-safe PDF text."""
        encoded = s.encode("utf-16-be")
        return b"<FEFF" + encoded.hex().upper().encode("ascii") + b">"

    def _pdf_escape_latin(s: str) -> str:
        safe = s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        return safe.encode("latin-1", errors="replace").decode("latin-1")

    objects: list[bytes] = []
    offsets: list[int] = []
    buf = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"

    def add_obj_bytes(content: bytes) -> int:
        nonlocal buf
        idx = len(objects) + 1
        offsets.append(len(buf))
        obj_bytes = f"{idx} 0 obj\n".encode("ascii") + content + b"\nendobj\n"
        buf += obj_bytes
        objects.append(obj_bytes)
        return idx

    def add_obj(content: str) -> int:
        return add_obj_bytes(content.encode("latin-1", errors="replace"))

    catalog_id = add_obj("<< /Type /Catalog /Pages 2 0 R >>")
    add_obj("PAGES_PLACEHOLDER")  # obj 2: replaced after page generation

    if has_cjk:
        # CIDFont for CJK support using Adobe-GB1 (Simplified Chinese) as primary
        # with fallback ordering — most PDF viewers can render CJK with this
        cid_font_id = add_obj(
            "<< /Type /Font /Subtype /Type0 /BaseFont /STSong-Light "
            "/Encoding /UniGB-UTF16-H "
            "/DescendantFonts [<< /Type /Font /Subtype /CIDFontType0 "
            "/BaseFont /STSong-Light "
            "/CIDSystemInfo << /Registry (Adobe) /Ordering (GB1) /Supplement 5 >> "
            "/DW 1000 >>] >>"
        )
        # Also add a latin fallback font for ASCII-heavy sections
        latin_font_id = add_obj("<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>")
    else:
        latin_font_id = add_obj("<< /Type /Font /Subtype /Type1 /BaseFont /Courier /Encoding /WinAnsiEncoding >>")
        cid_font_id = 0

    page_ids: list[int] = []
    for page_lines in pages_list:
        stream_parts: list[bytes] = []
        stream_parts.append(b"BT\n")
        y = page_h - margin_top
        stream_parts.append(f"{margin_left} {y} Td\n".encode("ascii"))
        for pl in page_lines:
            if has_cjk and _has_cjk(pl):
                stream_parts.append(f"/F1 {font_size} Tf\n".encode("ascii"))
                stream_parts.append(_pdf_escape_bytes(pl) + b" Tj\n")
            else:
                font_tag = "/F2" if has_cjk else "/F1"
                stream_parts.append(f"{font_tag} {font_size} Tf\n".encode("ascii"))
                safe = _pdf_escape_latin(pl)
                stream_parts.append(f"({safe}) Tj\n".encode("latin-1", errors="replace"))
            stream_parts.append(f"0 -{leading:.1f} Td\n".encode("ascii"))
        stream_parts.append(b"ET")
        stream_bytes = b"".join(stream_parts)
        content_id = add_obj_bytes(
            f"<< /Length {len(stream_bytes)} >>\nstream\n".encode("ascii")
            + stream_bytes
            + b"\nendstream"
        )
        if has_cjk:
            font_dict = f"/F1 {cid_font_id} 0 R /F2 {latin_font_id} 0 R"
        else:
            font_dict = f"/F1 {latin_font_id} 0 R"
        page_id = add_obj(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {page_w} {page_h}] "
            f"/Contents {content_id} 0 R /Resources << /Font << {font_dict} >> >> >>"
        )
        page_ids.append(page_id)

    kids = " ".join(f"{pid} 0 R" for pid in page_ids)
    pages_content = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_ids)} >>"
    pages_bytes = f"2 0 obj\n{pages_content}\nendobj\n".encode("latin-1")
    old_pages = objects[1]
    buf = buf.replace(b"2 0 obj\nPAGES_PLACEHOLDER\nendobj\n", pages_bytes)
    size_diff = len(pages_bytes) - len(old_pages)
    for i in range(2, len(offsets)):
        offsets[i] += size_diff

    xref_offset = len(buf)
    buf += b"xref\n"
    buf += f"0 {len(objects) + 1}\n".encode("ascii")
    buf += b"0000000000 65535 f \n"
    for off in offsets:
        buf += f"{off:010d} 00000 n \n".encode("ascii")
    buf += b"trailer\n"
    buf += f"<< /Size {len(objects) + 1} /Root {catalog_id} 0 R >>\n".encode("ascii")
    buf += b"startxref\n"
    buf += f"{xref_offset}\n".encode("ascii")
    buf += b"%%EOF\n"
    return buf

def normalize_work_text(text: object, status: str = "") -> str:
    s = re.sub(r"\s+", " ", str(text or "")).strip()
    if not s:
        return ""
    s = re.sub(r"^\[[ x>\-]\]\s*", "", s, flags=re.IGNORECASE)
    s = re.sub(
        r"^(pending|in[_\-\s]?progress|completed|done|blocked)\s*[·:\-\]]\s*",
        "",
        s,
        flags=re.IGNORECASE,
    )
    if status:
        status_pattern = re.escape(status).replace("_", r"[_\-\s]?")
        s = re.sub(
            rf"\s*[—-]\s*{status_pattern}\s*$",
            "",
            s,
            flags=re.IGNORECASE,
        )
    s = re.sub(
        r"\s*[—-]\s*(pending|in[_\-\s]?progress|completed|done|blocked)\s*$",
        "",
        s,
        flags=re.IGNORECASE,
    )
    return s.strip(" -")

def parse_front_matter(text: str) -> tuple[dict, str]:
    text = text or ""
    # Strip leading HTML/XML comments (kimi-agent-internals format)
    stripped = text
    while stripped.lstrip().startswith("<!--"):
        end_comment = stripped.find("-->")
        if end_comment < 0:
            break
        stripped = stripped[end_comment + 3:].lstrip()
    # Standard YAML frontmatter: ---\n...\n---\n
    if stripped.startswith("---\n"):
        end = stripped.find("\n---\n", 4)
        if end < 0:
            # Try alternate ending: \n--- followed by EOF or \n--\n
            end = stripped.find("\n---", 4)
            if end >= 0 and (end + 4 >= len(stripped) or stripped[end + 4] in ('\n', '\r', ' ')):
                raw_meta = stripped[4:end]
                body = stripped[end + 4:].strip()
            else:
                return {}, text.strip()
        else:
            raw_meta = stripped[4:end]
            body = stripped[end + 5:].strip()
    # Kimi xlsx format: no --- delimiters, but starts with "name:" and "description:"
    elif re.match(r'\s*name\s*:', stripped):
        # Find where the frontmatter-like section ends (blank line, markdown heading, XML tag, or bare --)
        lines = stripped.splitlines()
        meta_end = 0
        for i, line in enumerate(lines):
            s = line.strip()
            if s == "" or s.startswith("#") or s.startswith("<") or s in ("--", "---"):
                meta_end = i
                break
        else:
            meta_end = min(5, len(lines))
        raw_meta = "\n".join(lines[:meta_end])
        body = "\n".join(lines[meta_end:]).strip()
    else:
        return {}, text.strip()

    def _normalize_front_matter_value(value: object):
        if isinstance(value, dict):
            out: dict[str, object] = {}
            for key, row in value.items():
                out[str(key)] = _normalize_front_matter_value(row)
            return out
        if isinstance(value, list):
            return [_normalize_front_matter_value(x) for x in value]
        if value is None or isinstance(value, (str, int, float, bool)):
            return value
        return str(value)

    def _parse_scalar(raw: str):
        txt = str(raw or "").strip()
        if not txt:
            return ""
        if len(txt) >= 2 and txt[0] == txt[-1] and txt[0] in {"'", '"'}:
            return txt[1:-1]
        low = txt.lower()
        if low == "true":
            return True
        if low == "false":
            return False
        if low in {"null", "none"}:
            return ""
        if re.fullmatch(r"-?\d+", txt):
            try:
                return int(txt)
            except Exception:
                return txt
        if re.fullmatch(r"-?\d+\.\d+", txt):
            try:
                return float(txt)
            except Exception:
                return txt
        return txt

    def _parse_simple_yaml_block(raw: str) -> dict:
        lines = str(raw or "").splitlines()

        def _indent_of(line: str) -> int:
            return len(line) - len(line.lstrip(" "))

        def _next_significant(start: int):
            j = start
            while j < len(lines):
                if lines[j].strip():
                    return j
                j += 1
            return len(lines)

        def _parse_block(start: int, indent: int):
            j = _next_significant(start)
            if j >= len(lines):
                return {}, j
            stripped = lines[j].strip()
            is_list = stripped.startswith("- ")
            if is_list:
                items: list[object] = []
                i = j
                while i < len(lines):
                    if not lines[i].strip():
                        i += 1
                        continue
                    cur_indent = _indent_of(lines[i])
                    if cur_indent < indent:
                        break
                    if cur_indent != indent or not lines[i].lstrip().startswith("- "):
                        break
                    item_txt = lines[i].lstrip()[2:].strip()
                    i += 1
                    if not item_txt:
                        nested, i = _parse_block(i, indent + 2)
                        items.append(nested)
                        continue
                    if item_txt.endswith(":") and ":" not in item_txt[:-1]:
                        nested, i = _parse_block(i, indent + 2)
                        items.append({item_txt[:-1].strip(): nested})
                        continue
                    if ":" in item_txt and not item_txt.startswith(("'", '"')):
                        key, rest = item_txt.split(":", 1)
                        rest = rest.strip()
                        if rest:
                            items.append({key.strip(): _parse_scalar(rest)})
                            continue
                        nested, i = _parse_block(i, indent + 2)
                        items.append({key.strip(): nested})
                        continue
                    items.append(_parse_scalar(item_txt))
                return items, i

            obj: dict[str, object] = {}
            i = j
            while i < len(lines):
                if not lines[i].strip():
                    i += 1
                    continue
                cur_indent = _indent_of(lines[i])
                if cur_indent < indent:
                    break
                if cur_indent != indent:
                    break
                stripped_line = lines[i].strip()
                if ":" not in stripped_line:
                    i += 1
                    continue
                key, rest = stripped_line.split(":", 1)
                key = key.strip()
                rest = rest.strip()
                i += 1
                if rest in {"|", ">"}:
                    block_lines: list[str] = []
                    while i < len(lines):
                        if not lines[i].strip():
                            block_lines.append("")
                            i += 1
                            continue
                        next_indent = _indent_of(lines[i])
                        if next_indent <= cur_indent:
                            break
                        block_lines.append(lines[i][cur_indent + 2 :] if len(lines[i]) >= cur_indent + 2 else "")
                        i += 1
                    if rest == ">":
                        folded = " ".join(x.strip() for x in block_lines if x.strip())
                        obj[key] = folded.strip()
                    else:
                        obj[key] = "\n".join(block_lines).strip()
                    continue
                if rest:
                    obj[key] = _parse_scalar(rest)
                    continue
                nested, i = _parse_block(i, cur_indent + 2)
                obj[key] = nested
            return obj, i

        parsed, _ = _parse_block(0, 0)
        return parsed if isinstance(parsed, dict) else {}

    if _yaml is not None:
        try:
            parsed = _yaml.safe_load(raw_meta)
            if isinstance(parsed, dict):
                return _normalize_front_matter_value(parsed), body
        except Exception:
            pass

    meta = _parse_simple_yaml_block(raw_meta)
    return _normalize_front_matter_value(meta), body

def make_unified_diff(path: str, old_text: str, new_text: str, max_lines: int = 400) -> tuple[str, int, int]:
    old_lines = old_text.splitlines()
    new_lines = new_text.splitlines()
    diff = list(
        difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=f"a/{path}",
            tofile=f"b/{path}",
            lineterm="",
        )
    )
    added = sum(1 for ln in diff if ln.startswith("+") and not ln.startswith("+++"))
    deleted = sum(1 for ln in diff if ln.startswith("-") and not ln.startswith("---"))
    if max_lines and len(diff) > max_lines:
        diff = diff[:max_lines] + [f"... diff truncated, total lines={len(diff)}"]
    text = "\n".join(diff) if diff else f"@@ no textual diff for {path}"
    return text, added, deleted

def _skip_row(text: str) -> dict:
    msg = str(text or "").strip() or "⋮"
    if not msg.startswith("⋮"):
        msg = f"⋮ {msg}"
    return {"kind": "skip", "sign": "⋮", "old_line": None, "new_line": None, "text": msg}

def _row_is_hot(row: dict) -> bool:
    return str((row or {}).get("kind", "")).strip().lower() in {"add", "delete"}

def _hotspot_index(rows: list[dict]) -> int:
    arr = [dict(x) for x in (rows or [])]
    if not arr:
        return 0
    hot = [1 if _row_is_hot(row) else 0 for row in arr]
    if not any(hot):
        return max(0, len(arr) - 1)
    prefix = [0]
    for v in hot:
        prefix.append(prefix[-1] + v)
    n = len(arr)
    radius = max(10, min(180, n // 18))
    best_idx = 0
    best_score = -1
    for i in range(n):
        a = max(0, i - radius)
        b = min(n - 1, i + radius)
        score = prefix[b + 1] - prefix[a]
        if score > best_score or (score == best_score and i > best_idx):
            best_idx = i
            best_score = score
    return best_idx

def _compress_rows_keep_hotspot(
    rows: list[dict],
    max_rows: int,
    *,
    prefix_omitted: int = 0,
) -> tuple[list[dict], bool]:
    arr = [dict(x) for x in (rows or [])]
    limit = max(1, int(max_rows or 1))
    omitted_prefix_base = max(0, int(prefix_omitted or 0))
    if not arr:
        if omitted_prefix_base <= 0:
            return [], False
        return [_skip_row(f"⋮ ... ({omitted_prefix_base} rows omitted)")], True
    anchor = _hotspot_index(arr)
    n = len(arr)
    slots = (1 if omitted_prefix_base > 0 else 0) + 1
    slots = min(limit - 1, max(0, slots))
    start = 0
    end = n
    for _ in range(3):
        budget = max(1, limit - slots)
        if budget >= n:
            start, end = 0, n
        else:
            start = max(0, anchor - (budget // 2))
            if start + budget > n:
                start = max(0, n - budget)
            end = min(n, start + budget)
        omitted_prefix = omitted_prefix_base + start
        omitted_suffix = max(0, n - end)
        new_slots = (1 if omitted_prefix > 0 else 0) + (1 if omitted_suffix > 0 else 0)
        new_slots = min(limit - 1, max(0, new_slots))
        if new_slots == slots:
            break
        slots = new_slots
    omitted_prefix = omitted_prefix_base + start
    omitted_suffix = max(0, n - end)
    out: list[dict] = []
    if omitted_prefix > 0:
        out.append(_skip_row(f"⋮ ... ({omitted_prefix} rows omitted)"))
    out.extend(arr[start:end])
    if omitted_suffix > 0:
        out.append(_skip_row(f"⋮ ... ({omitted_suffix} rows omitted)"))
    truncated = omitted_prefix > 0 or omitted_suffix > 0
    if len(out) > limit:
        out = out[:limit]
        truncated = True
    return out, truncated

def make_numbered_diff(old_text: str, new_text: str, max_lines: int = 320) -> list[dict]:
    old_lines = old_text.splitlines()
    new_lines = new_text.splitlines()
    sm = difflib.SequenceMatcher(a=old_lines, b=new_lines)
    entries: list[dict] = []
    max_lines = max(16, int(max_lines or 320))
    # Keep bounded memory on huge files while preserving latest/hot rows.
    buffer_cap = max(max_lines + 256, min(6_000, max_lines * 6))
    dropped_head = 0

    def _push(row: dict):
        nonlocal dropped_head
        entries.append(row)
        if len(entries) <= buffer_cap:
            return
        drop = len(entries) - buffer_cap
        del entries[:drop]
        dropped_head += drop

    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            for off in range(i2 - i1):
                _push(
                    {
                        "kind": "context",
                        "sign": " ",
                        "old_line": i1 + off + 1,
                        "new_line": j1 + off + 1,
                        "old_col": 1,
                        "new_col": 1,
                        "text": old_lines[i1 + off],
                    }
                )
        elif tag == "delete":
            for idx in range(i1, i2):
                _push(
                    {
                        "kind": "delete",
                        "sign": "-",
                        "old_line": idx + 1,
                        "new_line": None,
                        "old_col": 1,
                        "new_col": None,
                        "text": old_lines[idx],
                    }
                )
        elif tag == "insert":
            for idx in range(j1, j2):
                _push(
                    {
                        "kind": "add",
                        "sign": "+",
                        "old_line": None,
                        "new_line": idx + 1,
                        "old_col": None,
                        "new_col": 1,
                        "text": new_lines[idx],
                    }
                )
        elif tag == "replace":
            for idx in range(i1, i2):
                _push(
                    {
                        "kind": "delete",
                        "sign": "-",
                        "old_line": idx + 1,
                        "new_line": None,
                        "old_col": 1,
                        "new_col": None,
                        "text": old_lines[idx],
                    }
                )
            for idx in range(j1, j2):
                _push(
                    {
                        "kind": "add",
                        "sign": "+",
                        "old_line": None,
                        "new_line": idx + 1,
                        "old_col": None,
                        "new_col": 1,
                        "text": new_lines[idx],
                    }
                )
    out, _ = _compress_rows_keep_hotspot(entries, max_lines, prefix_omitted=dropped_head)
    return out

def render_numbered_diff_text(entries: list[dict]) -> str:
    out = []
    for row in entries:
        if row.get("kind") == "skip":
            out.append(f"    {str(row.get('text') or '⋮').strip()}")
            continue
        old_ln = row.get("old_line")
        new_ln = row.get("new_line")
        ln = old_ln if old_ln is not None else new_ln
        sign = row.get("sign", " ")
        text = row.get("text", "")
        out.append(f"{str(ln or ''):>6} {sign} {text}")
    return "\n".join(out)

