# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.

from __future__ import annotations

# split-source: order=868 original-lines=100649-100832 hash=168fd81e5ca31b72

class RagAdminHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    server_version = f"StandaloneWebRAG/{APP_VERSION}"

    def log_message(self, fmt: str, *args):
        return

    def parse_request(self):
        self._clouds_request_body_consumed = False
        return super().parse_request()

    def handle(self):
        try:
            super().handle()
        except Exception as exc:
            if swallow_benign_socket_error(exc, "rag-handler.handle"):
                return
            raise

    @property
    def app(self) -> AppContext:
        return self.server.app  # type: ignore[attr-defined]

    def _client_ip(self) -> str:
        return trusted_client_ip(self)

    def _user_id(self) -> str:
        return user_id_from_ip(self._client_ip())

    def _read_json(self) -> dict:
        return read_http_json_body(self)

    def _require_admin_write(self) -> bool:
        auth = str(self.headers.get("Authorization", "") or "").strip()
        token = auth[7:].strip() if auth.lower().startswith("bearer ") else str(self.headers.get("X-Admin-Token", "") or "").strip()
        origin = str(self.headers.get("Origin", "") or "").strip()
        parsed = urlparse(origin)
        same_origin = not origin or (parsed.scheme in {"http", "https"} and parsed.netloc == str(self.headers.get("Host", "") or ""))
        if self.app.verify_admin_token(token) and same_origin:
            return True
        self._send_json({"error": "admin authentication and same-origin request required"}, status=401)
        return False

    def _send_json(self, obj: object, status: int = 200):
        body = json_response_bytes(obj)
        try:
            self.send_response(status)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            if close_if_http_request_body_unread(self):
                self.send_header("Connection", "close")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "rag-handler.send_json"):
                return
            raise

    def _send_text(self, text: str, content_type: str = "text/plain; charset=utf-8", status: int = 200):
        body = safe_utf8_bytes(text)
        try:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            if close_if_http_request_body_unread(self):
                self.send_header("Connection", "close")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "rag-handler.send_text"):
                return
            raise

    def _send_inline_bytes(self, data: bytes, content_type: str, status: int = 200):
        try:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(data)))
            self.send_header("Content-Disposition", "inline")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(data)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "rag-handler.send_inline_bytes"):
                return
            raise

    def do_GET(self):
        parsed = urlparse(self.path)
        path = unquote(parsed.path)
        query = parse_qs(parsed.query or "")
        if path == "/":
            return self._send_text(self.app.web_ui_rag_admin_index_html(), "text/html; charset=utf-8")
        if path == "/assets/style.css":
            return self._send_text(self.app.web_ui_rag_admin_style_css(), "text/css; charset=utf-8")
        if path == "/assets/rag-admin.js":
            return self._send_text(self.app.web_ui_rag_admin_js(), "application/javascript; charset=utf-8")
        if path.startswith("/assets/js_lib/"):
            asset_ref = path[len("/assets/js_lib/"):]
            fp = self.app.rag_js_lib_asset_path(asset_ref)
            if not fp:
                return self._send_json({"error": "asset not found"}, status=404)
            try:
                data = fp.read_bytes()
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=500)
            content_type = guess_mime_from_name(fp.name, "application/javascript")
            if fp.suffix.lower() in {".js", ".mjs", ".cjs"}:
                content_type = "application/javascript; charset=utf-8"
            return self._send_inline_bytes(data, content_type)
        if path == "/api/health":
            return self._send_json({"ok": True, "app": "rag-admin", "version": APP_VERSION})
        if path == "/api/rag/config":
            return self._send_json(self.app.rag_config(self._user_id()))
        if path == "/api/rag/library":
            try:
                limit = int((query.get("limit", ["-1"]) or ["-1"])[0] or -1)
            except Exception:
                limit = -1
            try:
                offset = int((query.get("offset", ["0"]) or ["0"])[0] or 0)
            except Exception:
                offset = 0
            return self._send_json(self.app.rag_library_payload(limit=limit, offset=offset))
        if path == "/api/rag/tasks":
            try:
                limit = int((query.get("limit", ["80"]) or ["80"])[0] or 80)
            except Exception:
                limit = 80
            return self._send_json(self.app.rag_tasks_payload(limit=limit))
        if path == "/api/rag/graph":
            try:
                max_nodes = int((query.get("max_nodes", [str(RAG_GRAPH_MAX_NODES)]) or [str(RAG_GRAPH_MAX_NODES)])[0] or RAG_GRAPH_MAX_NODES)
            except Exception:
                max_nodes = RAG_GRAPH_MAX_NODES
            return self._send_json(self.app.rag_graph_payload(max_nodes=max_nodes))
        if path == "/api/rag/filesystem":
            try:
                max_nodes = int((query.get("max_nodes", ["320"]) or ["320"])[0] or 320)
            except Exception:
                max_nodes = 320
            return self._send_json(self.app.rag_filesystem_payload(max_nodes=max_nodes))
        if path == "/api/rag/wiki":
            try:
                limit = int((query.get("limit", ["240"]) or ["240"])[0] or 240)
            except Exception:
                limit = 240
            return self._send_json(self.app.rag_wiki_payload(limit=limit))
        if path == "/api/rag/wiki/lint":
            return self._send_json(self.app.rag_wiki_lint())
        return self._send_json({"error": "not found"}, status=404)

    def do_POST(self):
        path = unquote(urlparse(self.path).path)
        if not self._require_admin_write():
            return
        if path == "/api/rag/import":
            try:
                out = self.app.rag_import_request(self._user_id(), self._read_json())
                return self._send_json(out, status=201)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/rag/query":
            try:
                out = self.app.rag_query(self._user_id(), self._read_json())
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/rag/rebuild":
            try:
                out = self.app.rag_rebuild()
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/rag/wiki/rebuild":
            try:
                out = self.app.rag_wiki.compile_from_store(self.app.rag_store, reason="manual-wiki-rebuild")
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        return self._send_json({"error": "not found"}, status=404)

# split-source: order=869 original-lines=100833-101035 hash=5e3a9bc915382a71


class CodeAdminHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    server_version = f"StandaloneWebCode/{APP_VERSION}"

    def log_message(self, fmt: str, *args):
        return

    def parse_request(self):
        self._clouds_request_body_consumed = False
        return super().parse_request()

    def handle(self):
        try:
            super().handle()
        except Exception as exc:
            if swallow_benign_socket_error(exc, "code-handler.handle"):
                return
            raise

    @property
    def app(self) -> AppContext:
        return self.server.app  # type: ignore[attr-defined]

    def _client_ip(self) -> str:
        return trusted_client_ip(self)

    def _user_id(self) -> str:
        return user_id_from_ip(self._client_ip())

    def _read_json(self) -> dict:
        return read_http_json_body(self)

    def _require_admin_write(self) -> bool:
        auth = str(self.headers.get("Authorization", "") or "").strip()
        token = auth[7:].strip() if auth.lower().startswith("bearer ") else str(self.headers.get("X-Admin-Token", "") or "").strip()
        origin = str(self.headers.get("Origin", "") or "").strip()
        parsed = urlparse(origin)
        same_origin = not origin or (parsed.scheme in {"http", "https"} and parsed.netloc == str(self.headers.get("Host", "") or ""))
        if self.app.verify_admin_token(token) and same_origin:
            return True
        self._send_json({"error": "admin authentication and same-origin request required"}, status=401)
        return False

    def _send_json(self, obj: object, status: int = 200):
        body = json_response_bytes(obj)
        try:
            self.send_response(status)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            if close_if_http_request_body_unread(self):
                self.send_header("Connection", "close")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "code-handler.send_json"):
                return
            raise

    def _send_text(self, text: str, content_type: str = "text/plain; charset=utf-8", status: int = 200):
        body = safe_utf8_bytes(text)
        try:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            if close_if_http_request_body_unread(self):
                self.send_header("Connection", "close")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "code-handler.send_text"):
                return
            raise

    def _send_inline_bytes(self, data: bytes, content_type: str, status: int = 200):
        try:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(data)))
            self.send_header("Content-Disposition", "inline")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(data)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "code-handler.send_inline_bytes"):
                return
            raise

    def do_GET(self):
        parsed = urlparse(self.path)
        path = unquote(parsed.path)
        query = parse_qs(parsed.query or "")
        if path == "/":
            return self._send_text(self.app.web_ui_code_admin_index_html(), "text/html; charset=utf-8")
        if path == "/assets/style.css":
            return self._send_text(self.app.web_ui_code_admin_style_css(), "text/css; charset=utf-8")
        if path == "/assets/code-admin.js":
            return self._send_text(self.app.web_ui_code_admin_js(), "application/javascript; charset=utf-8")
        if path.startswith("/assets/js_lib/"):
            asset_ref = path[len("/assets/js_lib/"):]
            fp = self.app.rag_js_lib_asset_path(asset_ref)
            if not fp:
                return self._send_json({"error": "asset not found"}, status=404)
            try:
                data = fp.read_bytes()
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=500)
            content_type = guess_mime_from_name(fp.name, "application/javascript")
            if fp.suffix.lower() in {".js", ".mjs", ".cjs"}:
                content_type = "application/javascript; charset=utf-8"
            return self._send_inline_bytes(data, content_type)
        if path == "/api/health":
            return self._send_json({"ok": True, "app": "code-admin", "version": APP_VERSION})
        if path == "/api/code/config":
            return self._send_json(self.app.code_config(self._user_id()))
        if path == "/api/code/library":
            try:
                limit = int((query.get("limit", ["-1"]) or ["-1"])[0] or -1)
            except Exception:
                limit = -1
            try:
                offset = int((query.get("offset", ["0"]) or ["0"])[0] or 0)
            except Exception:
                offset = 0
            return self._send_json(self.app.code_library_payload(limit=limit, offset=offset))
        if path == "/api/code/tasks":
            try:
                limit = int((query.get("limit", ["80"]) or ["80"])[0] or 80)
            except Exception:
                limit = 80
            return self._send_json(self.app.code_tasks_payload(limit=limit))
        if path == "/api/code/graph":
            try:
                max_nodes = int((query.get("max_nodes", [str(RAG_GRAPH_MAX_NODES)]) or [str(RAG_GRAPH_MAX_NODES)])[0] or RAG_GRAPH_MAX_NODES)
            except Exception:
                max_nodes = RAG_GRAPH_MAX_NODES
            return self._send_json(self.app.code_graph_payload(max_nodes=max_nodes))
        if path == "/api/code/filesystem":
            try:
                max_nodes = int((query.get("max_nodes", ["320"]) or ["320"])[0] or 320)
            except Exception:
                max_nodes = 320
            return self._send_json(self.app.code_filesystem_payload(max_nodes=max_nodes))
        if path == "/api/code/wiki":
            try:
                limit = int((query.get("limit", ["240"]) or ["240"])[0] or 240)
            except Exception:
                limit = 240
            return self._send_json(self.app.code_wiki_payload(limit=limit))
        if path == "/api/code/wiki/lint":
            return self._send_json(self.app.code_wiki_lint())
        if path == "/api/code/workflows":
            try:
                limit = int((query.get("limit", ["120"]) or ["120"])[0] or 120)
            except Exception:
                limit = 120
            return self._send_json(self.app.code_workflows_payload(limit=limit))
        return self._send_json({"error": "not found"}, status=404)

    def do_POST(self):
        path = unquote(urlparse(self.path).path)
        if not self._require_admin_write():
            return
        if path == "/api/code/import":
            try:
                out = self.app.code_import_request(self._user_id(), self._read_json())
                return self._send_json(out, status=201)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/code/query":
            try:
                out = self.app.code_query(self._user_id(), self._read_json())
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/code/rebuild":
            try:
                out = self.app.code_rebuild()
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/code/wiki/rebuild":
            try:
                out = self.app.code_wiki.compile_from_store(self.app.code_store, reason="manual-wiki-rebuild")
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/code/workflows/query":
            try:
                out = self.app.code_workflows_query(self._read_json())
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        if path == "/api/code/workflows/rebuild":
            try:
                out = self.app.workflow_memory.rebuild()
                return self._send_json(out)
            except Exception as exc:
                return self._send_json({"error": str(exc)}, status=400)
        return self._send_json({"error": "not found"}, status=404)
