# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=112 original-lines=235-235 hash=d2766984060631d7
MCP_SERVICE_PORT_OFFSET = 4

# split-source: order=818 original-lines=16769-16798 hash=637b2ed2c7e80e0c


# ----------------------------------------------------------------------------
# MCP (Model Context Protocol) — full stdio JSON-RPC client driver.
#
# Why this exists / how it relates to the rest of the system:
#   The reference tutorials (learn-claude-code-main s19/s20) only *mock* MCP —
#   in-process Python lambdas, no subprocess, no JSON-RPC. This is the real
#   thing: it spawns each declared server as a child process and speaks
#   newline-delimited JSON-RPC 2.0 over its stdin/stdout (the stdio transport
#   used by Claude Code, Codex, and OpenCode). Discovered tools are surfaced to
#   the model under the canonical `mcp__<server>__<tool>` name so they are
#   visible and callable *identically* to built-in tools, in every mode:
#   single/multi-agent, plan/no-plan, every role. The manager is the only place
#   that knows a tool came from an external process — dispatch, allowlists, the
#   blackboard, and the WebUI treat it like any other tool.
#
# Config compatibility (strong cross-tool compat — the user's explicit ask):
#   Three ecosystems write MCP server declarations slightly differently. We
#   normalize all of them into one internal record {command,args,env,cwd,...}:
#     * Claude Code / Codex (.mcp.json, claude_desktop_config.json):
#         {"mcpServers": {"name": {"command","args","env"}}}
#     * OpenCode (opencode.json):
#         {"mcp": {"name": {"type":"local","command":[argv...],"environment":{}}}}
#         (also accepts {"type":"remote","url"} which we record but mark
#          unsupported-transport rather than crash)
#   `disabled`/`enabled` flags from any dialect are honored.
# ----------------------------------------------------------------------------

MCP_PROTOCOL_VERSION = "2025-06-18"

# split-source: order=819 original-lines=16799-16799 hash=8952944d0fe9c8fd
MCP_NAME_RE = re.compile(r"[^a-zA-Z0-9_-]")

# split-source: order=820 original-lines=16800-16800 hash=d98dc1d8bc8c35e0
MCP_TOOL_PREFIX = "mcp__"

# split-source: order=821 original-lines=16801-16801 hash=f05e95f5608e9db3
_MCP_DEFAULT_HANDSHAKE_TIMEOUT = 20.0

# split-source: order=822 original-lines=16802-16802 hash=2cfd699f97d758a8
_MCP_DEFAULT_CALL_TIMEOUT = 60.0

# split-source: order=823 original-lines=16803-16803 hash=97320939011d5517
_MCP_MAX_RESULT_CHARS = 24000

# split-source: order=824 original-lines=16804-16804 hash=d3f40a4f9ffb843b
_MCP_TRUST_STORE_VERSION = 1
