# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=966 original-lines=110220-110436 hash=113b4291bf0a35b1

class McpServiceHandler(BaseHTTPRequestHandler):
    """HTTP control/health surface for the global MCP manager (ide_port+1).

    Read endpoints (GET): / (status HTML), /mcp/health, /mcp/tools, /mcp/status.
    Admin endpoints expose pending workspace-command approvals and accept an
    explicit approve/revoke decision bound to the displayed config digest and
    effective-command fingerprint. Reload, restart and crash recovery all pass
    through the same pre-spawn authorization gate.
    """
    protocol_version = "HTTP/1.1"
    server_version = f"CloudsCoderMCP/{APP_VERSION}"

    def log_message(self, fmt: str, *args):
        return

    def parse_request(self):
        self._clouds_request_body_consumed = False
        return super().parse_request()

    def handle(self):
        try:
            super().handle()
        except Exception as exc:
            if swallow_benign_socket_error(exc, "mcp-handler.handle"):
                return
            raise

    @property
    def app(self) -> AppContext:
        return self.server.app  # type: ignore[attr-defined]

    def _mgr(self):
        return getattr(self.app, "mcp", None)

    def _read_json(self) -> dict:
        return read_http_json_body(self)

    def _require_admin_write(self) -> bool:
        auth = str(self.headers.get("Authorization", "") or "").strip()
        token = auth[7:].strip() if auth.lower().startswith("bearer ") else str(self.headers.get("X-Admin-Token", "") or "").strip()
        origin = str(self.headers.get("Origin", "") or "").strip()
        parsed = urlparse(origin)
        same_origin = not origin or (parsed.scheme in {"http", "https"} and parsed.netloc == str(self.headers.get("Host", "") or ""))
        if self.app.verify_admin_token(token) and same_origin:
            return True
        self._send_json({"error": "admin authentication and same-origin request required"}, status=401)
        return False

    def _send_json(self, obj: object, status: int = 200):
        body = json_response_bytes(obj)
        try:
            self.send_response(status)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            if close_if_http_request_body_unread(self):
                self.send_header("Connection", "close")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "mcp-handler.send_json"):
                return
            raise

    def _send_html(self, text: str, status: int = 200):
        body = safe_utf8_bytes(text)
        try:
            self.send_response(status)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
        except Exception as exc:
            if swallow_benign_socket_error(exc, "mcp-handler.send_html"):
                return
            raise

    def _status_html(self) -> str:
        mgr = self._mgr()
        h = mgr.health() if mgr is not None else {"ready": 0, "total": 0, "servers": [], "tool_count": 0}
        rows = []
        for s in h.get("servers", []):
            tools = ", ".join(s.get("tools", []) or []) or "—"
            rows.append(
                f"<tr><td>{html.escape(str(s.get('name','')))}</td>"
                f"<td>{html.escape(str(s.get('state','')))}</td>"
                f"<td>{'yes' if s.get('alive') else 'no'}</td>"
                f"<td>{html.escape(tools)}</td>"
                f"<td>{html.escape(str(s.get('error','') or ''))}</td></tr>"
            )
        body = "".join(rows) or '<tr><td colspan="5">no MCP servers configured</td></tr>'
        return (
            "<!doctype html><html><head><meta charset='utf-8'><title>MCP Service</title>"
            "<style>body{font:14px system-ui;margin:24px;background:#0b0e14;color:#cdd6f4}"
            "table{border-collapse:collapse;width:100%}td,th{border:1px solid #313244;padding:6px 10px;text-align:left}"
            "th{background:#181825}code{color:#89b4fa}input,button{font:inherit;padding:6px 9px;margin:4px 4px 4px 0}"
            "button{cursor:pointer}article{border:1px solid #313244;padding:10px;margin:10px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}"
            ".ok{color:#a6e3a1}.warn{color:#f9e2af}.err{color:#f38ba8}</style></head><body>"
            f"<h2>Clouds_Coder MCP Service</h2>"
            f"<p>ready <b>{h.get('ready',0)}/{h.get('total',0)}</b> · tools <b>{h.get('tool_count',0)}</b> · "
            f"monitor {'on' if h.get('monitor') else 'off'}</p>"
            "<table><tr><th>server</th><th>state</th><th>alive</th><th>tools</th><th>error</th></tr>"
            f"{body}</table>"
            "<h3>Workspace command approvals</h3>"
            "<p>Review the exact resolved command before allowing a workspace MCP declaration to run.</p>"
            "<label>Admin token <input id='admin-token' type='password' autocomplete='off'></label>"
            "<button id='review-approvals' type='button'>Review approvals</button>"
            "<div id='approval-error' class='err' role='alert'></div><div id='approval-list'></div>"
            "<p style='color:#6c7086'>GET /mcp/health · /mcp/tools · /mcp/status — "
            "POST /mcp/trust · /mcp/reload · /mcp/restart · /mcp/call</p>"
            "<script>"
            "const token=()=>document.getElementById('admin-token').value.trim();"
            "async function api(path,options={}){const headers=Object.assign({'X-Admin-Token':token()},options.headers||{});"
            "if(options.body)headers['Content-Type']='application/json';const response=await fetch(path,Object.assign({},options,{headers}));"
            "const data=await response.json();if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}"
            "function addLine(pre,label,value){pre.textContent+=label+': '+value+'\\n';}"
            "async function loadApprovals(){const error=document.getElementById('approval-error'),host=document.getElementById('approval-list');"
            "error.textContent='';host.replaceChildren();try{const data=await api('/mcp/approvals');"
            "for(const row of data.approvals||[]){const card=document.createElement('article'),title=document.createElement('strong');"
            "title.textContent=row.server+' - '+(row.approved?'approved':'approval required');title.className=row.approved?'ok':'warn';"
            "const pre=document.createElement('pre');addLine(pre,'Command',[row.resolved_command||row.command,...(row.args||[])].join(' '));"
            "addLine(pre,'Working directory',row.cwd||'-');addLine(pre,'Environment keys',(row.env_keys||[]).join(', ')||'-');"
            "addLine(pre,'Config digest',row.config_digest||'-');addLine(pre,'Command fingerprint',row.fingerprint||'-');"
            "for(const file of row.referenced_files||[])addLine(pre,'Referenced file',file.path+' sha256='+file.sha256);"
            "addLine(pre,'Decision',row.reason||'-');const button=document.createElement('button');button.type='button';"
            "button.textContent=row.approved?'Revoke':'Approve exact command';button.onclick=async()=>{button.disabled=true;try{"
            "await api('/mcp/trust',{method:'POST',body:JSON.stringify({server:row.server,decision:row.approved?'revoke':'approve',"
            "config_digest:row.config_digest,fingerprint:row.fingerprint})});await loadApprovals();}catch(err){error.textContent=err.message;}finally{button.disabled=false;}};"
            "card.append(title,pre,button);host.append(card);}}catch(err){error.textContent=err.message;}}"
            "document.getElementById('review-approvals').addEventListener('click',loadApprovals);"
            "</script>"
            "</body></html>"
        )

    def do_GET(self):
        path = unquote(urlparse(self.path).path)
        mgr = self._mgr()
        if path in ("/", "/mcp", "/mcp/"):
            return self._send_html(self._status_html())
        if mgr is None:
            return self._send_json({"error": "mcp manager unavailable"}, status=503)
        if path == "/mcp/health":
            return self._send_json(mgr.health())
        if path == "/mcp/tools":
            specs = mgr.tool_specs()
            return self._send_json({
                "count": len(specs),
                "names": sorted(mgr.tool_names()),
                "tools": specs,
            })
        if path == "/mcp/status":
            return self._send_json({"servers": mgr.status()})
        if path == "/mcp/approvals":
            if not self._require_admin_write():
                return
            return self._send_json({
                "workspace": str(getattr(mgr, "_workspace", "") or ""),
                "config_path": str(getattr(mgr, "_config_path", "") or ""),
                "approvals": mgr.approval_requests(),
            })
        return self._send_json({"error": "not found"}, status=404)

    def do_POST(self):
        path = unquote(urlparse(self.path).path)
        if not self._require_admin_write():
            return
        mgr = self._mgr()
        if mgr is None:
            return self._send_json({"error": "mcp manager unavailable"}, status=503)
        try:
            payload = self._read_json()
        except Exception as exc:
            return self._send_json({"error": f"bad json: {exc}"}, status=400)
        if path == "/mcp/reload":
            # Inline process specs are never accepted. Workspace declarations
            # still require a matching user-private approval before spawn.
            cfg_path = getattr(mgr, "_config_path", "") or ""
            cfg = {}
            if cfg_path:
                cfg = parse_json_object(try_read_text(Path(cfg_path))) or {}
            diff = mgr.reload_from_config(cfg)
            mgr.note_config_loaded()
            return self._send_json(diff)
        if path == "/mcp/trust":
            server = str(payload.get("server", "") or "").strip()
            decision = str(payload.get("decision", "approve") or "approve").strip().lower()
            if not server:
                return self._send_json({"error": "server is required"}, status=400)
            if decision == "approve":
                result = mgr.approve_server(
                    server,
                    expected_config_digest=str(payload.get("config_digest", "") or ""),
                    expected_fingerprint=str(payload.get("fingerprint", "") or ""),
                )
            elif decision == "revoke":
                result = mgr.revoke_server_approval(server)
            else:
                return self._send_json({"error": "decision must be approve or revoke"}, status=400)
            return self._send_json(result, status=200 if result.get("ok") else 409)
        if path == "/mcp/restart":
            server = str(payload.get("server", "") or "").strip()
            if not server:
                return self._send_json({"error": "server is required"}, status=400)
            ok = mgr.restart_server(server)
            return self._send_json({"ok": bool(ok), "server": server})
        if path == "/mcp/call":
            name = str(payload.get("name", "") or "").strip()
            args = payload.get("arguments", {})
            if not name:
                return self._send_json({"error": "name is required"}, status=400)
            if not mgr.is_mcp_tool(name):
                return self._send_json({"error": f"unknown mcp tool '{name}'"}, status=404)
            out = mgr.call(name, args if isinstance(args, dict) else {})
            return self._send_json({"name": name, "result": out, "ok": not str(out).startswith("Error:")})
        return self._send_json({"error": "not found"}, status=404)
