# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=735 original-lines=8787-8794 hash=7405d447cbf41aba


class IDEAuthError(Exception):
    def __init__(self, code: str, message: str, status: int = 400, *, retry_after: int = 0):
        super().__init__(message)
        self.code = str(code or "ide_auth_error")
        self.status = int(status or 400)
        self.retry_after = max(0, int(retry_after or 0))

# split-source: order=736 original-lines=8795-9495 hash=219ecb95289d2b0b


class IDEAuthStore:
    """Account and browser-session store for the programming IDE.

    IDE identities are deliberately independent from source IP addresses. The
    client address remains a capability signal (local mount/process access), not
    an authentication credential.
    """

    _USERNAME_RE = re.compile(r"^[A-Za-z0-9._-]{3,64}$")

    def __init__(self, path: Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.lock = threading.RLock()
        self.password_slots = threading.BoundedSemaphore(3)
        self.login_failures: dict[tuple[str, str], deque[float]] = {}
        self._initialize()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(str(self.path), timeout=10.0, isolation_level=None)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA busy_timeout=10000")
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=FULL")
        return conn

    def _initialize(self) -> None:
        with self._connect() as conn:
            conn.executescript(
                """
                CREATE TABLE IF NOT EXISTS ide_accounts (
                    username_key TEXT PRIMARY KEY,
                    username TEXT NOT NULL,
                    user_id TEXT NOT NULL UNIQUE,
                    role TEXT NOT NULL,
                    password_hash TEXT NOT NULL,
                    password_salt TEXT NOT NULL,
                    password_algorithm TEXT NOT NULL,
                    password_iterations INTEGER NOT NULL,
                    auth_version INTEGER NOT NULL DEFAULT 1,
                    disabled INTEGER NOT NULL DEFAULT 0,
                    must_change_password INTEGER NOT NULL DEFAULT 0,
                    created_at REAL NOT NULL,
                    updated_at REAL NOT NULL
                );
                CREATE TABLE IF NOT EXISTS ide_sessions (
                    token_digest TEXT PRIMARY KEY,
                    username_key TEXT NOT NULL,
                    auth_version INTEGER NOT NULL,
                    csrf_token TEXT NOT NULL,
                    created_at REAL NOT NULL,
                    expires_at REAL NOT NULL,
                    revoked_at REAL NOT NULL DEFAULT 0,
                    last_ip TEXT NOT NULL DEFAULT '',
                    device_digest TEXT NOT NULL DEFAULT '',
                    session_kind TEXT NOT NULL DEFAULT '',
                    FOREIGN KEY(username_key) REFERENCES ide_accounts(username_key)
                );
                CREATE INDEX IF NOT EXISTS ide_sessions_expiry
                    ON ide_sessions(expires_at, revoked_at);
                CREATE TABLE IF NOT EXISTS ide_devices (
                    device_digest TEXT PRIMARY KEY,
                    pairing_id TEXT NOT NULL UNIQUE,
                    label TEXT NOT NULL,
                    fingerprint TEXT NOT NULL DEFAULT '',
                    source_ip TEXT NOT NULL,
                    status TEXT NOT NULL,
                    user_id TEXT NOT NULL,
                    username_key TEXT NOT NULL DEFAULT '',
                    created_at REAL NOT NULL,
                    requested_at REAL NOT NULL,
                    approved_at REAL NOT NULL DEFAULT 0,
                    approved_by TEXT NOT NULL DEFAULT '',
                    last_seen_at REAL NOT NULL DEFAULT 0,
                    revoked_at REAL NOT NULL DEFAULT 0
                );
                CREATE INDEX IF NOT EXISTS ide_devices_status
                    ON ide_devices(status, requested_at);
                """
            )
            columns = {
                str(row["name"] or "")
                for row in conn.execute("PRAGMA table_info(ide_sessions)").fetchall()
            }
            if "device_digest" not in columns:
                conn.execute("ALTER TABLE ide_sessions ADD COLUMN device_digest TEXT NOT NULL DEFAULT ''")
            if "session_kind" not in columns:
                conn.execute("ALTER TABLE ide_sessions ADD COLUMN session_kind TEXT NOT NULL DEFAULT ''")
            # Empty session kinds are legacy cookies and cannot be classified
            # as password, device, or the vulnerable shared local-admin form.
            # Revoke them so no ambiguous identity crosses the new boundary.
            conn.execute(
                "UPDATE ide_sessions SET revoked_at=? WHERE revoked_at=0 AND session_kind=''",
                (now_ts(),),
            )
        try:
            os.chmod(self.path, 0o600)
        except Exception:
            pass

    @classmethod
    def _normalize_username(cls, value: object) -> tuple[str, str]:
        username = unicodedata.normalize("NFKC", str(value or "")).strip()
        if not cls._USERNAME_RE.fullmatch(username):
            raise IDEAuthError(
                "invalid_username",
                "Username must contain 3-64 letters, numbers, dots, underscores, or hyphens.",
            )
        return username, username.casefold()

    @staticmethod
    def _validate_password(password: object, username: str) -> str:
        value = str(password if password is not None else "")
        size = len(value.encode("utf-8", errors="strict"))
        if size < 12 or size > 512:
            raise IDEAuthError("weak_password", "Password must be 12-512 UTF-8 bytes.")
        if value.casefold() == str(username or "").casefold():
            raise IDEAuthError("weak_password", "Password cannot equal the username.")
        classes = sum(
            bool(re.search(pattern, value))
            for pattern in (r"[a-z]", r"[A-Z]", r"[0-9]", r"[^A-Za-z0-9]")
        )
        if classes < 3:
            raise IDEAuthError("weak_password", "Password must use at least three character classes.")
        return value

    @staticmethod
    def _password_digest(password: str, salt: bytes, iterations: int) -> bytes:
        return AdminAuthStore._password_digest(password, salt, iterations)

    def configured(self) -> bool:
        try:
            with self._connect() as conn:
                return conn.execute("SELECT 1 FROM ide_accounts WHERE role='admin' LIMIT 1").fetchone() is not None
        except sqlite3.DatabaseError:
            return True

    @staticmethod
    def _public_account(row: sqlite3.Row | dict | None) -> dict:
        if row is None:
            return {}
        return {
            "username": str(row["username"] or ""),
            "user_id": str(row["user_id"] or ""),
            "role": str(row["role"] or "user"),
            "disabled": bool(row["disabled"]),
            "must_change_password": bool(row["must_change_password"]),
            "created_at": float(row["created_at"] or 0.0),
            "updated_at": float(row["updated_at"] or 0.0),
        }

    def _insert_account(
        self,
        username: object,
        password: object,
        *,
        user_id: str,
        role: str,
        must_change_password: bool = False,
    ) -> dict:
        clean_username, username_key = self._normalize_username(username)
        clean_password = self._validate_password(password, clean_username)
        uid = str(user_id or "").strip()
        if not re.fullmatch(r"[A-Za-z0-9._:-]{8,128}", uid):
            raise IDEAuthError("invalid_user_id", "Invalid IDE user id.")
        role_key = "admin" if str(role or "").strip().lower() == "admin" else "user"
        salt = os.urandom(24)
        with self.password_slots:
            digest = self._password_digest(clean_password, salt, ADMIN_AUTH_PASSWORD_ITERATIONS)
        now = now_ts()
        try:
            with self._connect() as conn:
                conn.execute(
                    """INSERT INTO ide_accounts
                       (username_key,username,user_id,role,password_hash,password_salt,
                        password_algorithm,password_iterations,auth_version,disabled,
                        must_change_password,created_at,updated_at)
                       VALUES(?,?,?,?,?,?,?,?,1,0,?,?,?)""",
                    (
                        username_key,
                        clean_username,
                        uid,
                        role_key,
                        base64.b64encode(digest).decode("ascii"),
                        base64.b64encode(salt).decode("ascii"),
                        "pbkdf2_hmac_sha256",
                        ADMIN_AUTH_PASSWORD_ITERATIONS,
                        1 if must_change_password else 0,
                        now,
                        now,
                    ),
                )
                row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (username_key,)).fetchone()
        except sqlite3.IntegrityError as exc:
            raise IDEAuthError("account_exists", "The username or workspace identity already exists.", 409) from exc
        return self._public_account(row)

    def setup_admin(self, username: object, password: object, *, legacy_user_id: str) -> dict:
        with self.lock:
            if self.configured():
                raise IDEAuthError("setup_already_completed", "IDE administrator already exists.", 409)
            account = self._insert_account(
                username,
                password,
                user_id=legacy_user_id,
                role="admin",
            )
        session = self.login(username, password, "127.0.0.1")
        session["account"] = account
        return session

    def local_session(self, *, legacy_user_id: str, client_ip: str = "127.0.0.1") -> dict:
        """Issue the caller's automatic identity without sharing an admin account."""
        user_id = str(legacy_user_id or user_id_from_ip(client_ip)).strip()
        if not re.fullmatch(r"[A-Za-z0-9._:-]{8,128}", user_id):
            raise IDEAuthError("invalid_user_id", "Invalid IDE local user id.")
        with self.lock:
            with self._connect() as conn:
                row = conn.execute(
                    "SELECT * FROM ide_accounts WHERE user_id=?",
                    (user_id,),
                ).fetchone()
            if row is None:
                random_password = "Local-7!" + base64.urlsafe_b64encode(os.urandom(36)).decode("ascii")
                identity = user_id[5:] if user_id.startswith("user_") else user_id
                safe_identity = re.sub(r"[^A-Za-z0-9._-]", "_", identity)
                username = f"local-user_{safe_identity}"
                if len(username) > 64:
                    digest = hashlib.sha256(user_id.encode("utf-8")).hexdigest()[:24]
                    username = f"local-user_{digest}"
                try:
                    self._insert_account(
                        username,
                        random_password,
                        user_id=user_id,
                        role="user",
                    )
                except IDEAuthError as exc:
                    if exc.code != "account_exists":
                        raise
                with self._connect() as conn:
                    row = conn.execute(
                        "SELECT * FROM ide_accounts WHERE user_id=?",
                        (user_id,),
                    ).fetchone()
            if row is None or bool(row["disabled"]):
                raise IDEAuthError("local_identity_unavailable", "The local IDE identity is unavailable.", 503)
        result = self.issue_session(row, client_ip=client_ip, session_kind="local_auto")
        result["local_auto_login"] = True
        return result

    def create_user(self, username: object, password: object, *, must_change_password: bool = True) -> dict:
        _, key = self._normalize_username(username)
        uid = f"ide_{hashlib.sha256((key + ':' + uuid.uuid4().hex).encode()).hexdigest()[:24]}"
        return self._insert_account(
            username,
            password,
            user_id=uid,
            role="user",
            must_change_password=must_change_password,
        )

    def list_accounts(self) -> list[dict]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM ide_accounts ORDER BY role='admin' DESC, username_key ASC"
            ).fetchall()
        return [self._public_account(row) for row in rows]

    def _check_rate_limit(self, client_ip: str, username_key: str) -> None:
        now = now_ts()
        targets = ((str(client_ip or "unknown")[:96], username_key), (str(client_ip or "unknown")[:96], "*"))
        with self.lock:
            for target, limit in ((targets[0], 8), (targets[1], 24)):
                rows = self.login_failures.setdefault(target, deque())
                while rows and now - rows[0] > 900:
                    rows.popleft()
                if len(rows) >= limit:
                    retry = max(1, int(900 - (now - rows[0])))
                    raise IDEAuthError("rate_limited", "Too many login attempts.", 429, retry_after=retry)

    def _record_failure(self, client_ip: str, username_key: str) -> None:
        now = now_ts()
        with self.lock:
            for target in ((str(client_ip or "unknown")[:96], username_key), (str(client_ip or "unknown")[:96], "*")):
                self.login_failures.setdefault(target, deque()).append(now)

    def login(self, username: object, password: object, client_ip: str) -> dict:
        try:
            _, username_key = self._normalize_username(username)
        except IDEAuthError:
            username_key = "invalid-user"
        self._check_rate_limit(client_ip, username_key)
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (username_key,)).fetchone()
        salt = b"\0" * 24
        expected = b"\0" * 32
        iterations = ADMIN_AUTH_PASSWORD_ITERATIONS
        valid = False
        if row is not None:
            try:
                salt = base64.b64decode(str(row["password_salt"]), validate=True)
                expected = base64.b64decode(str(row["password_hash"]), validate=True)
                iterations = int(row["password_iterations"] or ADMIN_AUTH_PASSWORD_ITERATIONS)
                valid = str(row["password_algorithm"] or "") == "pbkdf2_hmac_sha256" and not bool(row["disabled"])
            except Exception:
                valid = False
        with self.password_slots:
            actual = self._password_digest(str(password if password is not None else ""), salt, iterations)
        if not (valid and hmac.compare_digest(actual, expected)):
            self._record_failure(client_ip, username_key)
            raise IDEAuthError("invalid_credentials", "Invalid username or password.", 401)
        with self.lock:
            self.login_failures.pop((str(client_ip or "unknown")[:96], username_key), None)
        return self.issue_session(row, client_ip=client_ip)

    def _verify_account_password(self, username: object, password: object) -> sqlite3.Row:
        try:
            _, username_key = self._normalize_username(username)
        except IDEAuthError as exc:
            raise IDEAuthError("invalid_credentials", "Invalid username or password.", 401) from exc
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (username_key,)).fetchone()
        salt = b"\0" * 24
        expected = b"\0" * 32
        iterations = ADMIN_AUTH_PASSWORD_ITERATIONS
        valid = False
        if row is not None:
            try:
                salt = base64.b64decode(str(row["password_salt"]), validate=True)
                expected = base64.b64decode(str(row["password_hash"]), validate=True)
                iterations = int(row["password_iterations"] or ADMIN_AUTH_PASSWORD_ITERATIONS)
                valid = str(row["password_algorithm"] or "") == "pbkdf2_hmac_sha256" and not bool(row["disabled"])
            except Exception:
                valid = False
        with self.password_slots:
            actual = self._password_digest(str(password if password is not None else ""), salt, iterations)
        if not (valid and hmac.compare_digest(actual, expected)):
            raise IDEAuthError("invalid_credentials", "Invalid username or password.", 401)
        return row

    @staticmethod
    def _device_digest(device_key: object) -> str:
        raw = str(device_key or "").strip()
        if not re.fullmatch(r"cc_device_[A-Za-z0-9_-]{43,160}", raw):
            raise IDEAuthError("invalid_device_key", "This browser device key is invalid.", 400)
        encoded_size = len(raw.removeprefix("cc_device_"))
        if encoded_size < 43:
            raise IDEAuthError("invalid_device_key", "This browser device key is too short.", 400)
        return hashlib.sha256(raw.encode("utf-8", errors="strict")).hexdigest()

    @staticmethod
    def _public_device(row: sqlite3.Row | dict | None) -> dict:
        if row is None:
            return {}
        return {
            "pairing_id": str(row["pairing_id"] or ""),
            "label": str(row["label"] or ""),
            "fingerprint": str(row["fingerprint"] or ""),
            "source_ip": str(row["source_ip"] or ""),
            "status": str(row["status"] or "pending"),
            "user_id": str(row["user_id"] or ""),
            "created_at": float(row["created_at"] or 0.0),
            "requested_at": float(row["requested_at"] or 0.0),
            "approved_at": float(row["approved_at"] or 0.0),
            "last_seen_at": float(row["last_seen_at"] or 0.0),
            "revoked_at": float(row["revoked_at"] or 0.0),
        }

    def issue_session(
        self,
        account: sqlite3.Row,
        *,
        client_ip: str,
        device_digest: str = "",
        session_kind: str = "password",
    ) -> dict:
        raw = "ide_session_" + base64.urlsafe_b64encode(os.urandom(32)).decode("ascii").rstrip("=")
        digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
        csrf = base64.urlsafe_b64encode(os.urandom(24)).decode("ascii").rstrip("=")
        now = now_ts()
        expires = now + IDE_AUTH_SESSION_TTL_SECONDS
        username_key = str(account["username_key"] or "")
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            conn.execute("DELETE FROM ide_sessions WHERE revoked_at>0 OR expires_at<=?", (now,))
            conn.execute(
                """INSERT INTO ide_sessions
                   (token_digest,username_key,auth_version,csrf_token,created_at,expires_at,
                    revoked_at,last_ip,device_digest,session_kind)
                   VALUES(?,?,?,?,?,?,0,?,?,?)""",
                (
                    digest,
                    username_key,
                    int(account["auth_version"] or 1),
                    csrf,
                    now,
                    expires,
                    str(client_ip or ""),
                    str(device_digest or ""),
                    str(session_kind or "password"),
                ),
            )
            extras = conn.execute(
                """SELECT token_digest FROM ide_sessions WHERE username_key=? AND revoked_at=0
                   ORDER BY created_at DESC LIMIT -1 OFFSET ?""",
                (username_key, IDE_AUTH_MAX_ACTIVE_SESSIONS),
            ).fetchall()
            if extras:
                conn.executemany("UPDATE ide_sessions SET revoked_at=? WHERE token_digest=?", [(now, x[0]) for x in extras])
            conn.execute("COMMIT")
        return {
            "access_token": raw,
            "csrf_token": csrf,
            "expires_at": expires,
            "account": self._public_account(account),
        }

    def verify_session(self, token: str, client_ip: str = "") -> dict | None:
        raw = str(token or "")
        if not raw.startswith("ide_session_") or len(raw) < 48:
            return None
        digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
        now = now_ts()
        with self._connect() as conn:
            row = conn.execute(
                """SELECT a.*,s.csrf_token,s.expires_at,s.token_digest,s.last_ip,s.device_digest,
                          s.session_kind,
                          d.status AS device_status,d.source_ip AS device_source_ip
                   FROM ide_sessions s JOIN ide_accounts a ON a.username_key=s.username_key
                   LEFT JOIN ide_devices d ON d.device_digest=s.device_digest
                   WHERE s.token_digest=? AND s.revoked_at=0 AND s.expires_at>?
                     AND s.auth_version=a.auth_version AND a.disabled=0""",
                (digest, now),
            ).fetchone()
        if row is None:
            return None
        request_ip = str(client_ip or "")
        if str(row["session_kind"] or "") == "local_auto":
            expected_user_id = user_id_from_ip(request_ip)
            if (
                not request_ip
                or not hmac.compare_digest(str(row["last_ip"] or ""), request_ip)
                or not hmac.compare_digest(str(row["user_id"] or ""), expected_user_id)
            ):
                return None
        device_digest = str(row["device_digest"] or "")
        if device_digest:
            if (
                str(row["device_status"] or "") != "approved"
                or not request_ip
                or not hmac.compare_digest(str(row["last_ip"] or ""), request_ip)
                or not hmac.compare_digest(str(row["device_source_ip"] or ""), request_ip)
            ):
                return None
        account = self._public_account(row)
        account.update({
            "csrf_token": str(row["csrf_token"] or ""),
            "expires_at": float(row["expires_at"] or 0.0),
            "token_digest": str(row["token_digest"] or ""),
            "session_kind": str(row["session_kind"] or ""),
        })
        return account

    def register_device(
        self,
        device_key: object,
        *,
        label: object,
        fingerprint: object,
        client_ip: str,
    ) -> dict:
        digest = self._device_digest(device_key)
        now = now_ts()
        clean_label = trim(unicodedata.normalize("NFKC", str(label or "")).strip(), IDE_DEVICE_LABEL_MAX_CHARS)
        clean_label = clean_label or "Web browser"
        clean_fingerprint = trim(str(fingerprint or "").strip(), 500)
        source_ip = trim(str(client_ip or "").strip(), 96)
        if not source_ip:
            raise IDEAuthError("device_ip_required", "The device source address is unavailable.", 400)
        pairing_id = "pair-" + digest[:12]
        user_id = "ide_device_" + digest[:24]
        with self.lock:
            with self._connect() as conn:
                row = conn.execute("SELECT * FROM ide_devices WHERE device_digest=?", (digest,)).fetchone()
            if row is not None and str(row["status"] or "") == "revoked":
                raise IDEAuthError("device_revoked", "This browser device was revoked. Reset its device identity to request access again.", 403)
            username_key = str(row["username_key"] or "") if row is not None else ""
            if not username_key:
                username = "device-" + digest[:12]
                _, candidate_key = self._normalize_username(username)
                with self._connect() as conn:
                    account = conn.execute(
                        "SELECT * FROM ide_accounts WHERE user_id=? OR username_key=?",
                        (user_id, candidate_key),
                    ).fetchone()
                if account is None:
                    password = "Device-9!" + base64.urlsafe_b64encode(os.urandom(36)).decode("ascii")
                    account_payload = self._insert_account(username, password, user_id=user_id, role="user")
                    _, username_key = self._normalize_username(account_payload["username"])
                else:
                    if not hmac.compare_digest(str(account["user_id"] or ""), user_id):
                        raise IDEAuthError("device_identity_conflict", "The browser device identity conflicts with an existing account.", 409)
                    username_key = str(account["username_key"] or "")
            with self._connect() as conn:
                conn.execute("BEGIN IMMEDIATE")
                row = conn.execute("SELECT * FROM ide_devices WHERE device_digest=?", (digest,)).fetchone()
                if row is None:
                    conn.execute(
                        """INSERT INTO ide_devices
                           (device_digest,pairing_id,label,fingerprint,source_ip,status,user_id,
                            username_key,created_at,requested_at,approved_at,approved_by,last_seen_at,revoked_at)
                           VALUES(?,?,?,?,?,'approved',?,?,?, ?,?,'automatic-device-binding',?,0)""",
                        (digest, pairing_id, clean_label, clean_fingerprint, source_ip, user_id, username_key, now, now, now, now),
                    )
                elif str(row["status"] or "") == "revoked":
                    conn.execute("ROLLBACK")
                    raise IDEAuthError("device_revoked", "This browser device was revoked. Reset its device identity to request access again.", 403)
                elif not hmac.compare_digest(str(row["source_ip"] or ""), source_ip):
                    conn.execute(
                        """UPDATE ide_devices SET label=?,fingerprint=?,source_ip=?,status='approved',
                           username_key=?,requested_at=?,approved_at=?,approved_by='automatic-device-binding',
                           last_seen_at=?,revoked_at=0 WHERE device_digest=?""",
                        (clean_label, clean_fingerprint, source_ip, username_key, now, now, now, digest),
                    )
                    conn.execute(
                        "UPDATE ide_sessions SET revoked_at=? WHERE device_digest=? AND revoked_at=0",
                        (now, digest),
                    )
                else:
                    conn.execute(
                        """UPDATE ide_devices SET label=?,fingerprint=?,status='approved',username_key=?,
                           approved_at=CASE WHEN approved_at>0 THEN approved_at ELSE ? END,
                           approved_by=CASE WHEN approved_by<>'' THEN approved_by ELSE 'automatic-device-binding' END,
                           last_seen_at=?,revoked_at=0 WHERE device_digest=?""",
                        (clean_label, clean_fingerprint, username_key, now, now, digest),
                    )
                row = conn.execute("SELECT * FROM ide_devices WHERE device_digest=?", (digest,)).fetchone()
                conn.execute("COMMIT")
        if row is None:
            raise IDEAuthError("device_registration_failed", "The device request could not be stored.", 503)
        username_key = str(row["username_key"] or "")
        with self._connect() as conn:
            account = conn.execute(
                "SELECT * FROM ide_accounts WHERE username_key=? AND disabled=0",
                (username_key,),
            ).fetchone()
        if account is None:
            raise IDEAuthError("device_identity_unavailable", "The approved device identity is unavailable.", 503)
        result = self.issue_session(
            account,
            client_ip=source_ip,
            device_digest=digest,
            session_kind="device",
        )
        result["device"] = self._public_device(row)
        result["device_authenticated"] = True
        return result

    def list_devices(self) -> list[dict]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM ide_devices ORDER BY status='pending' DESC,requested_at DESC"
            ).fetchall()
        return [self._public_device(row) for row in rows]

    def approve_device(self, pairing_id: object, *, approved_by: str) -> dict:
        pairing = str(pairing_id or "").strip()
        with self.lock:
            with self._connect() as conn:
                row = conn.execute("SELECT * FROM ide_devices WHERE pairing_id=?", (pairing,)).fetchone()
            if row is None:
                raise IDEAuthError("device_not_found", "Device pairing request not found.", 404)
            if str(row["status"] or "") == "revoked":
                raise IDEAuthError("device_revoked", "A revoked device cannot be approved.", 409)
            username_key = str(row["username_key"] or "")
            if not username_key:
                username = "device-" + str(row["device_digest"] or "")[:12]
                password = "Device-9!" + base64.urlsafe_b64encode(os.urandom(36)).decode("ascii")
                account = self._insert_account(
                    username,
                    password,
                    user_id=str(row["user_id"] or ""),
                    role="user",
                )
                _, username_key = self._normalize_username(account["username"])
            now = now_ts()
            with self._connect() as conn:
                conn.execute(
                    """UPDATE ide_devices SET status='approved',username_key=?,approved_at=?,
                       approved_by=?,last_seen_at=?,revoked_at=0 WHERE pairing_id=?""",
                    (username_key, now, trim(approved_by, 64), now, pairing),
                )
                row = conn.execute("SELECT * FROM ide_devices WHERE pairing_id=?", (pairing,)).fetchone()
        return self._public_device(row)

    def revoke_device(self, pairing_id: object) -> dict:
        pairing = str(pairing_id or "").strip()
        now = now_ts()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute("SELECT * FROM ide_devices WHERE pairing_id=?", (pairing,)).fetchone()
            if row is None:
                conn.execute("ROLLBACK")
                raise IDEAuthError("device_not_found", "Device pairing request not found.", 404)
            digest = str(row["device_digest"] or "")
            conn.execute(
                "UPDATE ide_devices SET status='revoked',revoked_at=?,last_seen_at=? WHERE pairing_id=?",
                (now, now, pairing),
            )
            conn.execute("UPDATE ide_sessions SET revoked_at=? WHERE device_digest=?", (now, digest))
            row = conn.execute("SELECT * FROM ide_devices WHERE pairing_id=?", (pairing,)).fetchone()
            conn.execute("COMMIT")
        return self._public_device(row)

    def revoke_session(self, token: str) -> None:
        raw = str(token or "")
        if not raw.startswith("ide_session_"):
            return
        digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
        with self._connect() as conn:
            conn.execute("UPDATE ide_sessions SET revoked_at=? WHERE token_digest=?", (now_ts(), digest))

    def set_disabled(self, username: object, disabled: bool) -> dict:
        _, key = self._normalize_username(username)
        now = now_ts()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (key,)).fetchone()
            if row is None:
                conn.execute("ROLLBACK")
                raise IDEAuthError("account_not_found", "IDE account not found.", 404)
            if str(row["role"] or "") == "admin" and disabled:
                conn.execute("ROLLBACK")
                raise IDEAuthError("admin_disable_forbidden", "The IDE administrator cannot be disabled.", 409)
            conn.execute(
                "UPDATE ide_accounts SET disabled=?,auth_version=auth_version+1,updated_at=? WHERE username_key=?",
                (1 if disabled else 0, now, key),
            )
            conn.execute("UPDATE ide_sessions SET revoked_at=? WHERE username_key=?", (now, key))
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (key,)).fetchone()
            conn.execute("COMMIT")
        return self._public_account(row)

    def change_password(self, account: dict, old_password: object, new_password: object) -> dict:
        username = str(account.get("username", "") or "")
        self._verify_account_password(username, old_password)
        clean_password = self._validate_password(new_password, username)
        salt = os.urandom(24)
        with self.password_slots:
            digest = self._password_digest(clean_password, salt, ADMIN_AUTH_PASSWORD_ITERATIONS)
        now = now_ts()
        _, key = self._normalize_username(username)
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            conn.execute(
                """UPDATE ide_accounts SET password_hash=?,password_salt=?,password_iterations=?,
                   auth_version=auth_version+1,must_change_password=0,updated_at=? WHERE username_key=?""",
                (
                    base64.b64encode(digest).decode("ascii"),
                    base64.b64encode(salt).decode("ascii"),
                    ADMIN_AUTH_PASSWORD_ITERATIONS,
                    now,
                    key,
                ),
            )
            conn.execute("UPDATE ide_sessions SET revoked_at=? WHERE username_key=?", (now, key))
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (key,)).fetchone()
            conn.execute("COMMIT")
        return self._public_account(row)

    def reset_password(self, username: object, new_password: object) -> dict:
        clean_username, key = self._normalize_username(username)
        clean_password = self._validate_password(new_password, clean_username)
        salt = os.urandom(24)
        with self.password_slots:
            digest = self._password_digest(clean_password, salt, ADMIN_AUTH_PASSWORD_ITERATIONS)
        now = now_ts()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (key,)).fetchone()
            if row is None:
                conn.execute("ROLLBACK")
                raise IDEAuthError("account_not_found", "IDE account not found.", 404)
            conn.execute(
                """UPDATE ide_accounts SET password_hash=?,password_salt=?,password_iterations=?,
                   auth_version=auth_version+1,must_change_password=0,updated_at=? WHERE username_key=?""",
                (
                    base64.b64encode(digest).decode("ascii"),
                    base64.b64encode(salt).decode("ascii"),
                    ADMIN_AUTH_PASSWORD_ITERATIONS,
                    now,
                    key,
                ),
            )
            conn.execute("UPDATE ide_sessions SET revoked_at=? WHERE username_key=?", (now, key))
            row = conn.execute("SELECT * FROM ide_accounts WHERE username_key=?", (key,)).fetchone()
            conn.execute("COMMIT")
        return self._public_account(row)
