# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=816 original-lines=14122-14128 hash=a7a3f693afd66024


class IDECapabilityError(Exception):
    def __init__(self, code: str, message: str, status: int = 403):
        super().__init__(message)
        self.code = str(code or "ide_capability_denied")
        self.status = int(status or 403)

# split-source: order=817 original-lines=14129-14136 hash=a89c4b79be3974b9


class IDEFileConflict(Exception):
    def __init__(self, current: dict):
        super().__init__("The file changed on disk after it was opened.")
        self.code = "file_conflict"
        self.status = 409
        self.current = dict(current or {})
