# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=670 original-lines=7533-7550 hash=ac928f4957da521b

def _windows_subprocess_encodings() -> list[str]:
    if os.name != "nt" and not sys.platform.startswith("win"):
        return []
    out: list[str] = []
    try:
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        for function_name in ("GetOEMCP", "GetACP"):
            function = getattr(kernel32, function_name, None)
            if function is None:
                continue
            function.restype = ctypes.c_uint
            codepage = int(function() or 0)
            if codepage > 0:
                out.append(f"cp{codepage}")
    except Exception:
        pass
    return out

# split-source: order=934 original-lines=27174-27182 hash=9e668c7c3fcbd2dc

# ============================================================================
# Architecture / 架构 / アーキテクチャ
# Layer 4: Session execution chain and agent-facing runtime state.
# 第四层：会话执行链与面向 agent 的运行时状态。
# 第4層：セッション実行チェーンと agent 向けランタイム状態。
# ============================================================================

_IDE_SANDBOX_BACKEND_CACHE: dict[str, object] = {}

# split-source: order=935 original-lines=27183-27183 hash=6fd3520014763931
_IDE_SANDBOX_BACKEND_LOCK = threading.RLock()

# split-source: order=936 original-lines=27184-27184 hash=8a49dbb25dd35c5c
WINDOWS_JOB_SANDBOX_MARKER = "__clouds_windows_job__"

# split-source: order=937 original-lines=27185-27185 hash=e9091a7636337ff2
_WINDOWS_LOW_INTEGRITY_ROOTS: set[str] = set()

# split-source: order=938 original-lines=27186-27186 hash=e81acd4ddab152d2
_WINDOWS_LOW_INTEGRITY_FAILED_ROOTS: set[str] = set()

# split-source: order=939 original-lines=27187-27187 hash=5e5351da59b8c3e5
_WINDOWS_LOW_INTEGRITY_LOCK = threading.RLock()

# split-source: order=940 original-lines=27188-27194 hash=77416c0f2acc726f

def _is_windows_job_sandbox_prefix(prefix: object) -> bool:
    return bool(
        isinstance(prefix, (list, tuple))
        and len(prefix) == 1
        and str(prefix[0]) == WINDOWS_JOB_SANDBOX_MARKER
    )

# split-source: order=941 original-lines=27195-27218 hash=916341a37017a4ba

def _windows_builtin_sandbox_probe() -> tuple[bool, str]:
    if os.name != "nt" or not sys.platform.startswith("win"):
        return False, "Windows security APIs are unavailable on this platform."
    try:
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        advapi32 = ctypes.WinDLL("advapi32", use_last_error=True)
        ntdll = ctypes.WinDLL("ntdll", use_last_error=True)
        required = (
            (kernel32, "CreateJobObjectW"),
            (kernel32, "AssignProcessToJobObject"),
            (kernel32, "SetInformationJobObject"),
            (advapi32, "OpenProcessToken"),
            (advapi32, "SetTokenInformation"),
            (advapi32, "AddMandatoryAce"),
            (advapi32, "SetNamedSecurityInfoW"),
            (ntdll, "NtResumeProcess"),
        )
        missing = [name for library, name in required if not hasattr(library, name)]
        if missing:
            return False, f"Windows security API missing: {', '.join(missing)}"
        return True, "Built-in low-integrity token and Job Object isolation."
    except Exception as exc:
        return False, f"Windows security API initialization failed: {exc}"

# split-source: order=942 original-lines=27219-27226 hash=7e07dad19e17b216

def _windows_last_error(label: str) -> OSError:
    code = int(ctypes.get_last_error() or 1)
    try:
        detail = ctypes.FormatError(code).strip()
    except Exception:
        detail = "Windows API error"
    return OSError(code, f"{label}: {detail}")

# split-source: order=943 original-lines=27227-27280 hash=9bc6a284727c424d

def _windows_set_integrity_label(path: Path, *, inherit: bool, sid_string: str) -> None:
    from ctypes import wintypes

    advapi32 = ctypes.WinDLL("advapi32", use_last_error=True)
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    sid = ctypes.c_void_p()
    advapi32.ConvertStringSidToSidW.argtypes = [wintypes.LPCWSTR, ctypes.POINTER(ctypes.c_void_p)]
    advapi32.ConvertStringSidToSidW.restype = wintypes.BOOL
    if not advapi32.ConvertStringSidToSidW(sid_string, ctypes.byref(sid)):
        raise _windows_last_error("ConvertStringSidToSidW")
    try:
        advapi32.GetLengthSid.argtypes = [ctypes.c_void_p]
        advapi32.GetLengthSid.restype = wintypes.DWORD
        sid_length = int(advapi32.GetLengthSid(sid) or 0)
        acl_size = max(128, sid_length + 64)
        acl = ctypes.create_string_buffer(acl_size)
        advapi32.InitializeAcl.argtypes = [ctypes.c_void_p, wintypes.DWORD, wintypes.DWORD]
        advapi32.InitializeAcl.restype = wintypes.BOOL
        if not advapi32.InitializeAcl(ctypes.byref(acl), acl_size, 2):
            raise _windows_last_error("InitializeAcl")
        advapi32.AddMandatoryAce.argtypes = [
            ctypes.c_void_p,
            wintypes.DWORD,
            wintypes.DWORD,
            wintypes.DWORD,
            ctypes.c_void_p,
        ]
        advapi32.AddMandatoryAce.restype = wintypes.BOOL
        ace_flags = 0x03 if inherit else 0
        if not advapi32.AddMandatoryAce(ctypes.byref(acl), 2, ace_flags, 0x1, sid):
            raise _windows_last_error("AddMandatoryAce")
        advapi32.SetNamedSecurityInfoW.argtypes = [
            wintypes.LPWSTR,
            wintypes.DWORD,
            wintypes.DWORD,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
        ]
        advapi32.SetNamedSecurityInfoW.restype = wintypes.DWORD
        status = int(
            advapi32.SetNamedSecurityInfoW(
                str(path), 1, 0x10, None, None, None, ctypes.byref(acl)
            )
            or 0
        )
        if status:
            raise OSError(status, f"SetNamedSecurityInfoW: {ctypes.FormatError(status).strip()}")
    finally:
        kernel32.LocalFree.argtypes = [ctypes.c_void_p]
        kernel32.LocalFree.restype = ctypes.c_void_p
        kernel32.LocalFree(sid)

# split-source: order=944 original-lines=27281-27283 hash=1b60eda767ee08cf

def _windows_set_low_integrity_label(path: Path, *, inherit: bool) -> None:
    _windows_set_integrity_label(path, inherit=inherit, sid_string="S-1-16-4096")

# split-source: order=945 original-lines=27284-27307 hash=9037185914e9a128

def _windows_protect_application_snapshot(workspace_root: Path) -> None:
    snapshot = Path(workspace_root) / ".application_skills"
    if not snapshot.exists() or snapshot.is_symlink():
        return
    for dirpath, dirnames, filenames in os.walk(snapshot, topdown=True, followlinks=False):
        current = Path(dirpath)
        dirnames[:] = [name for name in dirnames if not (current / name).is_symlink()]
        try:
            _windows_set_integrity_label(current, inherit=True, sid_string="S-1-16-8192")
        except OSError:
            pass
        for name in filenames:
            target = current / name
            if target.is_symlink():
                continue
            try:
                _windows_set_integrity_label(target, inherit=False, sid_string="S-1-16-8192")
            except OSError:
                pass
            try:
                os.chmod(target, stat.S_IREAD)
            except Exception:
                pass

# split-source: order=946 original-lines=27308-27345 hash=0427774e9b45bad0

def _windows_prepare_low_integrity_workspace(workspace_root: Path) -> bool:
    canonical = Path(os.path.realpath(workspace_root)).resolve()
    key = os.path.normcase(str(canonical))
    with _WINDOWS_LOW_INTEGRITY_LOCK:
        _windows_protect_application_snapshot(canonical)
        if key in _WINDOWS_LOW_INTEGRITY_ROOTS or key in _WINDOWS_LOW_INTEGRITY_FAILED_ROOTS:
            return key in _WINDOWS_LOW_INTEGRITY_ROOTS
        # The low-integrity label is defense-in-depth. Standard Windows users can
        # lack SeSecurityPrivilege, in which case SetNamedSecurityInfoW returns
        # ERROR_ACCESS_DENIED even though the Job Object/token sandbox is usable.
        # Record that capability failure once and continue with the stronger job
        # isolation instead of failing every Bash invocation.
        try:
            _windows_set_low_integrity_label(canonical, inherit=True)
        except OSError:
            _WINDOWS_LOW_INTEGRITY_FAILED_ROOTS.add(key)
            return False
        for dirpath, dirnames, filenames in os.walk(canonical, topdown=True, followlinks=False):
            current = Path(dirpath)
            dirnames[:] = [name for name in dirnames if not (current / name).is_symlink()]
            if current == canonical:
                dirnames[:] = [name for name in dirnames if name != ".application_skills"]
            for name in dirnames:
                try:
                    _windows_set_low_integrity_label(current / name, inherit=True)
                except OSError:
                    pass
            for name in filenames:
                file_path = current / name
                if file_path.is_symlink():
                    continue
                try:
                    _windows_set_low_integrity_label(file_path, inherit=False)
                except OSError:
                    pass
        _WINDOWS_LOW_INTEGRITY_ROOTS.add(key)
        return True

# split-source: order=947 original-lines=27346-27353 hash=f8b21aa8be386c16

def _windows_job_memory_limit() -> int:
    raw = str(os.environ.get("CLOUDS_CODER_SANDBOX_MEMORY", "1g") or "1g").strip().lower()
    match = re.fullmatch(r"(\d+(?:\.\d+)?)\s*([kmgt]?)b?", raw)
    if not match:
        return 1024 * 1024 * 1024
    factor = {"": 1, "k": 1024, "m": 1024**2, "g": 1024**3, "t": 1024**4}[match.group(2)]
    return max(128 * 1024 * 1024, min(16 * 1024**3, int(float(match.group(1)) * factor)))

# split-source: order=948 original-lines=27354-27401 hash=7a33e21232b7a212

def _windows_lower_process_integrity(process_handle: object) -> None:
    from ctypes import wintypes

    advapi32 = ctypes.WinDLL("advapi32", use_last_error=True)
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

    class SID_AND_ATTRIBUTES(ctypes.Structure):
        _fields_ = [("Sid", ctypes.c_void_p), ("Attributes", wintypes.DWORD)]

    class TOKEN_MANDATORY_LABEL(ctypes.Structure):
        _fields_ = [("Label", SID_AND_ATTRIBUTES)]

    token = wintypes.HANDLE()
    advapi32.OpenProcessToken.argtypes = [wintypes.HANDLE, wintypes.DWORD, ctypes.POINTER(wintypes.HANDLE)]
    advapi32.OpenProcessToken.restype = wintypes.BOOL
    if not advapi32.OpenProcessToken(process_handle, 0x0080 | 0x0008, ctypes.byref(token)):
        raise _windows_last_error("OpenProcessToken")
    sid = ctypes.c_void_p()
    try:
        advapi32.ConvertStringSidToSidW.argtypes = [wintypes.LPCWSTR, ctypes.POINTER(ctypes.c_void_p)]
        advapi32.ConvertStringSidToSidW.restype = wintypes.BOOL
        if not advapi32.ConvertStringSidToSidW("S-1-16-4096", ctypes.byref(sid)):
            raise _windows_last_error("ConvertStringSidToSidW")
        advapi32.GetLengthSid.argtypes = [ctypes.c_void_p]
        advapi32.GetLengthSid.restype = wintypes.DWORD
        sid_length = int(advapi32.GetLengthSid(sid) or 0)
        label = TOKEN_MANDATORY_LABEL(SID_AND_ATTRIBUTES(sid, 0x20))
        advapi32.SetTokenInformation.argtypes = [
            wintypes.HANDLE,
            ctypes.c_int,
            ctypes.c_void_p,
            wintypes.DWORD,
        ]
        advapi32.SetTokenInformation.restype = wintypes.BOOL
        if not advapi32.SetTokenInformation(
            token, 25, ctypes.byref(label), ctypes.sizeof(label) + sid_length
        ):
            raise _windows_last_error("SetTokenInformation(TokenIntegrityLevel)")
    finally:
        if sid:
            kernel32.LocalFree.argtypes = [ctypes.c_void_p]
            kernel32.LocalFree.restype = ctypes.c_void_p
            kernel32.LocalFree(sid)
        if token:
            kernel32.CloseHandle.argtypes = [wintypes.HANDLE]
            kernel32.CloseHandle.restype = wintypes.BOOL
            kernel32.CloseHandle(token)

# split-source: order=949 original-lines=27402-27494 hash=8b61c117b2a11d8e

def _windows_attach_sandbox_job(
    proc: subprocess.Popen,
    workspace_root: Path,
    *,
    lower_integrity: bool = True,
) -> None:
    from ctypes import wintypes

    class LARGE_INTEGER(ctypes.Union):
        _fields_ = [("QuadPart", ctypes.c_longlong)]

    class JOBOBJECT_BASIC_LIMIT_INFORMATION(ctypes.Structure):
        _fields_ = [
            ("PerProcessUserTimeLimit", LARGE_INTEGER),
            ("PerJobUserTimeLimit", LARGE_INTEGER),
            ("LimitFlags", wintypes.DWORD),
            ("MinimumWorkingSetSize", ctypes.c_size_t),
            ("MaximumWorkingSetSize", ctypes.c_size_t),
            ("ActiveProcessLimit", wintypes.DWORD),
            ("Affinity", ctypes.c_size_t),
            ("PriorityClass", wintypes.DWORD),
            ("SchedulingClass", wintypes.DWORD),
        ]

    class IO_COUNTERS(ctypes.Structure):
        _fields_ = [(name, ctypes.c_ulonglong) for name in (
            "ReadOperationCount", "WriteOperationCount", "OtherOperationCount",
            "ReadTransferCount", "WriteTransferCount", "OtherTransferCount",
        )]

    class JOBOBJECT_EXTENDED_LIMIT_INFORMATION(ctypes.Structure):
        _fields_ = [
            ("BasicLimitInformation", JOBOBJECT_BASIC_LIMIT_INFORMATION),
            ("IoInfo", IO_COUNTERS),
            ("ProcessMemoryLimit", ctypes.c_size_t),
            ("JobMemoryLimit", ctypes.c_size_t),
            ("PeakProcessMemoryUsed", ctypes.c_size_t),
            ("PeakJobMemoryUsed", ctypes.c_size_t),
        ]

    class JOBOBJECT_CPU_RATE_CONTROL_INFORMATION(ctypes.Structure):
        _fields_ = [("ControlFlags", wintypes.DWORD), ("CpuRate", wintypes.DWORD)]

    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    ntdll = ctypes.WinDLL("ntdll", use_last_error=True)
    kernel32.CreateJobObjectW.argtypes = [ctypes.c_void_p, wintypes.LPCWSTR]
    kernel32.CreateJobObjectW.restype = wintypes.HANDLE
    job = kernel32.CreateJobObjectW(None, None)
    if not job:
        raise _windows_last_error("CreateJobObjectW")
    try:
        limits = JOBOBJECT_EXTENDED_LIMIT_INFORMATION()
        limits.BasicLimitInformation.LimitFlags = 0x2000 | 0x0008 | 0x0200 | 0x0400
        limits.BasicLimitInformation.ActiveProcessLimit = 64
        limits.JobMemoryLimit = _windows_job_memory_limit()
        kernel32.SetInformationJobObject.argtypes = [wintypes.HANDLE, ctypes.c_int, ctypes.c_void_p, wintypes.DWORD]
        kernel32.SetInformationJobObject.restype = wintypes.BOOL
        if not kernel32.SetInformationJobObject(job, 9, ctypes.byref(limits), ctypes.sizeof(limits)):
            raise _windows_last_error("SetInformationJobObject")
        try:
            cpu_budget = max(
                0.1,
                float(os.environ.get("CLOUDS_CODER_SANDBOX_CPUS", "2") or 2),
            )
        except Exception:
            cpu_budget = 2.0
        cpu_fraction = min(1.0, cpu_budget / max(1, int(os.cpu_count() or 1)))
        cpu_limit = JOBOBJECT_CPU_RATE_CONTROL_INFORMATION(
            0x1 | 0x4,
            max(100, min(10_000, int(cpu_fraction * 10_000))),
        )
        # CPU hard caps are available on supported desktop Windows versions.
        # Memory/process-tree isolation remains active if an older kernel rejects it.
        kernel32.SetInformationJobObject(
            job, 15, ctypes.byref(cpu_limit), ctypes.sizeof(cpu_limit)
        )
        if lower_integrity:
            _windows_lower_process_integrity(proc._handle)
        kernel32.AssignProcessToJobObject.argtypes = [wintypes.HANDLE, wintypes.HANDLE]
        kernel32.AssignProcessToJobObject.restype = wintypes.BOOL
        if not kernel32.AssignProcessToJobObject(job, proc._handle):
            raise _windows_last_error("AssignProcessToJobObject")
        proc._clouds_windows_job_handle = job
        job = None
        ntdll.NtResumeProcess.argtypes = [wintypes.HANDLE]
        ntdll.NtResumeProcess.restype = ctypes.c_long
        status = int(ntdll.NtResumeProcess(proc._handle) or 0)
        if status < 0:
            raise OSError(status, "NtResumeProcess failed")
    finally:
        if job:
            kernel32.CloseHandle(job)

# split-source: order=950 original-lines=27495-27511 hash=a01de1a457312922

def _windows_close_sandbox_job(proc: subprocess.Popen | None, *, terminate: bool = False) -> None:
    if proc is None:
        return
    job = getattr(proc, "_clouds_windows_job_handle", None)
    if not job:
        return
    try:
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        if terminate:
            try:
                kernel32.TerminateJobObject(job, 1)
            except Exception:
                pass
        kernel32.CloseHandle(job)
    finally:
        proc._clouds_windows_job_handle = None

# split-source: order=951 original-lines=27512-27543 hash=c4a14a964d9cd5dc

def _popen_windows_sandboxed(
    command: object,
    *,
    workspace_root: Path,
    cwd: Path,
    env: dict,
    **kwargs,
) -> subprocess.Popen:
    if os.name != "nt":
        raise RuntimeError("Windows built-in sandbox requested on a non-Windows platform")
    low_integrity_ready = _windows_prepare_low_integrity_workspace(workspace_root)
    flags = int(kwargs.pop("creationflags", 0) or 0)
    flags |= int(getattr(subprocess, "CREATE_SUSPENDED", 0x00000004) or 0x00000004)
    flags |= int(getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0x00000200) or 0x00000200)
    proc = subprocess.Popen(
        command,
        cwd=str(cwd),
        env=env,
        creationflags=flags,
        **kwargs,
    )
    try:
        _windows_attach_sandbox_job(proc, workspace_root, lower_integrity=low_integrity_ready)
        return proc
    except Exception:
        try:
            ctypes.WinDLL("kernel32", use_last_error=True).TerminateProcess(proc._handle, 1)
        except Exception:
            pass
        _windows_close_sandbox_job(proc, terminate=True)
        raise

# split-source: order=952 original-lines=27544-27597 hash=3712bcbfdf4619bd

def _run_windows_sandboxed_command(
    command: str,
    *,
    workspace_root: Path,
    cwd: Path,
    env: dict,
    timeout: int,
) -> subprocess.CompletedProcess:
    proc = _popen_windows_sandboxed(
        f"chcp 65001>nul & {command}",
        workspace_root=workspace_root,
        cwd=cwd,
        env=env,
        shell=True,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=False,
        bufsize=0,
    )
    try:
        stdout, stderr = proc.communicate(timeout=timeout)
        stdout_text, stdout_diagnostics = decode_subprocess_bytes(stdout)
        stderr_text, stderr_diagnostics = decode_subprocess_bytes(stderr)
        completed = subprocess.CompletedProcess(
            command,
            int(proc.returncode or 0),
            stdout_text,
            stderr_text,
        )
        completed.decoding_diagnostics = {
            "stdout": stdout_diagnostics,
            "stderr": stderr_diagnostics,
        }
        return completed
    except subprocess.TimeoutExpired as exc:
        _windows_close_sandbox_job(proc, terminate=True)
        try:
            stdout, stderr = proc.communicate(timeout=2)
        except Exception:
            stdout = getattr(exc, "stdout", None)
            stderr = getattr(exc, "stderr", None)
        stdout_text, stdout_diagnostics = decode_subprocess_bytes(stdout)
        stderr_text, stderr_diagnostics = decode_subprocess_bytes(stderr)
        exc.stdout = exc.output = stdout_text
        exc.stderr = stderr_text
        exc.decoding_diagnostics = {
            "stdout": stdout_diagnostics,
            "stderr": stderr_diagnostics,
        }
        raise exc
    finally:
        _windows_close_sandbox_job(proc)

# split-source: order=953 original-lines=27598-27702 hash=9dd286da7d9bf200

def _detect_ide_sandbox_backend(*, force: bool = False) -> dict:
    preference = str(os.environ.get("CLOUDS_CODER_SANDBOX_BACKEND", "auto") or "auto").strip().lower()
    image = str(os.environ.get("CLOUDS_CODER_SANDBOX_IMAGE", "clouds-coder-sandbox:latest") or "").strip()
    cache_key = "|".join((os.name, sys.platform, preference, image, str(os.environ.get("PATH", ""))))
    with _IDE_SANDBOX_BACKEND_LOCK:
        cached = _IDE_SANDBOX_BACKEND_CACHE.get(cache_key)
        if not force and isinstance(cached, dict) and (now_ts() - float(cached.get("checked_at", 0.0) or 0.0)) < 60.0:
            return dict(cached)

    def result(name: str = "", *, available: bool = False, terminal: bool = False, debug: bool = False, reason: str = "") -> dict:
        return {
            "available": bool(available),
            "name": name,
            "processes": bool(available),
            "terminal": bool(available and terminal),
            "debug": bool(available and debug),
            "reason": reason,
            "image": image if name in {"docker", "podman"} else "",
            "checked_at": now_ts(),
        }

    if preference in {"off", "disabled", "none"}:
        detected = result(reason="Hard process isolation is disabled by CLOUDS_CODER_SANDBOX_BACKEND.")
    elif preference in {"auto", "windows-job", "windows", "builtin"} and os.name == "nt" and sys.platform.startswith("win"):
        ready, reason = _windows_builtin_sandbox_probe()
        detected = (
            result(
                "windows-job",
                available=True,
                terminal=True,
                debug=True,
                reason=reason,
            )
            if ready
            else None
        )
    elif preference in {"auto", "sandbox-exec", "seatbelt"} and os.name == "posix" and sys.platform == "darwin" and shutil.which("sandbox-exec"):
        detected = result("sandbox-exec", available=True, terminal=True, debug=True)
    elif preference in {"auto", "bubblewrap", "bwrap"} and os.name == "posix" and sys.platform.startswith("linux") and shutil.which("bwrap"):
        bwrap = str(shutil.which("bwrap") or "")
        try:
            probe = subprocess.run(
                [
                    bwrap,
                    "--die-with-parent",
                    "--unshare-user",
                    "--unshare-pid",
                    "--ro-bind", "/", "/",
                    "--proc", "/proc",
                    "--dev", "/dev",
                    "--", "/bin/true",
                ],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=4,
            )
            detected = result("bubblewrap", available=True, terminal=True, debug=True) if probe.returncode == 0 else None
        except Exception:
            detected = None
    else:
        detected = None
    if detected is None:
        runtimes = (
            (preference,)
            if preference in {"docker", "podman"}
            else (("docker", "podman") if preference == "auto" else ())
        )
        if image:
            for runtime_name in runtimes:
                runtime = shutil.which(runtime_name)
                if not runtime:
                    continue
                try:
                    probe = subprocess.run(
                        [runtime, "image", "inspect", image],
                        stdin=subprocess.DEVNULL,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                        timeout=4,
                    )
                except Exception:
                    continue
                if probe.returncode == 0:
                    detected = result(
                        runtime_name,
                        available=True,
                        terminal=False,
                        debug=False,
                        reason="The container backend supports commands, tasks, and agents; host PTY and debug adapter passthrough are disabled.",
                    )
                    break
        if detected is None:
            detected = result(
                reason=(
                    "No hard isolation backend is ready. The built-in Windows Job Object sandbox, "
                    "sandbox-exec (macOS), Bubblewrap (Linux), or a pre-loaded Docker/Podman "
                    f"image ({image or '<unset>'}) is required."
                )
            )
    with _IDE_SANDBOX_BACKEND_LOCK:
        _IDE_SANDBOX_BACKEND_CACHE.clear()
        _IDE_SANDBOX_BACKEND_CACHE[cache_key] = dict(detected)
    return detected
