# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821
"""Architecture-aware split of the original Clouds_Coder application."""

from ._runtime import bootstrap as _bootstrap

_bootstrap()
del _bootstrap
