# Auto-generated by split_coder.py v3 — do not edit manually.
# Re-run run_split.py to regenerate.
# flake8: noqa: F821
# ruff: noqa: F401, F821

from __future__ import annotations

# split-source: order=632 original-lines=6859-6864 hash=86ab07aacf89e33f


class SessionCreationLimitExceeded(RuntimeError):
    def __init__(self, status: dict):
        self.status = dict(status or {})
        super().__init__(str(self.status.get("message", "daily session limit reached")))

# split-source: order=955 original-lines=82481-83860 hash=f2c63bcdee6ee050

class SessionManager:
    def __init__(
        self,
        root: Path,
        user_id: str,
        ollama_base: str,
        model: str,
        skills_root: Path,
        js_lib_root: Path,
        crypto: CryptoBox,
        repo_root: Path,
        thinking: bool = False,
        default_llm_config: dict | None = None,
        default_language: str = DEFAULT_UI_LANGUAGE,
        context_token_limit: int = DEFAULT_CONTEXT_TOKEN_LIMIT,
        context_limit_locked: bool = False,
        max_rounds: int = MAX_AGENT_ROUNDS,
        max_run_seconds: int = MAX_RUN_SECONDS,
        shell_command_timeout_seconds: int = DEFAULT_SHELL_COMMAND_TIMEOUT_SECONDS,
        auto_task_level_ceiling: int = DEFAULT_AUTO_TASK_LEVEL_CEILING,
        l2_todo_policy: str | None = None,
        auto_model_switch: bool = False,
        arbiter_enabled: bool = True,
        arbiter_model: str = "",
        arbiter_timeout_seconds: float = ARBITER_DEFAULT_TIMEOUT_SECONDS,
        arbiter_max_tokens: int = ARBITER_DEFAULT_MAX_TOKENS,
        arbiter_temperature: float = ARBITER_DEFAULT_TEMPERATURE,
        execution_mode: str = EXECUTION_MODE_SYNC,
        max_output_tokens: int = AGENT_MAX_OUTPUT_TOKENS,
        web_search_enabled: bool = DEFAULT_WEB_SEARCH_ENABLED,
        web_search_setting_locked: bool = False,
        user_memory_mode: str = DEFAULT_USER_MEMORY_MODE,
        user_memory_setting_locked: bool = False,
        upload_callback=None,
        run_finished_callback=None,
        reference_prepare_callback=None,
        query_code_library_callback=None,
        query_knowledge_library_callback=None,
        rag_remember_callback=None,
        code_library_root: Path | str | None = None,
        code_library_status_callback=None,
        knowledge_library_root: Path | str | None = None,
        knowledge_library_status_callback=None,
        mcp_manager=None,
        js_lib_download_enabled: bool = True,
        workspace_root: Path | None = None,
        collaboration_context: dict | None = None,
        collaboration_context_provider=None,
        collaboration_write_coordinator=None,
        shell_timeout_mode: str = DEFAULT_SHELL_TIMEOUT_MODE,
        shell_async_handoff_seconds: int = DEFAULT_SHELL_ASYNC_HANDOFF_SECONDS,
        process_manager: UserProcessManager | None = None,
    ):
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)
        self.user_id = str(user_id or "")
        self.ollama_base = ollama_base
        self.model = model
        self.skills_root = skills_root
        self.js_lib_root = js_lib_root.resolve()
        self.js_lib_download_enabled = bool(js_lib_download_enabled)
        self.crypto = crypto
        self.repo_root = repo_root
        self.workspace_root = Path(workspace_root).resolve(strict=False) if workspace_root is not None else None
        self.collaboration_context = dict(collaboration_context or {})
        self.collaboration_context_provider = collaboration_context_provider
        self.collaboration_write_coordinator = collaboration_write_coordinator
        self.process_manager = process_manager
        self.thinking = False
        self.mcp_manager = mcp_manager
        self.default_llm_config = default_llm_config or {}
        self.context_token_limit = max(
            MIN_CONTEXT_TOKEN_LIMIT,
            min(TOKEN_THRESHOLD, int(context_token_limit or TOKEN_THRESHOLD)),
        )
        self.context_limit_locked = bool(context_limit_locked)
        self.max_rounds = max(
            MIN_AGENT_ROUNDS,
            min(MAX_AGENT_ROUNDS_CAP, int(max_rounds or MAX_AGENT_ROUNDS)),
        )
        self.max_output_tokens = max(256, int(max_output_tokens or AGENT_MAX_OUTPUT_TOKENS))
        self.max_run_seconds = normalize_timeout_seconds(
            max_run_seconds if max_run_seconds is not None else MAX_RUN_SECONDS,
            minimum=MIN_RUN_TIMEOUT_SECONDS,
            maximum=MAX_RUN_TIMEOUT_SECONDS,
            fallback=MAX_RUN_SECONDS,
        )
        self.shell_command_timeout_seconds = normalize_timeout_seconds(
            shell_command_timeout_seconds if shell_command_timeout_seconds is not None else DEFAULT_SHELL_COMMAND_TIMEOUT_SECONDS,
            minimum=MIN_SHELL_COMMAND_TIMEOUT_SECONDS,
            maximum=MAX_SHELL_COMMAND_TIMEOUT_SECONDS,
            fallback=DEFAULT_SHELL_COMMAND_TIMEOUT_SECONDS,
        )
        self.shell_timeout_mode = normalize_shell_timeout_mode(shell_timeout_mode)
        self.shell_async_handoff_seconds = normalize_timeout_seconds(
            shell_async_handoff_seconds,
            minimum=MIN_SHELL_ASYNC_HANDOFF_SECONDS,
            maximum=MAX_SHELL_ASYNC_HANDOFF_SECONDS,
            fallback=DEFAULT_SHELL_ASYNC_HANDOFF_SECONDS,
        )
        self.auto_task_level_ceiling = normalize_auto_task_level_ceiling(auto_task_level_ceiling)
        cfg_l2_todo_policy = extract_l2_todo_policy_setting(self.default_llm_config)
        self.l2_todo_policy = normalize_l2_todo_policy(
            l2_todo_policy if l2_todo_policy is not None else (cfg_l2_todo_policy or DEFAULT_L2_TODO_POLICY)
        )
        self.auto_model_switch = bool(auto_model_switch)
        self.arbiter_enabled = bool(arbiter_enabled)
        self.arbiter_model = str(arbiter_model or "").strip()
        self.arbiter_timeout_seconds = max(0.2, min(15.0, float(arbiter_timeout_seconds or ARBITER_DEFAULT_TIMEOUT_SECONDS)))
        self.arbiter_max_tokens = max(24, min(256, int(arbiter_max_tokens or ARBITER_DEFAULT_MAX_TOKENS)))
        self.arbiter_temperature = max(0.0, min(1.0, float(arbiter_temperature if arbiter_temperature is not None else ARBITER_DEFAULT_TEMPERATURE)))
        self.execution_mode = normalize_execution_mode(execution_mode, default=EXECUTION_MODE_SYNC)
        self.web_search_enabled = bool(web_search_enabled)
        self.web_search_setting_locked = bool(web_search_setting_locked)
        self.user_memory_mode = normalize_user_memory_mode(user_memory_mode)
        self.user_memory_setting_locked = bool(user_memory_setting_locked)
        self.telemetry_callback = None
        self.single_advance_prompt_enhance = False
        cfg_single_todo_enabled, cfg_single_todo_prompt = extract_single_no_plan_todo_settings(
            self.default_llm_config
        )
        self.single_no_plan_todo_enabled = bool(cfg_single_todo_enabled)
        self.single_no_plan_todo_prompt = str(cfg_single_todo_prompt or "").strip()
        self.read_context_policy = DEFAULT_READ_CONTEXT_POLICY
        self.tool_memory_policy = DEFAULT_TOOL_MEMORY_POLICY
        self.upload_callback = upload_callback
        self.reference_prepare_callback = reference_prepare_callback
        self.query_code_library_callback = query_code_library_callback
        self.query_knowledge_library_callback = query_knowledge_library_callback
        self.rag_remember_callback = rag_remember_callback
        self.code_library_root = code_library_root
        self.code_library_status_callback = code_library_status_callback
        self.knowledge_library_root = knowledge_library_root
        self.knowledge_library_status_callback = knowledge_library_status_callback
        # Keep manager creation cheap for the initial page.  Ollama discovery is
        # performed by model_catalog() when the model picker is actually loaded.
        self.ollama_env_available = False
        self.ollama_env_tags: list[str] = []
        self.run_finished_callback = run_finished_callback
        self.lock = threading.Lock()
        self.sessions: dict[str, SessionState] = {}
        self.session_index: dict[str, dict] = {}
        self.user_root = self.root.parent
        self.user_root.mkdir(parents=True, exist_ok=True)
        self.user_prefs_path = self.user_root / "user_prefs.json"
        self.user_memory_store = UserMemoryStore(self.user_root, user_id=self.user_id)
        self.user_interaction_optimizer = UserInteractionOptimizer()
        self.user_intent_profiler = UserIntentProfiler(self.user_memory_store, self.user_interaction_optimizer)
        self.user_model_profiles: dict[str, dict] = {}
        self.user_active_profile_id = ""
        self.global_llm_config_revision = ""
        self.global_llm_config_source = ""
        self.force_global_defaults_on_load = False
        self.collaboration_llm_independent = False
        self.collaboration_llm_source_revision = ""
        self.collaboration_llm_source_user_id = ""
        self.collaboration_llm_source_kind = ""
        self.user_language = normalize_ui_language(default_language)
        self._load_user_prefs()
        self._load_existing()

    def _profiles_from_config(self, config: dict) -> tuple[dict[str, dict], str]:
        parsed = parse_llm_config_profiles(config, self.ollama_base, self.model)
        profiles: dict[str, dict] = {}
        for idx, profile in enumerate(parsed.get("profiles", [])):
            pid = sanitize_profile_id(str(profile.get("id") or f"profile-{idx+1}"))
            if pid in profiles:
                n = 2
                while f"{pid}-{n}" in profiles:
                    n += 1
                pid = f"{pid}-{n}"
            row = dict(profile)
            row["id"] = pid
            row["selection"] = f"{pid}::{row.get('model','')}"
            profiles[pid] = row
        if not profiles:
            profiles["ollama"] = {
                "id": "ollama",
                "provider": "ollama",
                "label": "Ollama",
                "model": self.model,
                "base_url": self.ollama_base,
                "temperature": 0.2,
                "request_timeout": DEFAULT_REQUEST_TIMEOUT,
                "selection": f"ollama::{self.model}",
                "thinking_stream": False,
                "response_stream": False,
                "capabilities": infer_model_multimodal_capabilities("ollama", self.model),
                "media_endpoints": {},
                "source": "fallback",
            }
        requested = sanitize_profile_id(str(parsed.get("default_profile_id", "")))
        active = requested if requested in profiles else next(iter(profiles.keys()))
        return profiles, active

    def _active_profile(self) -> dict:
        return dict(self.user_model_profiles.get(self.user_active_profile_id, {}))

    def _sync_ollama_defaults(self, active_profile: dict | None = None):
        if not (isinstance(active_profile, dict) and str(active_profile.get("provider", "")).lower() == "ollama"):
            return
        picked = dict(active_profile)
        model = str(picked.get("model", self.model) or self.model).strip()
        base = extract_base_url(str(picked.get("base_url", self.ollama_base) or self.ollama_base)).strip()
        if model:
            self.model = model
        if base:
            self.ollama_base = base

    def _ensure_user_ollama_profile(self):
        for pid, profile in list(self.user_model_profiles.items()):
            if str(profile.get("provider", "")).lower() == "ollama":
                row = dict(profile)
                sid = sanitize_profile_id(str(row.get("id", pid) or pid))
                model = str(row.get("model", self.model) or self.model).strip()
                base = extract_base_url(str(row.get("base_url", self.ollama_base) or self.ollama_base)).strip()
                if model:
                    row["model"] = model
                if base:
                    row["base_url"] = base
                if not str(row.get("label", "")).strip():
                    row["label"] = "Ollama"
                row["id"] = sid
                row["selection"] = f"{sid}::{row.get('model','')}"
                self.user_model_profiles[sid] = row
                if sid != pid:
                    self.user_model_profiles.pop(pid, None)
                return
        if self.user_model_profiles:
            return
        self.user_model_profiles["ollama"] = {
            "id": "ollama",
            "provider": "ollama",
            "label": "Ollama",
            "model": self.model,
            "base_url": self.ollama_base,
            "temperature": 0.2,
            "request_timeout": DEFAULT_REQUEST_TIMEOUT,
            "selection": f"ollama::{self.model}",
            "capabilities": infer_model_multimodal_capabilities("ollama", self.model),
            "media_endpoints": {},
            "source": "fallback",
        }

    def _has_non_ollama_user_profiles(self) -> bool:
        for profile in self.user_model_profiles.values():
            if str((profile or {}).get("provider", "")).lower() != "ollama":
                return True
        return False

    def _persist_user_prefs(self):
        data = {
            "model_profiles": self.user_model_profiles,
            "active_profile_id": self.user_active_profile_id,
            "model": self.model,
            "ollama_base": self.ollama_base,
            "thinking": self.thinking,
            "ui_language": self.user_language,
            "read_context_policy": normalize_read_context_policy(
                getattr(self, "read_context_policy", DEFAULT_READ_CONTEXT_POLICY)
            ),
            "tool_memory_policy": normalize_tool_memory_policy(
                getattr(self, "tool_memory_policy", getattr(self, "read_context_policy", DEFAULT_TOOL_MEMORY_POLICY))
            ),
            "auto_task_level_ceiling": normalize_auto_task_level_ceiling(
                getattr(self, "auto_task_level_ceiling", DEFAULT_AUTO_TASK_LEVEL_CEILING)
            ),
            "l2_todo_policy": normalize_l2_todo_policy(
                getattr(self, "l2_todo_policy", DEFAULT_L2_TODO_POLICY)
            ),
            "single_no_plan_todo_enabled": bool(
                getattr(self, "single_no_plan_todo_enabled", False)
            ),
            "single_no_plan_todo_prompt": trim(
                str(getattr(self, "single_no_plan_todo_prompt", "") or ""),
                6000,
            ),
            "web_search_enabled": bool(getattr(self, "web_search_enabled", DEFAULT_WEB_SEARCH_ENABLED)),
            "user_memory_mode": normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE)),
            "global_llm_config_revision": str(getattr(self, "global_llm_config_revision", "") or ""),
            "global_llm_config_source": str(getattr(self, "global_llm_config_source", "") or ""),
            "collaboration_llm_independent": bool(
                getattr(self, "collaboration_llm_independent", False)
            ),
            "collaboration_llm_source_revision": str(
                getattr(self, "collaboration_llm_source_revision", "") or ""
            ),
            "collaboration_llm_source_user_id": str(
                getattr(self, "collaboration_llm_source_user_id", "") or ""
            ),
            "collaboration_llm_source_kind": str(
                getattr(self, "collaboration_llm_source_kind", "") or ""
            ),
            "updated_at": now_ts(),
        }
        self.crypto.write_json(self.user_prefs_path, data)

    def _prefer_ollama_profile_from_tags(self):
        if self._has_non_ollama_user_profiles():
            return
        tags = list_ollama_models_cached(self.ollama_base)
        if tags:
            self.ollama_env_tags = list(tags)
        elif self.ollama_env_tags:
            tags = list(self.ollama_env_tags)
        if not tags:
            return
        target_pid = ""
        for pid, profile in self.user_model_profiles.items():
            if str(profile.get("provider", "")).lower() == "ollama":
                target_pid = pid
                break
        if not target_pid:
            target_pid = "ollama"
            n = 2
            while target_pid in self.user_model_profiles:
                target_pid = f"ollama-{n}"
                n += 1
            self.user_model_profiles[target_pid] = {
                "id": target_pid,
                "provider": "ollama",
                "label": "Ollama",
                "model": tags[0],
                "base_url": self.ollama_base,
                "temperature": 0.2,
                "request_timeout": DEFAULT_REQUEST_TIMEOUT,
                "capabilities": infer_model_multimodal_capabilities("ollama", tags[0]),
                "media_endpoints": {},
                "source": "startup-autodetect",
            }
        profile = dict(self.user_model_profiles[target_pid])
        current = str(profile.get("model", "")).strip()
        profile["model"] = current if current in tags else tags[0]
        profile["base_url"] = self.ollama_base
        profile["selection"] = f"{target_pid}::{profile.get('model','')}"
        self.user_model_profiles[target_pid] = profile
        self.user_active_profile_id = target_pid

    def _load_user_prefs(self) -> bool:
        loaded = False
        if self.user_prefs_path.exists():
            raw = self.crypto.read_json(self.user_prefs_path, {})
            self.user_language = normalize_ui_language(raw.get("ui_language", self.user_language))
            self.read_context_policy = normalize_read_context_policy(
                raw.get("read_context_policy", getattr(self, "read_context_policy", DEFAULT_READ_CONTEXT_POLICY))
            )
            self.tool_memory_policy = normalize_tool_memory_policy(
                raw.get(
                    "tool_memory_policy",
                    raw.get("read_context_policy", getattr(self, "tool_memory_policy", DEFAULT_TOOL_MEMORY_POLICY)),
                )
            )
            raw_auto_task_level_ceiling = extract_auto_task_level_ceiling_setting(raw)
            self.auto_task_level_ceiling = normalize_auto_task_level_ceiling(
                raw_auto_task_level_ceiling
                if raw_auto_task_level_ceiling is not None
                else getattr(self, "auto_task_level_ceiling", DEFAULT_AUTO_TASK_LEVEL_CEILING)
            )
            cfg_l2_todo_policy = extract_l2_todo_policy_setting(raw)
            if cfg_l2_todo_policy is not None:
                self.l2_todo_policy = normalize_l2_todo_policy(cfg_l2_todo_policy)
            if _single_no_plan_todo_setting_present(raw):
                _single_todo_enabled, _single_todo_prompt = extract_single_no_plan_todo_settings(raw)
                self.single_no_plan_todo_enabled = bool(_single_todo_enabled)
                self.single_no_plan_todo_prompt = str(_single_todo_prompt or "").strip()
            if not bool(getattr(self, "web_search_setting_locked", False)) and "web_search_enabled" in raw:
                self.web_search_enabled = _to_bool_like(
                    raw.get("web_search_enabled"),
                    default=getattr(self, "web_search_enabled", DEFAULT_WEB_SEARCH_ENABLED),
                )
            if not bool(getattr(self, "user_memory_setting_locked", False)):
                raw_user_memory_mode = extract_user_memory_mode_setting(raw)
                if raw_user_memory_mode is not None:
                    self.user_memory_mode = normalize_user_memory_mode(raw_user_memory_mode)
            self.global_llm_config_revision = str(raw.get("global_llm_config_revision", "") or "")
            self.global_llm_config_source = str(raw.get("global_llm_config_source", "") or "")
            self.collaboration_llm_independent = bool(
                raw.get("collaboration_llm_independent", False)
            )
            self.collaboration_llm_source_revision = str(
                raw.get("collaboration_llm_source_revision", "") or ""
            )
            self.collaboration_llm_source_user_id = str(
                raw.get("collaboration_llm_source_user_id", "") or ""
            )
            self.collaboration_llm_source_kind = str(
                raw.get("collaboration_llm_source_kind", "") or ""
            )
            profiles = raw.get("model_profiles", {})
            if isinstance(profiles, dict) and profiles:
                for k, v in profiles.items():
                    if not isinstance(v, dict):
                        continue
                    pid = sanitize_profile_id(str(k))
                    row = dict(v)
                    row["id"] = pid
                    row["selection"] = f"{pid}::{row.get('model','')}"
                    self.user_model_profiles[pid] = row
                active = sanitize_profile_id(str(raw.get("active_profile_id", "")))
                if active in self.user_model_profiles:
                    self.user_active_profile_id = active
                loaded = bool(self.user_model_profiles)
        if not self.user_model_profiles:
            self.user_model_profiles, self.user_active_profile_id = self._profiles_from_config(self.default_llm_config)
        self._ensure_user_ollama_profile()
        # Do not probe Ollama while the initial session page is loading.  The
        # catalog path still discovers tags on demand and keeps this fallback
        # profile runnable with the configured model in the meantime.
        if self.user_active_profile_id not in self.user_model_profiles:
            self.user_active_profile_id = next(iter(self.user_model_profiles.keys()))
        self._ensure_user_active_runnable()
        active = self._active_profile()
        self._sync_ollama_defaults(active)
        self.thinking = False
        self._persist_user_prefs()
        return loaded

    def _preflight_user_ollama_profile(self):
        profile = self.user_model_profiles.get(self.user_active_profile_id, {})
        if str(profile.get("provider", "ollama")).lower() != "ollama":
            return
        base = str(profile.get("base_url", self.ollama_base) or self.ollama_base)
        tags = list_ollama_models_cached(base)
        if tags:
            self.ollama_env_tags = list(tags)
        elif self.ollama_env_tags:
            tags = list(self.ollama_env_tags)
        if not tags:
            return
        current = str(profile.get("model", "") or self.model)
        picked = current if current in tags else tags[0]
        profile["base_url"] = base
        profile["model"] = picked
        profile["selection"] = f"{self.user_active_profile_id}::{picked}"
        self.user_model_profiles[self.user_active_profile_id] = profile

    def _set_session_profile(self, sess: SessionState, profile_id: str, profile: dict):
        row = dict(profile)
        row["id"] = profile_id
        row["selection"] = f"{profile_id}::{row.get('model','')}"
        if not sess._profile_is_runnable(row):
            provider = str(row.get("provider", "") or "unknown")
            model = str(row.get("model", "") or "")
            raise ValueError(
                f"profile '{profile_id}' is not runnable (provider={provider}, model={model or '(empty)'})"
            )
        sess.model_profiles[profile_id] = row
        sess.active_profile_id = profile_id
        sess.failed_selections = []
        sess._apply_active_profile()
        sess.updated_at = now_ts()
        sess._persist()

    def _apply_user_defaults_to_session(self, sess: SessionState, *, clear_cap_cache: bool = False):
        sess.model_profiles = {}
        for pid, profile in self.user_model_profiles.items():
            row = dict(profile)
            row["id"] = pid
            row["selection"] = f"{pid}::{row.get('model','')}"
            sess.model_profiles[pid] = row
        preferred = ""
        if self.user_active_profile_id in sess.model_profiles:
            candidate = dict(sess.model_profiles.get(self.user_active_profile_id, {}))
            if sess._profile_is_runnable(candidate):
                preferred = self.user_active_profile_id
        if not preferred:
            for pid, profile in sess.model_profiles.items():
                if sess._profile_is_runnable(profile):
                    preferred = pid
                    break
        if preferred:
            sess.active_profile_id = preferred
        sess.failed_selections = []
        if clear_cap_cache:
            sess.multimodal_capability_cache = {}
            sess.ollama.clear_probe_cache()
        sess._set_ui_language(self.user_language, relabel_todos=True)
        sess.auto_model_switch = bool(self.auto_model_switch)
        sess.arbiter_enabled = bool(self.arbiter_enabled)
        sess.arbiter_model = str(self.arbiter_model or "").strip()
        sess.arbiter_timeout_seconds = max(
            0.2,
            min(15.0, float(self.arbiter_timeout_seconds or ARBITER_DEFAULT_TIMEOUT_SECONDS)),
        )
        sess.arbiter_max_tokens = max(24, min(256, int(self.arbiter_max_tokens or ARBITER_DEFAULT_MAX_TOKENS)))
        sess.arbiter_temperature = max(
            0.0,
            min(1.0, float(self.arbiter_temperature if self.arbiter_temperature is not None else ARBITER_DEFAULT_TEMPERATURE)),
        )
        sess.execution_mode = normalize_execution_mode(self.execution_mode, default=EXECUTION_MODE_SYNC)
        sess.single_advance_prompt_enhance = bool(self.single_advance_prompt_enhance)
        sess.single_no_plan_todo_enabled = bool(
            getattr(self, "single_no_plan_todo_enabled", False)
        )
        sess.single_no_plan_todo_prompt = str(
            getattr(self, "single_no_plan_todo_prompt", "") or ""
        ).strip()[:6000]
        sess.read_context_policy = normalize_read_context_policy(
            getattr(self, "read_context_policy", DEFAULT_READ_CONTEXT_POLICY)
        )
        sess.tool_memory_policy = normalize_tool_memory_policy(
            getattr(self, "tool_memory_policy", getattr(self, "read_context_policy", DEFAULT_TOOL_MEMORY_POLICY))
        )
        sess.auto_task_level_ceiling = normalize_auto_task_level_ceiling(
            getattr(self, "auto_task_level_ceiling", DEFAULT_AUTO_TASK_LEVEL_CEILING)
        )
        sess.l2_todo_policy = normalize_l2_todo_policy(
            getattr(self, "l2_todo_policy", DEFAULT_L2_TODO_POLICY)
        )
        sess.web_search_enabled = bool(getattr(self, "web_search_enabled", DEFAULT_WEB_SEARCH_ENABLED))
        sess.user_memory_mode = normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
        sess.shell_command_timeout_seconds = normalize_timeout_seconds(
            self.shell_command_timeout_seconds,
            minimum=MIN_SHELL_COMMAND_TIMEOUT_SECONDS,
            maximum=MAX_SHELL_COMMAND_TIMEOUT_SECONDS,
            fallback=DEFAULT_SHELL_COMMAND_TIMEOUT_SECONDS,
        )
        sess.shell_timeout_mode = normalize_shell_timeout_mode(self.shell_timeout_mode)
        sess.shell_async_handoff_seconds = normalize_timeout_seconds(
            self.shell_async_handoff_seconds,
            minimum=MIN_SHELL_ASYNC_HANDOFF_SECONDS,
            maximum=MAX_SHELL_ASYNC_HANDOFF_SECONDS,
            fallback=DEFAULT_SHELL_ASYNC_HANDOFF_SECONDS,
        )
        sess._apply_active_profile()
        sess.updated_at = now_ts()
        sess._persist()

    def _sync_from_session(self, sess: SessionState, *, apply_to_all: bool):
        synced: dict[str, dict] = {}
        for pid, profile in sess.model_profiles.items():
            row = dict(profile)
            sid = sanitize_profile_id(str(pid))
            row["id"] = sid
            row["selection"] = f"{sid}::{row.get('model','')}"
            synced[sid] = row
        if synced:
            self.user_model_profiles = synced
        self._ensure_user_ollama_profile()
        active = sanitize_profile_id(str(sess.active_profile_id))
        if active in self.user_model_profiles:
            self.user_active_profile_id = active
        elif self.user_model_profiles:
            self.user_active_profile_id = next(iter(self.user_model_profiles.keys()))
        self._ensure_user_active_runnable()
        active_profile = self._active_profile()
        self._sync_ollama_defaults(active_profile)
        self.thinking = False
        self.user_language = normalize_ui_language(getattr(sess, "ui_language", self.user_language))
        self.single_no_plan_todo_enabled = bool(
            getattr(sess, "single_no_plan_todo_enabled", getattr(self, "single_no_plan_todo_enabled", False))
        )
        self.single_no_plan_todo_prompt = str(
            getattr(sess, "single_no_plan_todo_prompt", getattr(self, "single_no_plan_todo_prompt", ""))
            or ""
        ).strip()[:6000]
        self.read_context_policy = normalize_read_context_policy(
            getattr(sess, "read_context_policy", getattr(self, "read_context_policy", DEFAULT_READ_CONTEXT_POLICY))
        )
        self.tool_memory_policy = normalize_tool_memory_policy(
            getattr(
                sess,
                "tool_memory_policy",
                getattr(self, "tool_memory_policy", getattr(self, "read_context_policy", DEFAULT_TOOL_MEMORY_POLICY)),
            )
        )
        self.auto_task_level_ceiling = normalize_auto_task_level_ceiling(
            getattr(
                sess,
                "auto_task_level_ceiling",
                getattr(self, "auto_task_level_ceiling", DEFAULT_AUTO_TASK_LEVEL_CEILING),
            )
        )
        self.l2_todo_policy = normalize_l2_todo_policy(
            getattr(sess, "l2_todo_policy", getattr(self, "l2_todo_policy", DEFAULT_L2_TODO_POLICY))
        )
        if bool(getattr(self, "web_search_setting_locked", False)):
            set_web_search_enabled_on_runtime(sess, self.web_search_enabled, persist=True)
        else:
            self.web_search_enabled = bool(
                getattr(sess, "web_search_enabled", getattr(self, "web_search_enabled", DEFAULT_WEB_SEARCH_ENABLED))
            )
        if bool(getattr(self, "user_memory_setting_locked", False)):
            sess.user_memory_mode = normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
        else:
            self.user_memory_mode = normalize_user_memory_mode(
                getattr(sess, "user_memory_mode", getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
            )
        self._persist_user_prefs()
        if not apply_to_all:
            return
        for other in self.sessions.values():
            if other.id == sess.id:
                continue
            self._apply_user_defaults_to_session(other, clear_cap_cache=True)

    def prepare_user_intent_for_session(self, sess: SessionState, content: str) -> dict:
        mode = normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
        if mode == "off":
            sess.user_memory_mode = "off"
            sess.user_profile_capsule = ""
            sess.user_profile_capsule_meta = {"mode": "off", "memory_count": 0}
            return {"ok": True, "mode": "off", "capsule_chars": 0, "memory_count": 0}
        try:
            out = self.user_intent_profiler.prepare_session(sess, content, mode)
            sess.user_memory_mode = mode
            sess.updated_at = now_ts()
            # The immediately following submit path persists the complete
            # request state. Avoid a second full encrypted state write here.
            return out
        except Exception as exc:
            sess.user_profile_capsule = ""
            sess.user_profile_capsule_meta = {"mode": mode, "error": trim(str(exc), 160)}
            return {"ok": False, "mode": mode, "error": trim(str(exc), 200)}

    def capture_user_memory_from_session(self, sess: SessionState) -> dict:
        mode = normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
        if mode == "off":
            return {"ok": True, "skipped": True, "mode": "off"}
        try:
            return self.user_memory_store.capture_session(sess, mode=mode)
        except Exception as exc:
            return {"ok": False, "error": trim(str(exc), 220)}

    def user_memory_payload(self, *, limit: int = 80) -> dict:
        payload = self.user_memory_store.payload(limit=limit)
        payload["user_memory_mode"] = normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
        payload["setting_locked"] = bool(getattr(self, "user_memory_setting_locked", False))
        return payload

    def user_memory_export_payload(self) -> dict:
        payload = self.user_memory_store.export_payload()
        payload["user_memory_mode"] = normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE))
        return payload

    def clear_user_memory(self) -> dict:
        return self.user_memory_store.clear()

    def set_user_memory_mode(self, mode: str) -> dict:
        if bool(getattr(self, "user_memory_setting_locked", False)):
            return {
                "ok": False,
                "locked": True,
                "user_memory_mode": normalize_user_memory_mode(getattr(self, "user_memory_mode", DEFAULT_USER_MEMORY_MODE)),
                "error": "user memory mode is locked by startup argument",
            }
        self.user_memory_mode = normalize_user_memory_mode(mode)
        for sess in list(self.sessions.values()):
            try:
                sess.user_memory_mode = self.user_memory_mode
                if self.user_memory_mode == "off":
                    sess.user_profile_capsule = ""
                    sess.user_profile_capsule_meta = {"mode": "off", "memory_count": 0}
                sess.updated_at = now_ts()
                sess._persist()
            except Exception:
                pass
        self._persist_user_prefs()
        return {"ok": True, "user_memory_mode": self.user_memory_mode}

    def _session_summary_from_disk(self, path: Path) -> dict:
        sid = str(path.name or "").strip()
        title = sid
        updated_at = 0.0
        message_count = 0
        ui_language = self.user_language
        meta = path / "meta.json"
        if meta.exists():
            try:
                raw = self.crypto.read_json(meta, {})
                if isinstance(raw, dict):
                    title = str(raw.get("title", sid) or sid)
                    updated_at = float(raw.get("updated_at", 0.0) or 0.0)
                    message_count = max(0, int(raw.get("message_count", 0) or 0))
                    ui_language = normalize_ui_language(raw.get("ui_language", ui_language))
            except Exception:
                pass
        if updated_at <= 0:
            try:
                state = path / "state.json"
                updated_at = float((state if state.exists() else path).stat().st_mtime)
            except Exception:
                updated_at = 0.0
        return {
            "id": sid,
            "title": title,
            "running": False,
            "degraded": False,
            "recovered_at": 0.0,
            "recovered_reason": "",
            "ui_language": ui_language,
            "updated_at": float(updated_at or 0.0),
            "message_count": int(message_count),
            "loaded": False,
        }

    def _make_session_state(self, sid: str, title: str) -> SessionState:
        sess = SessionState(
                session_id=sid,
                title=title,
                root=self.root,
                ollama_base=self.ollama_base,
                model=self.model,
                skills_root=self.skills_root,
                crypto=self.crypto,
                repo_root=self.repo_root,
                thinking=self.thinking,
                default_llm_config=self.default_llm_config,
                context_token_limit=self.context_token_limit,
                context_limit_locked=self.context_limit_locked,
                max_rounds=self.max_rounds,
                max_run_seconds=self.max_run_seconds,
                shell_command_timeout_seconds=self.shell_command_timeout_seconds,
                auto_task_level_ceiling=self.auto_task_level_ceiling,
                l2_todo_policy=self.l2_todo_policy,
                auto_model_switch=self.auto_model_switch,
                arbiter_enabled=self.arbiter_enabled,
                arbiter_model=self.arbiter_model,
                arbiter_timeout_seconds=self.arbiter_timeout_seconds,
                arbiter_max_tokens=self.arbiter_max_tokens,
                arbiter_temperature=self.arbiter_temperature,
                execution_mode=self.execution_mode,
                max_output_tokens=self.max_output_tokens,
                web_search_enabled=self.web_search_enabled,
                ui_language=self.user_language,
                js_lib_root=self.js_lib_root,
                js_lib_download_enabled=self.js_lib_download_enabled,
                owner_user_id=self.user_id,
                upload_callback=self.upload_callback,
                run_finished_callback=self.run_finished_callback,
                reference_prepare_callback=self.reference_prepare_callback,
                query_code_library_callback=self.query_code_library_callback,
                query_knowledge_library_callback=self.query_knowledge_library_callback,
                rag_remember_callback=self.rag_remember_callback,
                code_library_root=self.code_library_root,
                code_library_status_callback=self.code_library_status_callback,
                knowledge_library_root=self.knowledge_library_root,
                knowledge_library_status_callback=self.knowledge_library_status_callback,
                mcp_manager=getattr(self, "mcp_manager", None),
                workspace_root=self.workspace_root,
                collaboration_context=self.collaboration_context,
                collaboration_context_provider=self.collaboration_context_provider,
                collaboration_write_coordinator=self.collaboration_write_coordinator,
                shell_timeout_mode=self.shell_timeout_mode,
                shell_async_handoff_seconds=self.shell_async_handoff_seconds,
                process_manager=self.process_manager,
            )
        sess.set_telemetry_callback(self.telemetry_callback)
        desired_mode = normalize_execution_mode(self.execution_mode, default=EXECUTION_MODE_SYNC)
        if normalize_execution_mode(getattr(sess, "execution_mode", ""), default=desired_mode) != desired_mode:
            sess.execution_mode = desired_mode
            sess.updated_at = now_ts()
            sess._persist()
        if bool(getattr(self, "force_global_defaults_on_load", False)):
            self._apply_user_defaults_to_session(sess, clear_cap_cache=True)
        elif not sess.model_profiles:
            self._apply_user_defaults_to_session(sess)
        return sess

    def _load_existing(self):
        for path in sorted(self.root.glob("*")):
            if not path.is_dir():
                continue
            sid = str(path.name or "").strip()
            if not sid:
                continue
            self.session_index[sid] = self._session_summary_from_disk(path)

    def _load_session_locked(self, session_id: str) -> SessionState | None:
        sid = str(session_id or "").strip()
        if not sid:
            return None
        existing = self.sessions.get(sid)
        if existing:
            return existing
        session_dir = self.root / sid
        if not session_dir.exists() or not session_dir.is_dir():
            return None
        summary = self.session_index.get(sid) or self._session_summary_from_disk(session_dir)
        title = str(summary.get("title", sid) or sid)
        sess = self._make_session_state(sid, title)
        self.sessions[sid] = sess
        self.session_index[sid] = {
            **summary,
            "title": str(getattr(sess, "title", title) or title),
            "running": bool(getattr(sess, "running", False)),
            "recovered_at": float(getattr(sess, "run_recovered_at", 0.0) or 0.0),
            "recovered_reason": str(getattr(sess, "run_recovered_reason", "") or ""),
            "ui_language": normalize_ui_language(getattr(sess, "ui_language", self.user_language)),
            "updated_at": float(getattr(sess, "updated_at", summary.get("updated_at", 0.0)) or 0.0),
            "message_count": int(self._session_message_count(sess)),
            "loaded": True,
        }
        return sess

    def _session_message_count(self, sess: SessionState) -> int:
        try:
            count = sum(
                1 for row in getattr(sess, "messages", [])
                if isinstance(row, dict) and str(row.get("role", "")).strip() != "tool"
            )
            count += sum(
                1 for row in getattr(sess, "scheduler_visible_inputs", [])
                if isinstance(row, dict) and str(row.get("content", "") or "").strip()
            )
            return max(0, int(count))
        except Exception:
            return 0

    def create(self, title: str | None = None) -> SessionState:
        with self.lock:
            sid = make_id("sess")
            name = title.strip() if title else sid
            sess = SessionState(
                session_id=sid,
                title=name,
                root=self.root,
                ollama_base=self.ollama_base,
                model=self.model,
                skills_root=self.skills_root,
                crypto=self.crypto,
                repo_root=self.repo_root,
                thinking=self.thinking,
                default_llm_config=self.default_llm_config,
                context_token_limit=self.context_token_limit,
                context_limit_locked=self.context_limit_locked,
                max_rounds=self.max_rounds,
                max_run_seconds=self.max_run_seconds,
                shell_command_timeout_seconds=self.shell_command_timeout_seconds,
                auto_task_level_ceiling=self.auto_task_level_ceiling,
                l2_todo_policy=self.l2_todo_policy,
                auto_model_switch=self.auto_model_switch,
                arbiter_enabled=self.arbiter_enabled,
                arbiter_model=self.arbiter_model,
                arbiter_timeout_seconds=self.arbiter_timeout_seconds,
                arbiter_max_tokens=self.arbiter_max_tokens,
                arbiter_temperature=self.arbiter_temperature,
                execution_mode=self.execution_mode,
                max_output_tokens=self.max_output_tokens,
                web_search_enabled=self.web_search_enabled,
                ui_language=self.user_language,
                js_lib_root=self.js_lib_root,
                js_lib_download_enabled=self.js_lib_download_enabled,
                owner_user_id=self.user_id,
                upload_callback=self.upload_callback,
                run_finished_callback=self.run_finished_callback,
                reference_prepare_callback=self.reference_prepare_callback,
                query_code_library_callback=self.query_code_library_callback,
                query_knowledge_library_callback=self.query_knowledge_library_callback,
                rag_remember_callback=self.rag_remember_callback,
                code_library_root=self.code_library_root,
                code_library_status_callback=self.code_library_status_callback,
                knowledge_library_root=self.knowledge_library_root,
                knowledge_library_status_callback=self.knowledge_library_status_callback,
                mcp_manager=getattr(self, "mcp_manager", None),
                workspace_root=self.workspace_root,
                collaboration_context=self.collaboration_context,
                collaboration_context_provider=self.collaboration_context_provider,
                collaboration_write_coordinator=self.collaboration_write_coordinator,
                shell_timeout_mode=self.shell_timeout_mode,
                shell_async_handoff_seconds=self.shell_async_handoff_seconds,
                process_manager=self.process_manager,
            )
            sess.set_telemetry_callback(self.telemetry_callback)
            self._apply_user_defaults_to_session(sess)
            self.sessions[sid] = sess
            self.session_index[sid] = {
                "id": sid,
                "title": str(getattr(sess, "title", name) or name),
                "running": bool(getattr(sess, "running", False)),
                "degraded": False,
                "recovered_at": float(getattr(sess, "run_recovered_at", 0.0) or 0.0),
                "recovered_reason": str(getattr(sess, "run_recovered_reason", "") or ""),
                "ui_language": normalize_ui_language(getattr(sess, "ui_language", self.user_language)),
                "updated_at": float(getattr(sess, "updated_at", now_ts()) or now_ts()),
                "message_count": int(self._session_message_count(sess)),
                "loaded": True,
            }
            return sess

    def get(self, session_id: str) -> SessionState | None:
        with self.lock:
            return self._load_session_locked(session_id)

    def rename(self, session_id: str, title: str) -> SessionState:
        with self.lock:
            sess = self._load_session_locked(session_id)
            if not sess:
                raise KeyError(session_id)
            sess.title = title.strip() or sess.id
            sess.title_origin = "manual"
            sess.last_auto_title_source = ""
            sess.updated_at = now_ts()
            sess._persist()
            row = dict(self.session_index.get(sess.id, {}))
            row.update({
                "id": sess.id,
                "title": sess.title,
                "updated_at": float(sess.updated_at or now_ts()),
                "message_count": int(self._session_message_count(sess)),
                "loaded": True,
            })
            self.session_index[sess.id] = row
            return sess

    def delete(self, session_id: str) -> bool:
        sid = str(session_id or "").strip()
        if not sid:
            return False
        with self.lock:
            sess = self.sessions.pop(sid, None)
            existed = bool(sess or sid in self.session_index or (self.root / sid).exists())
            self.session_index.pop(sid, None)
        if not existed:
            return False
        if sess:
            # Note: sess.mcp is the SHARED global manager — never shut it down on
            # per-session delete (that would kill MCP for all other sessions).
            sess.interrupt()
            shutil.rmtree(sess.root, ignore_errors=True)
        else:
            shutil.rmtree(self.root / sid, ignore_errors=True)
        return True

    def _user_profile_is_runnable(self, profile: dict) -> bool:
        if not isinstance(profile, dict):
            return False
        provider = str(profile.get("provider", "") or "").strip().lower()
        model = str(profile.get("model", "") or "").strip()
        if provider in {"", "unknown", "config_only"}:
            return False
        if not model:
            return False
        if provider == "ollama":
            base = str(profile.get("base_url", self.ollama_base) or self.ollama_base).strip()
            return bool(base)
        if is_openai_compat_provider(provider):
            endpoint = str(profile.get("endpoint", "") or "").strip()
            base = str(profile.get("base_url", "") or "").strip()
            return bool(endpoint or complete_chat_endpoint(base))
        if provider == "custom_http":
            return bool(str(profile.get("endpoint", "") or "").strip())
        if provider == "anthropic":
            api_key = str(profile.get("api_key", "") or "").strip()
            endpoint = str(profile.get("endpoint", "") or "").strip()
            base = str(profile.get("base_url", "") or "").strip()
            return bool(api_key and (endpoint or base))
        return False

    def _option_is_runnable(self, option: dict) -> bool:
        if not isinstance(option, dict):
            return False
        pid = str(option.get("profile_id", "") or "")
        profile = dict(self.user_model_profiles.get(pid, {}))
        if option.get("provider") is not None:
            profile["provider"] = option.get("provider")
        if option.get("model") is not None:
            profile["model"] = option.get("model")
        if str(profile.get("provider", "")).lower() == "ollama" and not str(profile.get("base_url", "")).strip():
            profile["base_url"] = self.ollama_base
        return self._user_profile_is_runnable(profile)

    def _ensure_user_active_runnable(self):
        active = self._active_profile()
        if self._user_profile_is_runnable(active):
            return
        for pid, profile in self.user_model_profiles.items():
            if self._user_profile_is_runnable(profile):
                self.user_active_profile_id = pid
                return

    def _probe_user_active_capabilities(self, force_probe: bool = False):
        profile = self._active_profile()
        if not profile or not self._user_profile_is_runnable(profile):
            return
        client = OllamaClient(
            str(profile.get("base_url", self.ollama_base) or self.ollama_base),
            str(profile.get("model", self.model) or self.model),
            int(profile.get("request_timeout", DEFAULT_REQUEST_TIMEOUT) or DEFAULT_REQUEST_TIMEOUT),
            provider=str(profile.get("provider", "ollama") or "ollama"),
            endpoint=str(profile.get("endpoint", "") or ""),
            api_key=str(profile.get("api_key", "") or ""),
            headers=profile.get("headers", {}) if isinstance(profile.get("headers"), dict) else {},
            payload_template=str(profile.get("payload_template", "") or ""),
            thinking_stream=bool(profile.get("thinking_stream", False)),
            response_stream=bool(profile.get("response_stream", False)),
        )
        client.apply_profile(profile)
        client.set_telemetry(self.telemetry_callback, context_provider=lambda: {}, name="capability_probe")
        caps = client.probe_multimodal_capabilities(force=True if force_probe else False)
        merged = merge_multimodal_capabilities(
            merge_multimodal_capabilities(
                infer_model_multimodal_capabilities(str(profile.get("provider", "")), str(profile.get("model", ""))),
                parse_capability_overrides(profile.get("capabilities", {})),
            ),
            caps,
        )
        profile["capabilities"] = merged
        self.user_model_profiles[self.user_active_profile_id] = profile
        self._persist_user_prefs()
        probe_entry = client.probe_cache_entry()
        probe_details = probe_entry.get("details", {}) if isinstance(probe_entry, dict) else {}
        probe_updated_at = float(
            (probe_entry.get("updated_at", now_ts()) if isinstance(probe_entry, dict) else now_ts()) or now_ts()
        )
        for sess in self.sessions.values():
            if self.user_active_profile_id not in sess.model_profiles:
                continue
            row = dict(sess.model_profiles[self.user_active_profile_id])
            row["capabilities"] = merged
            sess.model_profiles[self.user_active_profile_id] = row
            cache_key = sess._profile_cache_key(row)
            sess.multimodal_capability_cache[cache_key] = {
                "capabilities": merged,
                "details": probe_details if isinstance(probe_details, dict) else {},
                "updated_at": probe_updated_at,
                "provider": str(row.get("provider", "")),
                "model": str(row.get("model", "")),
            }
            if sess.active_profile_id == self.user_active_profile_id:
                sess.ollama.apply_profile(row)
            sess.updated_at = now_ts()
            sess._persist()

    def model_catalog(self, force_probe: bool = False) -> dict:
        if force_probe:
            try:
                self._probe_user_active_capabilities(force_probe=True)
            except Exception:
                pass
        opts = []
        ollama_profile_id = ""
        ollama_base = self.ollama_base
        for pid, profile in sorted(self.user_model_profiles.items(), key=lambda x: x[0]):
            model = str(profile.get("model", "") or "")
            caps = merge_multimodal_capabilities(
                infer_model_multimodal_capabilities(str(profile.get("provider", "")), model),
                parse_capability_overrides(profile.get("capabilities", {})),
            )
            if (not ollama_profile_id) and str(profile.get("provider", "")).lower() == "ollama":
                ollama_profile_id = pid
                ollama_base = str(profile.get("base_url", ollama_base) or ollama_base)
            opts.append(
                {
                    "selection": f"{pid}::{model}",
                    "profile_id": pid,
                    "provider": profile.get("provider", "unknown"),
                    "model": model,
                    "label": f"{profile.get('label', pid)} | {model or '(no-model)'}",
                    "source": profile.get("source", ""),
                    "thinking_hint": bool(profile.get("thinking_hint", False)),
                    "thinking_stream": bool(profile.get("thinking_stream", False)),
                    "response_stream": bool(profile.get("response_stream", False)),
                    "capabilities": caps,
                }
            )
        if not ollama_profile_id:
            ollama_profile_id = "ollama"
        seen = {str(x.get("selection", "")) for x in opts}
        for pid, profile in sorted(self.user_model_profiles.items(), key=lambda x: x[0]):
            if str(profile.get("provider", "")).lower() != "ollama":
                continue
            base = str(profile.get("base_url", self.ollama_base) or self.ollama_base).strip()
            if not base:
                continue
            tags = list_ollama_models_cached(base, force_refresh=bool(force_probe))
            if tags:
                if pid == self.user_active_profile_id:
                    self.ollama_env_tags = list(tags)
            elif pid == self.user_active_profile_id and self.ollama_env_tags:
                tags = list(self.ollama_env_tags)
            for tag in tags:
                selection = f"{pid}::{tag}"
                if selection in seen:
                    continue
                seen.add(selection)
                tag_caps = merge_multimodal_capabilities(
                    infer_model_multimodal_capabilities("ollama", tag),
                    parse_capability_overrides(profile.get("capabilities", {})),
                )
                opts.append(
                    {
                        "selection": selection,
                        "profile_id": pid,
                        "provider": "ollama",
                        "model": tag,
                        "label": f"{profile.get('label', 'Ollama')} | {tag}",
                        "source": "ollama-tags",
                        "thinking_hint": bool(profile.get("thinking_hint", self.thinking)),
                        "thinking_stream": bool(profile.get("thinking_stream", False)),
                        "response_stream": bool(profile.get("response_stream", False)),
                        "capabilities": tag_caps,
                    }
                )
        runnable_opts = [x for x in opts if self._option_is_runnable(x)]
        if runnable_opts:
            opts = runnable_opts
        active = self.user_model_profiles.get(self.user_active_profile_id, {})
        selected = f"{self.user_active_profile_id}::{active.get('model','')}" if active else ""
        option_map = {str(x.get("selection", "")) for x in opts}
        if active and selected and selected not in option_map:
            active_caps = merge_multimodal_capabilities(
                infer_model_multimodal_capabilities(str(active.get("provider", "")), str(active.get("model", ""))),
                parse_capability_overrides(active.get("capabilities", {})),
            )
            opts.insert(
                0,
                {
                    "selection": selected,
                    "profile_id": self.user_active_profile_id,
                    "provider": active.get("provider", "unknown"),
                    "model": str(active.get("model", "") or ""),
                    "label": f"{active.get('label', self.user_active_profile_id)} | {str(active.get('model', '') or '(no-model)')}",
                    "source": active.get("source", "active-profile"),
                    "thinking_hint": bool(active.get("thinking_hint", False)),
                    "thinking_stream": bool(active.get("thinking_stream", False)),
                    "response_stream": bool(active.get("response_stream", False)),
                    "capabilities": active_caps,
                },
            )
            option_map.add(selected)
        if opts and selected not in option_map:
            selected = str(opts[0].get("selection", ""))
        active_caps = merge_multimodal_capabilities(
            infer_model_multimodal_capabilities(str(active.get("provider", "")), str(active.get("model", ""))),
            parse_capability_overrides(active.get("capabilities", {})),
        )
        return {
            "provider": active.get("provider", "ollama"),
            "models": [x["selection"] for x in opts] or [self.model],
            "options": opts,
            "selected": selected,
            "thinking": self.thinking,
            "response_stream": bool(active.get("response_stream", False)),
            "thinking_mode": "auto",
            "active_capabilities": active_caps,
        }

    def set_runtime_model(self, model: str, thinking: bool | None = None) -> dict:
        raw = str(model or "").strip()
        if not raw:
            raise ValueError("model required")
        explicit_profile = "::" in raw
        if "::" in raw:
            pid, selected_model = raw.split("::", 1)
        else:
            pid, selected_model = self.user_active_profile_id, raw
        pid = sanitize_profile_id(pid)
        with self.lock:
            profile = dict(self.user_model_profiles.get(pid, {}))
            if not profile:
                if pid.startswith("ollama"):
                    profile = {
                        "id": pid,
                        "provider": "ollama",
                        "label": "Ollama",
                        "model": selected_model or self.model,
                        "base_url": self.ollama_base,
                        "capabilities": infer_model_multimodal_capabilities("ollama", selected_model or self.model),
                        "media_endpoints": {},
                        "source": "runtime",
                    }
                else:
                    raise ValueError(f"profile not found: {pid}")
            if selected_model.strip():
                profile["model"] = selected_model.strip()
            if str(profile.get("provider", "")).lower() == "ollama" and selected_model.strip():
                profile["capabilities"] = infer_model_multimodal_capabilities("ollama", selected_model.strip())
            if not self._user_profile_is_runnable(profile) and not explicit_profile and selected_model.strip():
                fallback_pid = ""
                for xpid, xprofile in self.user_model_profiles.items():
                    if str(xprofile.get("provider", "")).lower() == "ollama" and self._user_profile_is_runnable(xprofile):
                        fallback_pid = xpid
                        break
                if not fallback_pid:
                    for xpid, xprofile in self.user_model_profiles.items():
                        if self._user_profile_is_runnable(xprofile):
                            fallback_pid = xpid
                            break
                if fallback_pid:
                    pid = fallback_pid
                    profile = dict(self.user_model_profiles[fallback_pid])
                    profile["model"] = selected_model.strip()
            if not self._user_profile_is_runnable(profile):
                provider = str(profile.get("provider", "") or "unknown")
                model_text = str(profile.get("model", "") or "")
                raise ValueError(
                    f"profile '{pid}' is not runnable (provider={provider}, model={model_text or '(empty)'})"
                )
            profile["id"] = pid
            profile["selection"] = f"{pid}::{profile.get('model','')}"
            self.user_model_profiles[pid] = profile
            self.user_active_profile_id = pid
            self._sync_ollama_defaults(profile)
            self.thinking = False
            try:
                self._probe_user_active_capabilities(force_probe=False)
            except Exception:
                pass
            self._persist_user_prefs()
            for sess in self.sessions.values():
                try:
                    self._set_session_profile(sess, pid, profile)
                except Exception:
                    sess.ollama.model = self.model
                    sess.thinking = False
                    sess.updated_at = now_ts()
                    sess._persist()
            return self.model_catalog()

    def apply_llm_config(self, session_id: str, config: dict, source: str = "") -> dict:
        with self.lock:
            sess = self._load_session_locked(session_id)
            if not sess:
                raise KeyError(session_id)
            catalog = sess.load_llm_config(config, source=source)
            if bool(getattr(self, "web_search_setting_locked", False)):
                set_web_search_enabled_on_runtime(sess, self.web_search_enabled, persist=True)
            self._sync_from_session(sess, apply_to_all=True)
            return catalog

    def reset_to_llm_config(self, config: dict, source: str = "") -> dict:
        cfg = dict(config or {})
        OllamaClient.clear_global_probe_cache()
        profiles, active = self._profiles_from_config(cfg)
        with self.lock:
            normalized: dict[str, dict] = {}
            for pid, row in profiles.items():
                item = dict(row)
                item["id"] = sanitize_profile_id(str(pid))
                item["selection"] = f"{item['id']}::{item.get('model','')}"
                if source:
                    item["source"] = source
                normalized[item["id"]] = item
            self.default_llm_config = cfg
            self.user_model_profiles = normalized or self.user_model_profiles
            if active in self.user_model_profiles:
                self.user_active_profile_id = active
            elif self.user_model_profiles:
                self.user_active_profile_id = next(iter(self.user_model_profiles.keys()))
            self._ensure_user_ollama_profile()
            self._preflight_user_ollama_profile()
            self._ensure_user_active_runnable()
            active_profile = self._active_profile()
            self._sync_ollama_defaults(active_profile)
            self.thinking = False
            if _single_no_plan_todo_setting_present(cfg):
                _single_todo_enabled, _single_todo_prompt = extract_single_no_plan_todo_settings(cfg)
                self.single_no_plan_todo_enabled = bool(_single_todo_enabled)
                self.single_no_plan_todo_prompt = str(_single_todo_prompt or "").strip()
            cfg_read_context_policy = extract_read_context_policy_setting(cfg)
            if cfg_read_context_policy:
                self.read_context_policy = cfg_read_context_policy
            cfg_tool_memory_policy = extract_tool_memory_policy_setting(cfg)
            if cfg_tool_memory_policy:
                self.tool_memory_policy = cfg_tool_memory_policy
            cfg_auto_task_level_ceiling = extract_auto_task_level_ceiling_setting(cfg)
            if cfg_auto_task_level_ceiling is not None:
                self.auto_task_level_ceiling = normalize_auto_task_level_ceiling(cfg_auto_task_level_ceiling)
            cfg_l2_todo_policy = extract_l2_todo_policy_setting(cfg)
            if cfg_l2_todo_policy is not None:
                self.l2_todo_policy = normalize_l2_todo_policy(cfg_l2_todo_policy)
            cfg_web_search_enabled = extract_web_search_enabled_setting(cfg)
            if cfg_web_search_enabled is not None and not bool(getattr(self, "web_search_setting_locked", False)):
                self.web_search_enabled = bool(cfg_web_search_enabled)
            cfg_user_memory_mode = extract_user_memory_mode_setting(cfg)
            if cfg_user_memory_mode is not None and not bool(getattr(self, "user_memory_setting_locked", False)):
                self.user_memory_mode = normalize_user_memory_mode(cfg_user_memory_mode)
            self._persist_user_prefs()
            for sess in self.sessions.values():
                self._apply_user_defaults_to_session(sess, clear_cap_cache=True)
        return self.model_catalog()

    def set_user_language(self, language: str) -> dict:
        lang = normalize_ui_language(language)
        with self.lock:
            self.user_language = lang
            for sess in self.sessions.values():
                sess._set_ui_language(lang, relabel_todos=True)
                sess.updated_at = now_ts()
                sess._persist()
            self._persist_user_prefs()
        return {"ok": True, "language": lang}

    def set_session_language(self, session_id: str, language: str, set_user_default: bool = False) -> dict:
        lang = normalize_ui_language(language)
        with self.lock:
            sess = self._load_session_locked(session_id)
            if not sess:
                raise KeyError(session_id)
            sess._set_ui_language(lang, relabel_todos=True)
            sess.updated_at = now_ts()
            sess._persist()
            row = dict(self.session_index.get(sess.id, {}))
            row.update({
                "id": sess.id,
                "title": str(getattr(sess, "title", sess.id) or sess.id),
                "ui_language": normalize_ui_language(getattr(sess, "ui_language", lang)),
                "updated_at": float(getattr(sess, "updated_at", now_ts()) or now_ts()),
                "message_count": int(self._session_message_count(sess)),
                "loaded": True,
            })
            self.session_index[sess.id] = row
            if set_user_default:
                self.user_language = lang
                self._persist_user_prefs()
        return {"ok": True, "session_id": session_id, "language": lang, "set_user_default": bool(set_user_default)}

    def import_default_llm_config(self, session_id: str) -> dict:
        cfg = parse_json_object(try_read_text(LLM_CONFIG_PATH) or "{}", {})
        if not cfg:
            raise FileNotFoundError(f"missing or invalid config: {LLM_CONFIG_PATH}")
        return self.apply_llm_config(session_id, cfg, source=str(LLM_CONFIG_PATH))

    def list(self, *, limit: int | None = None, offset: int = 0, search: str = "", status: str = "") -> list[dict] | dict:
        with self.lock:
            rows_by_id = {str(k): dict(v) for k, v in self.session_index.items() if isinstance(v, dict)}
            loaded_sessions = list(self.sessions.values())
            for sess in loaded_sessions:
                sid = str(getattr(sess, "id", "") or "")
                if not sid:
                    continue
                # Session summaries are a hot path for both IDE polling and the
                # traditional session list. Never lock a live session or rescan its
                # complete message history here. Mutations update the index through
                # the normal manager APIs; the selected session's live snapshot is
                # responsible for immediate message-count updates in the UI.
                cached = rows_by_id.get(sid, {})
                rows_by_id[sid] = {
                    **cached,
                    "id": sid,
                    "title": str(getattr(sess, "title", "") or cached.get("title", sid) or sid),
                    "running": bool(getattr(sess, "running", cached.get("running", False))),
                    "degraded": False,
                    "recovered_at": float(getattr(sess, "run_recovered_at", cached.get("recovered_at", 0.0)) or 0.0),
                    "recovered_reason": str(getattr(sess, "run_recovered_reason", cached.get("recovered_reason", "")) or ""),
                    "ui_language": normalize_ui_language(getattr(sess, "ui_language", cached.get("ui_language", self.user_language))),
                    "updated_at": float(getattr(sess, "updated_at", cached.get("updated_at", 0.0)) or 0.0),
                    "message_count": int(cached.get("message_count", 0) or 0),
                    "loaded": True,
                }
        rows: list[dict] = []
        needle = str(search or "").strip().lower()
        status_key = str(status or "").strip().lower()
        for raw in rows_by_id.values():
            sid = str(raw.get("id", "") or "")
            title = str(raw.get("title", "") or sid)
            running = bool(raw.get("running", False))
            if needle and needle not in title.lower() and needle not in sid.lower():
                continue
            if status_key in {"running", "active"} and not running:
                continue
            if status_key in {"idle", "stopped"} and running:
                continue
            rows.append(
                {
                    "id": sid,
                    "title": title,
                    "running": running,
                    "degraded": bool(raw.get("degraded", False)),
                    "recovered_at": float(raw.get("recovered_at", 0.0) or 0.0),
                    "recovered_reason": str(raw.get("recovered_reason", "") or ""),
                    "ui_language": normalize_ui_language(raw.get("ui_language", self.user_language)),
                    "updated_at": float(raw.get("updated_at", 0.0) or 0.0),
                    "message_count": int(raw.get("message_count", 0) or 0),
                }
            )
        rows.sort(key=lambda x: x["updated_at"], reverse=True)
        if limit is None:
            return rows
        off = max(0, int(offset or 0))
        lim = max(1, min(2000, int(limit or SESSION_LIST_DEFAULT_LIMIT)))
        return {
            "sessions": rows[off: off + lim],
            "total": len(rows),
            "offset": off,
            "limit": lim,
            "has_more": off + lim < len(rows),
        }
